import type { Lesson } from "../../types";

export const embeddings: Lesson = {
  slug: "embeddings",
  module: "ie",
  order: 3,
  title: "Embeddings and Semantic Similarity",
  tagline: "“borrow money” and “personal loan” share no words — embeddings still put them side by side.",
  difficulty: "Intermediate",
  minutes: 30,
  stages: ["classification", "evidence"],
  why: `Lexical methods compare spellings. Customers don't use your vocabulary: they say "EMI bahut zyada hai" when your taxonomy says "rate / affordability", or "I need some money urgently" when you're looking for "personal loan". **[[Embeddings|embedding]]** map text to vectors so that similar *meanings* land close together, enabling **[[semantic search|semantic-search]]**, clustering and deduplication.

But similarity is a property of the model, not the text. English-only models handle Romanized Hindi poorly, and negations ("I don't want a loan") often sit right next to their positive versions. You must evaluate embeddings on your own data.`,
  concepts: [
    {
      title: "Vectors and cosine similarity",
      intuition: `An embedding model turns a sentence into a list of a few hundred numbers — a point in space. Sentences with similar meaning end up pointing in similar directions. **[[Cosine similarity|cosine-similarity]]** measures that angle: 1 = same direction, 0 = unrelated.`,
      technical: `Sentence encoders (e.g., sentence-transformers such as all-MiniLM-L6-v2, 384-d) are trained with contrastive objectives so paraphrases have high dot products. cos(u, v) = u·v / (‖u‖‖v‖); with L2-normalized vectors it's the dot product. Similarity values aren't comparable across models, and thresholds must be tuned on labelled pairs. Visualize with [[PCA|pca]] or UMAP — but distances in 2D projections are approximate.`,
      example: `In the lab, switch from TF-IDF to the neural model: "borrow money" moves near "personal loan"; "pizza" stays far away. Check where "I don't want a loan" lands — often uncomfortably close to "loan application".`,
    },
    {
      title: "Lexical vs semantic similarity",
      intuition: `**[[TF-IDF|tf-idf]]** (character or word overlap) is cheap, exact and great for typos and IDs, but blind to synonyms. Neural embeddings capture paraphrase but can blur exact distinctions and negation. Many production systems use both (hybrid search).`,
      technical: `TF-IDF vectors are sparse and interpretable; cosine over TF-IDF measures shared (weighted) surface forms. Dense embeddings are learned; they generalize across paraphrases and some languages (multilingual models), but inherit training-data biases and can conflate topic with stance. Hybrid retrieval (BM25 + dense, reciprocal rank fusion) is a strong default for search. Evaluate with labelled similar/dissimilar pairs (AUC) or retrieval recall@k.`,
      example: `Query "customer can't afford the EMI": TF-IDF ranks "EMI is too high" top (shared 'EMI'), misses "bahut mehenga hai". A multilingual dense model can find both — if it handles Romanized Hindi well. Measure it.`,
    },
  ],
  questions: {
    what: "Dense vector representations of text in which semantic similarity corresponds to geometric closeness.",
    why: "Meaning-level matching is needed when wording varies (paraphrase, synonyms, code-mixing).",
    problem: "It enables semantic search, clustering, deduplication and similarity-based features.",
    how: "Encode texts with a pretrained sentence encoder; compare with cosine similarity; index with approximate nearest neighbours for scale.",
    onRealData: "Hinglish and Romanized Hindi challenge English-only models; ASR noise perturbs embeddings; short utterances ('haan') carry little meaning alone.",
    whatCanGoWrong: "Negation blindness, topic-over-stance similarity, poor multilingual coverage, thresholds copied across models, over-trusting 2D plots.",
    howToEvaluate: "Labelled pairs (similar/not) → AUC or accuracy at threshold; retrieval recall@k on real queries; per-language slices.",
    whenToUse: "Semantic search, clustering objections, finding similar calls, retrieving few-shot examples, deduplication.",
    whenNotToUse: "Exact lookups (IDs, rates by key), decisions that hinge on negation, or as the sole classifier without evaluation.",
    downstream: "Embedding choices shape clusters (and thus taxonomies), retrieval quality in RAG, and similarity thresholds.",
  },
  lab: {
    id: "embeddings",
    title: "Embedding explorer",
    intro: "Enter sentences and compare a lexical TF-IDF baseline with a real neural embedding model (all-MiniLM-L6-v2) running in your browser. See a 2D PCA map, a cosine-similarity heatmap and semantic search.",
    modes: ["computed", "real-local"],
  },
  realWorld: {
    text: `A team used an English sentence-transformer to deduplicate objection reasons. Precision looked fine on English; on Romanized-Hindi reasons, unrelated objections ("CIBIL kam hai" and "documents nahi hai") were merged because the model mostly saw shared function words. Switching to a multilingual model and validating on 300 labelled Hinglish pairs raised pair-classification AUC from 0.71 to 0.88.`,
  },
  mistakes: [
    { mistake: "Assuming similarity = same meaning", why: "Negations and opposite stances can be close.", fix: "Evaluate on pairs that differ in stance; don't use similarity alone for decisions." },
    { mistake: "Using an English-only model on Hinglish", why: "Poor coverage of Romanized Hindi.", fix: "Use multilingual models and validate per language." },
    { mistake: "Copying thresholds across models", why: "Similarity scales differ by model.", fix: "Re-tune thresholds on labelled pairs." },
    { mistake: "Reading 2D plots too literally", why: "Projection distorts distances.", fix: "Use plots for intuition; decide with measured similarities." },
  ],
  decision: {
    question: "Lexical, dense or hybrid?",
    useWhen: ["Lexical: exact terms, IDs, typos", "Dense: paraphrase-heavy text, clustering by meaning", "Hybrid: search over real user language"],
    avoidWhen: ["Dense-only when exact terms matter (product codes)", "Lexical-only when users paraphrase heavily"],
    tradeoffs: [
      { a: "Lexical", b: "Semantic", note: "Exactness and explainability vs paraphrase robustness." },
      { a: "Model size", b: "Latency/cost", note: "Larger encoders embed better but cost more per item; batch offline when possible." },
    ],
  },
  exercises: [
    {
      id: "em-ex-1",
      kind: "numeric",
      exType: "applied",
      difficulty: "Intermediate",
      concept: "cosine-similarity",
      prompt: "u = (1, 0, 1), v = (1, 1, 0). Compute cosine similarity (2 decimals).",
      answer: 0.5,
      tolerance: 0.01,
      hint: "u·v / (‖u‖‖v‖).",
      explanation: "u·v = 1; ‖u‖ = ‖v‖ = √2 → 1/2 = **0.50**.",
    },
    {
      id: "em-ex-2",
      kind: "mcq",
      exType: "conceptual",
      difficulty: "Intermediate",
      concept: "embeddings",
      prompt: "Why does TF-IDF give near-zero similarity between 'borrow money' and 'personal loan'?",
      options: [
        { text: "They share no (character/word) features — lexical methods can't see synonyms", correct: true },
        { text: "TF-IDF is broken", whyWrong: "It's working as designed." },
        { text: "They are in different languages", whyWrong: "Both English." },
        { text: "The phrases are too short", whyWrong: "Length isn't the issue." },
      ],
      hint: "What does TF-IDF compare?",
      explanation: "Lexical overlap only.",
    },
    {
      id: "em-ex-3",
      kind: "text",
      exType: "engineering",
      difficulty: "Advanced",
      concept: "embeddings",
      prompt: "How would you choose and validate an embedding model for clustering Hinglish objection reasons?",
      rubric: [
        { idea: "Candidate multilingual models", keywords: ["multilingual", "hinglish", "romanized"] },
        { idea: "Labelled similar/dissimilar pairs from real data", keywords: ["pairs", "label", "similar", "dissimilar"] },
        { idea: "Metric: AUC / accuracy at threshold / recall@k", keywords: ["auc", "recall@k", "recall", "threshold"] },
        { idea: "Include stance/negation hard negatives", keywords: ["negation", "stance", "hard negative", "opposite"] },
        { idea: "Per-language slices", keywords: ["per language", "slice", "by language"] },
      ],
      minIdeas: 3,
      hint: "Treat it like model selection with a small gold set.",
      modelAnswer:
        "Shortlist 2–3 multilingual sentence encoders. Build ~300 labelled pairs from real reasons (same objection vs different), including hard negatives that share words but differ in reason or stance. Compute pair-classification AUC and accuracy at the best threshold, per language slice (English/Hinglish/Romanized Hindi). Pick the best model that fits cost/latency; re-tune clustering thresholds for it.",
      explanation: "Embeddings are models — select them with data.",
    },
  ],
  quiz: [
    {
      id: "em-q-1",
      kind: "mcq",
      difficulty: "Beginner",
      concept: "embeddings",
      prompt: "An embedding is…",
      options: [
        { text: "A vector representation where similar meanings are close", correct: true },
        { text: "A compressed audio file", whyWrong: "No." },
        { text: "A list of keywords", whyWrong: "That's closer to TF-IDF features." },
        { text: "A label", whyWrong: "No." },
      ],
      hint: "Geometry of meaning.",
      explanation: "Dense vectors for semantic similarity.",
    },
    {
      id: "em-q-2",
      kind: "mcq",
      difficulty: "Intermediate",
      concept: "cosine-similarity",
      prompt: "For L2-normalized vectors, cosine similarity equals…",
      options: [
        { text: "The dot product", correct: true },
        { text: "Euclidean distance", whyWrong: "Related but not equal." },
        { text: "Always 1", whyWrong: "No." },
        { text: "The number of dimensions", whyWrong: "No." },
      ],
      hint: "Norms are 1.",
      explanation: "u·v/(1·1).",
    },
    {
      id: "em-q-3",
      kind: "mcq",
      difficulty: "Intermediate",
      concept: "embeddings",
      prompt: "'I want a loan' and 'I don't want a loan' have high embedding similarity. Why is that a problem for intent?",
      options: [
        { text: "Embeddings capture topic strongly; stance/negation differences can be small in vector space", correct: true },
        { text: "It isn't — they mean the same", whyWrong: "Opposite intents." },
        { text: "The model is broken", whyWrong: "It's a known property." },
        { text: "Cosine similarity can't be high", whyWrong: "It can." },
      ],
      hint: "Topic vs stance.",
      explanation: "Don't use raw similarity for stance-dependent decisions.",
    },
    {
      id: "em-q-4",
      kind: "mcq",
      difficulty: "Intermediate",
      concept: "cosine-similarity",
      prompt: "You switch embedding models. Your similarity threshold of 0.8…",
      options: [
        { text: "Must be re-tuned; similarity scales differ between models", correct: true },
        { text: "Stays valid", whyWrong: "Scales differ." },
        { text: "Should be doubled", whyWrong: "No rule like that." },
        { text: "Becomes 0.5 automatically", whyWrong: "No." },
      ],
      hint: "Model-specific geometry.",
      explanation: "Re-tune on labelled pairs.",
    },
    {
      id: "em-q-5",
      kind: "mcq",
      difficulty: "Advanced",
      concept: "embeddings",
      prompt: "A hybrid (BM25 + dense) search is usually better than either alone because…",
      options: [
        { text: "Lexical matching nails exact terms while dense retrieval handles paraphrase", correct: true },
        { text: "It's cheaper", whyWrong: "It's usually more expensive." },
        { text: "It removes the need for evaluation", whyWrong: "No." },
        { text: "Dense retrieval can't handle English", whyWrong: "No." },
      ],
      hint: "Complementary strengths.",
      explanation: "Combine exactness and semantics.",
    },
  ],
  challenge: {
    id: "em-ch-1",
    kind: "numeric",
    exType: "applied",
    difficulty: "Advanced",
    concept: "cosine-similarity",
    prompt: "u = (3, 4), v = (4, 3). Compute cosine similarity (2 decimals).",
    answer: 0.96,
    tolerance: 0.01,
    hint: "u·v = 24; ‖u‖ = ‖v‖ = 5.",
    explanation: "24/25 = **0.96** — nearly the same direction despite different coordinates.",
  },
  related: ["clustering", "fuzzy-matching", "rag-agents"],
  terms: ["embedding", "cosine-similarity", "semantic-search", "tf-idf", "pca"],
};
