import type { Lesson } from "../../types";

export const openClosedSet: Lesson = {
  slug: "open-closed-set",
  module: "ie",
  order: 2,
  title: "Open-set vs Closed-set Classification",
  tagline: "Consistency and governance vs discovery and flexibility — and the hybrid most teams end up with.",
  difficulty: "Intermediate",
  minutes: 25,
  stages: ["classification"],
  why: `Ask "why wasn't the customer interested?" two ways. **[[Closed set|closed-set]]**: pick from {Rate, Eligibility, Documentation, Timing, Other}. **[[Open set|open-set]]**: describe the reason in your own words. Closed sets are consistent, countable and governable — but blind to anything you didn't anticipate. Open sets discover new problems ("the app keeps crashing") — but produce "Rate too high", "Pricing concern" and "High EMI" for the same thing, and different names on every run.

Most production systems need both: closed for measurement, open for discovery, and a governance loop that moves discoveries into the taxonomy.`,
  concepts: [
    {
      title: "The trade-off",
      intuition: `- **Closed set**: consistent, easy to evaluate and trend; can't see new categories.
- **Open set**: finds the unexpected; hard to count, drifts, needs normalization.
- **Hybrid**: closed set + "Other: <free text>", reviewed periodically; recurring "Other" clusters get promoted into the taxonomy.`,
      technical: `Closed-set classification yields categorical outputs evaluable with exact metrics. Open-set generation yields free text; aggregation requires normalization (canonicalization, embedding + clustering, LLM-based consolidation) and its evaluation needs judges or human review. Open-set outputs drift with prompt/model changes (naming instability). Hybrid designs cap the open part to the residual and route it to a discovery pipeline (see [[clustering]]).`,
      example: `16 objection utterances: closed-set intent labels collapse them into "Not Interested"; open-set reasons produce 11–13 distinct strings per run; clustering the strings recovers Rate, Eligibility, Timing, Documentation — plus a new "Digital experience" cluster worth adding to the taxonomy.`,
    },
  ],
  questions: {
    what: "Closed set: predict from a fixed label list. Open set: generate or discover categories not fixed in advance.",
    why: "Measurement needs stable categories; the world produces new ones.",
    problem: "Choosing well balances comparability over time with the ability to discover new issues.",
    how: "Closed: enum outputs + exact metrics. Open: free-text reasons → normalize/cluster → human review. Hybrid: both, with a promotion loop.",
    onRealData: "Objection reasons have a long tail; new product/app issues appear suddenly; free-text reasons vary by run and model.",
    whatCanGoWrong: "Closed sets that silently absorb new issues into 'Other'; open sets that fragment and drift; no owner for taxonomy updates.",
    howToEvaluate: "Closed: per-class metrics. Open: cluster purity against human-reviewed samples, naming stability across runs, human usefulness ratings.",
    whenToUse: "Closed for KPIs and compliance; open for discovery phases; hybrid for ongoing production monitoring.",
    whenNotToUse: "Open-set outputs as direct KPIs; closed sets during early exploration of a new product.",
    downstream: "Determines what dashboards can show, how quickly new issues surface, and how much review effort is needed.",
  },
  lab: {
    id: "open-closed-set",
    title: "Open vs closed set simulation",
    intro: "See the same 16 objections through a closed set, an open set across three runs (naming drift), and a discover-then-govern hybrid. Finish with a trade-off matrix and four scenarios.",
    modes: ["precomputed"],
  },
  realWorld: {
    text: `A closed objection taxonomy tracked "Other" at a steady 8%. When a bank's mobile app broke during a release, "Other" rose to 14% — a signal nobody read, because "Other" wasn't reviewed. A weekly job now clusters "Other" free-text reasons; a spike in a coherent cluster pages the product owner. The "Digital experience" category was added (v3.2) after three weeks.`,
  },
  mistakes: [
    { mistake: "Never reading 'Other'", why: "New issues hide there.", fix: "Cluster and review 'Other' regularly." },
    { mistake: "Using open-set labels as KPIs", why: "Naming drift makes counts meaningless over time.", fix: "Normalize into governed categories before counting." },
    { mistake: "Closed sets frozen forever", why: "The taxonomy goes stale.", fix: "Version and promote recurring clusters." },
  ],
  decision: {
    question: "Closed, open or hybrid?",
    useWhen: ["Closed: KPIs, compliance, trend reporting", "Open: new products, exploratory research", "Hybrid: steady-state production with discovery"],
    avoidWhen: ["Open for KPIs", "Closed without an 'Other' review process"],
    tradeoffs: [
      { a: "Consistency", b: "Discovery", note: "Closed sets are stable; open sets see the unexpected." },
      { a: "Governance", b: "Flexibility", note: "Owned, versioned categories vs cheap, fast label space changes." },
    ],
  },
  exercises: [
    {
      id: "oc-ex-1",
      kind: "mcq",
      exType: "applied",
      difficulty: "Beginner",
      concept: "open-vs-closed-set",
      prompt: "A board-level monthly KPI: '% of calls lost to rate objections'. Closed or open?",
      options: [
        { text: "Closed", correct: true },
        { text: "Open", whyWrong: "Naming drift breaks monthly comparisons." },
        { text: "Either", whyWrong: "KPIs need stable definitions." },
        { text: "Neither", whyWrong: "Closed fits." },
      ],
      hint: "Comparability over time.",
      explanation: "Stable, governed categories.",
    },
    {
      id: "oc-ex-2",
      kind: "mcq",
      exType: "applied",
      difficulty: "Intermediate",
      concept: "open-vs-closed-set",
      prompt: "A new credit product launched last week; nobody knows why customers decline. Best first approach?",
      options: [
        { text: "Open-set reasons, then cluster and read them", correct: true },
        { text: "Closed set copied from the loan taxonomy", whyWrong: "It may miss product-specific reasons." },
        { text: "No analysis until the taxonomy is final", whyWrong: "You need data to design the taxonomy." },
        { text: "Only count 'Not Interested'", whyWrong: "Loses the reasons." },
      ],
      hint: "Discovery phase.",
      explanation: "Discover first, then govern.",
    },
    {
      id: "oc-ex-3",
      kind: "text",
      exType: "engineering",
      difficulty: "Advanced",
      concept: "open-vs-closed-set",
      prompt: "Design a hybrid objection pipeline: outputs, discovery loop and governance.",
      rubric: [
        { idea: "Closed enum + 'other' with free-text reason", keywords: ["enum", "closed", "other", "free text", "free-text"] },
        { idea: "Periodic clustering of 'other' reasons (embeddings)", keywords: ["cluster", "embedding", "weekly", "monthly", "periodic"] },
        { idea: "Human review / owner decides promotions", keywords: ["review", "owner", "human", "promote"] },
        { idea: "Versioning + relabel/back-map + update gold set", keywords: ["version", "back-map", "relabel", "gold"] },
      ],
      minIdeas: 3,
      hint: "Measure, discover, govern.",
      modelAnswer:
        "Output: objection ∈ {rate, eligibility, documentation, timing, other} plus other_reason (free text, only when 'other'). Weekly: embed and cluster other_reasons, surface clusters with size/growth and examples. A taxonomy owner reviews; recurring, actionable clusters get a definition, examples and a version bump. Relabel a sample, update the gold set and prompts, and back-map history for trend continuity.",
      explanation: "The hybrid gives stable metrics and a path for new categories.",
    },
    {
      id: "oc-ex-4",
      kind: "mcq",
      exType: "conceptual",
      difficulty: "Intermediate",
      concept: "open-vs-closed-set",
      prompt: "Why are open-set labels hard to use directly as KPIs?",
      options: [
        { text: "The same reason is phrased differently across calls and runs, so counts fragment and drift", correct: true },
        { text: "They are always wrong", whyWrong: "They're often accurate descriptions — just not stable categories." },
        { text: "They can't be stored in a database", whyWrong: "Storage isn't the problem." },
        { text: "They only work in English", whyWrong: "Language isn't the issue." },
      ],
      hint: "'Rate too high' vs 'Pricing concern'.",
      explanation: "Normalize open-set outputs into governed categories before counting them.",
    },
  ],
  quiz: [
    {
      id: "oc-q-1",
      kind: "mcq",
      difficulty: "Beginner",
      concept: "open-vs-closed-set",
      prompt: "Main advantage of open-set extraction:",
      options: [
        { text: "Discovering categories you didn't anticipate", correct: true },
        { text: "Perfect consistency", whyWrong: "That's closed-set." },
        { text: "Easy exact-match evaluation", whyWrong: "That's closed-set." },
        { text: "No need for review", whyWrong: "Open-set needs more review." },
      ],
      hint: "Unknown unknowns.",
      explanation: "Discovery.",
    },
    {
      id: "oc-q-2",
      kind: "mcq",
      difficulty: "Intermediate",
      concept: "open-vs-closed-set",
      prompt: "'Rate too high', 'Pricing concern' and 'High EMI' across runs illustrate…",
      options: [
        { text: "Naming drift / fragmentation in open-set outputs", correct: true },
        { text: "Hallucination", whyWrong: "The reasons are real; the names vary." },
        { text: "Class imbalance", whyWrong: "No." },
        { text: "Calibration", whyWrong: "No." },
      ],
      hint: "Same meaning, different strings.",
      explanation: "Open-set outputs need normalization before counting.",
    },
    {
      id: "oc-q-3",
      kind: "mcq",
      difficulty: "Intermediate",
      concept: "open-vs-closed-set",
      prompt: "The biggest risk of a closed set with 'Other' is…",
      options: [
        { text: "New issues accumulate unnoticed in 'Other'", correct: true },
        { text: "Too many categories", whyWrong: "Not inherent." },
        { text: "Naming drift", whyWrong: "That's open-set." },
        { text: "It can't be evaluated", whyWrong: "It can." },
      ],
      hint: "Where do surprises go?",
      explanation: "Review 'Other' regularly.",
    },
    {
      id: "oc-q-4",
      kind: "mcq",
      difficulty: "Intermediate",
      concept: "open-vs-closed-set",
      prompt: "How do you turn open-set reasons into countable categories?",
      options: [
        { text: "Normalize them (embed + cluster, or LLM consolidation) into reviewed categories", correct: true },
        { text: "Count exact strings", whyWrong: "Fragmentation makes counts meaningless." },
        { text: "Sort alphabetically", whyWrong: "No." },
        { text: "Ask the model to count", whyWrong: "Unreliable without a fixed set." },
      ],
      hint: "Group by meaning.",
      explanation: "Normalization + human review.",
    },
    {
      id: "oc-q-5",
      kind: "mcq",
      difficulty: "Advanced",
      concept: "open-vs-closed-set",
      prompt: "After adding 'Digital experience' to the taxonomy, what else must happen for trends to stay meaningful?",
      options: [
        { text: "Version the taxonomy, update guidelines/prompts/gold set, and back-map historical 'Other' where possible", correct: true },
        { text: "Nothing", whyWrong: "Counts before/after aren't comparable otherwise." },
        { text: "Delete old data", whyWrong: "No." },
        { text: "Retrain annotators only", whyWrong: "Necessary but not sufficient." },
      ],
      hint: "Governance.",
      explanation: "Taxonomy changes ripple through the whole system.",
    },
  ],
  challenge: {
    id: "oc-ch-1",
    kind: "label",
    exType: "applied",
    difficulty: "Advanced",
    concept: "open-vs-closed-set",
    prompt: "Choose the approach for each need.",
    labels: ["Closed", "Open", "Hybrid"],
    passThreshold: 0.75,
    items: [
      { text: "Regulatory report: % of calls with the mandatory disclosure", answer: "Closed" },
      { text: "Explore why customers reject a brand-new product", answer: "Open" },
      { text: "Ongoing objection monitoring that must also catch new issues", answer: "Hybrid" },
      { text: "Quarterly board KPI on rate objections", answer: "Closed" },
    ],
    hint: "Measurement vs discovery.",
    explanation: "Closed for measurement, open for discovery, hybrid for both.",
  },
  related: ["taxonomy-design", "clustering", "embeddings"],
  terms: ["closed-set", "open-set", "taxonomy", "clustering"],
};
