import type { Lesson } from "../../types";

export const taxonomyDesign: Lesson = {
  slug: "taxonomy-design",
  module: "ie",
  order: 1,
  title: "Taxonomy Design",
  tagline: "Labels are a product: one dimension per field, mutually exclusive siblings, an honest 'other'.",
  difficulty: "Advanced",
  minutes: 35,
  stages: ["classification", "evaluation"],
  why: `A **[[taxonomy]]** is the vocabulary your whole system speaks: what the prompt asks for, what annotators label, what dashboards count. A flawed taxonomy can't be fixed downstream — overlapping categories cap agreement, missing categories force wrong labels, mixed dimensions make metrics meaningless.

Good taxonomies are designed deliberately: separate dimensions (product, intent, objection) into separate fields, make siblings **[[mutually exclusive and collectively exhaustive|mece]]**, keep depth shallow enough to label reliably, and give every set an explicit abstain/other option.`,
  concepts: [
    {
      title: "Dimensions, exclusivity and exhaustiveness",
      intuition: `Ask of every label set: "Is this one question?" Product (which loan?), intent (do they want it?) and objection (why not?) are three questions — three fields. Within a field, each call should fit exactly one label (exclusive), and every call should fit some label (exhaustive — which is what "Other"/"Insufficient evidence" is for).`,
      technical: `A label set is MECE if its categories partition the input space. Violations: overlap (two labels apply → annotator disagreement), gaps (no label applies → forced errors), and dimension mixing (labels answer different questions → a call legitimately has several). Hierarchies add parent/child consistency constraints and allow back-off. Test with a coverage exercise: label a realistic sample and count "fits none" and "fits several".`,
      example: `Bad: {Personal Loan, Interested, Existing Customer, Not Interested, Callback}. Good: product ∈ {personal, home, vehicle, unspecified}; intent ∈ {interested, not_interested, insufficient_evidence}; objections ⊆ {rate/affordability, eligibility, documentation, timing, other}.`,
    },
    {
      title: "Depth, granularity and governance",
      intuition: `Deeper trees look precise but each leaf gets fewer examples and more disagreement. Keep leaves you can label reliably and act on. Treat the taxonomy like an API: versioned, owned, with definitions, and changed deliberately.`,
      technical: `Granularity trade-off: more categories → more information but lower agreement and sparser training/eval data per class. Heuristics: ≥ ~50 gold examples per leaf you evaluate; depth ≤ 3; merge siblings with persistent low agreement; split categories when a cluster of "Other" is large, coherent and actionable. Version the taxonomy; map old versions to new for trend continuity.`,
      example: `"Rate concern", "Pricing issue" and "EMI too high" are one objection ("rate / affordability") with sub-flavours. Merge them unless the business acts differently on each.`,
    },
  ],
  questions: {
    what: "The designed set of categories (and their relations) that a system uses to label content.",
    why: "Every downstream artifact — prompts, guidelines, gold labels, metrics, dashboards — inherits the taxonomy.",
    problem: "It makes labels reliable, actionable and comparable over time.",
    how: "Separate dimensions into fields; make siblings exclusive; add abstain/other; keep depth shallow; test coverage on real data; version and govern.",
    onRealData: "Calls mix products and intents; objections have a long tail; new issues (app outages) appear without warning.",
    whatCanGoWrong: "Mixed dimensions, overlapping siblings, missing abstain, overly deep leaves, unused labels, silent changes.",
    howToEvaluate: "Coverage tests (fits none/several), inter-annotator agreement per label, label frequency, confusion between siblings.",
    whenToUse: "Before annotation, prompting or dashboard design — and on a regular review cadence.",
    whenNotToUse: "Don't over-design for categories that never occur or that nobody acts on.",
    downstream: "Taxonomy flaws show up as low κ, noisy metrics, confused prompts and misleading dashboards.",
  },
  lab: {
    id: "taxonomy-design",
    title: "Taxonomy builder",
    intro: "Load a bad taxonomy (mixed dimensions, overlapping siblings, too deep) and fix it with drag-and-drop until the linter is happy. Then test coverage: can every real utterance get exactly one leaf?",
    modes: ["computed"],
  },
  realWorld: {
    text: `An objection dashboard showed "Pricing issue" falling 30% after a relaunch — celebrated as a pricing win. In reality, annotators had started using the newly added "EMI too high" label for the same calls. The underlying objection rate hadn't moved. After merging the overlapping labels (with a sub-reason field) and back-mapping history, the trend was flat.`,
  },
  mistakes: [
    { mistake: "Mixing dimensions in one label list", why: "A call can legitimately have several labels; annotators split arbitrarily.", fix: "One field per dimension." },
    { mistake: "Overlapping siblings", why: "Two labels describe the same thing → disagreement and fake trends.", fix: "Merge; use sub-reasons if needed." },
    { mistake: "No 'other/insufficient' option", why: "Gaps force wrong labels.", fix: "Add an explicit abstain/other with a definition." },
    { mistake: "Unversioned changes", why: "Trends break silently.", fix: "Version and back-map." },
  ],
  decision: {
    question: "Should you add, split or merge a category?",
    useWhen: ["Add: a recurring, actionable 'Other' cluster", "Split: a category whose sub-types need different actions and can be labelled reliably", "Merge: siblings with persistent disagreement or no distinct action"],
    avoidWhen: ["Adding categories for rare, non-actionable cases", "Changing definitions without versioning"],
    tradeoffs: [
      { a: "Granularity", b: "Agreement", note: "Finer labels carry more information but are labelled less consistently." },
      { a: "Stability", b: "Discovery", note: "A fixed taxonomy enables trends; the world keeps inventing new categories (see Open vs Closed Set)." },
    ],
  },
  exercises: [
    {
      id: "tx-ex-1",
      kind: "mcq",
      exType: "conceptual",
      difficulty: "Intermediate",
      concept: "taxonomy-dimensions",
      prompt: "What's wrong with the multi-class label set {Personal Loan, Interested, Existing Customer, Not Interested}?",
      options: [
        { text: "It mixes dimensions (product, intent, customer status), so labels aren't mutually exclusive", correct: true },
        { text: "Too few labels", whyWrong: "Count isn't the problem." },
        { text: "Labels should be lowercase", whyWrong: "Cosmetic." },
        { text: "Nothing", whyWrong: "An existing customer interested in a personal loan fits three labels." },
      ],
      hint: "Can one call fit several?",
      explanation: "Separate fields: product, intent, customer_status.",
    },
    {
      id: "tx-ex-2",
      kind: "multi",
      exType: "applied",
      difficulty: "Intermediate",
      concept: "taxonomy-boundaries",
      prompt: "Objection labels: {Rate concern, Pricing issue, EMI too high, Documentation, Paperwork hassle, Timing}. Which pairs/groups overlap? (Select all)",
      options: [
        { text: "Rate concern / Pricing issue / EMI too high", correct: true },
        { text: "Documentation / Paperwork hassle", correct: true },
        { text: "Timing / Documentation", whyWrong: "Different reasons." },
        { text: "Rate concern / Timing", whyWrong: "Different reasons." },
      ],
      hint: "Same underlying objection, different words.",
      explanation: "Merge into 'Rate / affordability' and 'Documentation'.",
    },
    {
      id: "tx-ex-3",
      kind: "json",
      exType: "engineering",
      difficulty: "Advanced",
      concept: "taxonomy-dimensions",
      prompt: "Write a taxonomy as JSON with three fields: `product` (array of allowed values, must include 'unspecified'), `intent` (must include 'insufficient_evidence'), `objection` (must include 'other'). Each list should have 3–6 values.",
      starter: `{
  "product": [],
  "intent": [],
  "objection": []
}`,
      checks: [
        { label: "product includes 'unspecified'", test: (v) => Array.isArray(v?.product) && v.product.includes("unspecified") },
        { label: "intent includes 'insufficient_evidence'", test: (v) => Array.isArray(v?.intent) && v.intent.includes("insufficient_evidence") },
        { label: "objection includes 'other'", test: (v) => Array.isArray(v?.objection) && v.objection.includes("other") },
        { label: "each list has 3–6 values", test: (v) => ["product", "intent", "objection"].every((k) => Array.isArray(v?.[k]) && v[k].length >= 3 && v[k].length <= 6) },
        { label: "intent contains no product words", test: (v) => Array.isArray(v?.intent) && !v.intent.some((x: string) => /loan|card/i.test(x)) },
      ],
      hint: "One dimension per field; each with an honest fallback.",
      modelAnswer: `{
  "product": ["personal_loan", "home_loan", "vehicle_loan", "unspecified"],
  "intent": ["interested", "not_interested", "insufficient_evidence"],
  "objection": ["rate_affordability", "eligibility", "documentation", "timing", "other"]
}`,
      explanation: "Separate dimensions, exclusive values, explicit fallbacks.",
    },
  ],
  quiz: [
    {
      id: "tx-q-1",
      kind: "mcq",
      difficulty: "Beginner",
      concept: "taxonomy-boundaries",
      prompt: "MECE stands for…",
      options: [
        { text: "Mutually Exclusive, Collectively Exhaustive", correct: true },
        { text: "Multi-Entity Classification Engine", whyWrong: "No." },
        { text: "Minimum Error, Complete Evaluation", whyWrong: "No." },
        { text: "Machine-Extracted Category Evidence", whyWrong: "No." },
      ],
      hint: "No overlaps, no gaps.",
      explanation: "Every item fits exactly one category.",
    },
    {
      id: "tx-q-2",
      kind: "mcq",
      difficulty: "Intermediate",
      concept: "taxonomy-boundaries",
      prompt: "In a coverage test, 15% of utterances 'fit none'. Most likely fix?",
      options: [
        { text: "Add a missing category or an explicit 'other'", correct: true },
        { text: "Force annotators to pick the closest label", whyWrong: "Creates label noise." },
        { text: "Delete those utterances", whyWrong: "They exist in production." },
        { text: "Add more depth", whyWrong: "Doesn't address gaps." },
      ],
      hint: "Exhaustiveness.",
      explanation: "Gaps need categories or an honest fallback.",
    },
    {
      id: "tx-q-3",
      kind: "mcq",
      difficulty: "Intermediate",
      concept: "taxonomy-boundaries",
      prompt: "A parent with a single child ('Retail → Unsecured → Personal Loan') suggests…",
      options: [
        { text: "An unnecessary level that adds no information", correct: true },
        { text: "A well-balanced tree", whyWrong: "Single-child levels add depth without discrimination." },
        { text: "Missing examples", whyWrong: "Different issue." },
        { text: "High agreement", whyWrong: "Unrelated." },
      ],
      hint: "What decision does that level make?",
      explanation: "Collapse single-child chains.",
    },
    {
      id: "tx-q-4",
      kind: "mcq",
      difficulty: "Intermediate",
      concept: "taxonomy-dimensions",
      prompt: "An objection trend drops sharply right after a new sibling label was introduced. First suspicion?",
      options: [
        { text: "Label migration between overlapping categories, not a real change", correct: true },
        { text: "Customers changed behaviour overnight", whyWrong: "Possible, but check the taxonomy change first." },
        { text: "Model improvement", whyWrong: "Unlikely to cause a category-specific cliff." },
        { text: "Seasonality", whyWrong: "Coincides with the taxonomy change." },
      ],
      hint: "What else changed?",
      explanation: "Overlapping labels split counts; back-map before interpreting trends.",
    },
    {
      id: "tx-q-5",
      kind: "mcq",
      difficulty: "Advanced",
      concept: "taxonomy-boundaries",
      prompt: "When should you split 'Documentation' into 'Missing salary slips' and 'KYC friction'?",
      options: [
        { text: "When the business acts differently on each AND annotators can distinguish them reliably", correct: true },
        { text: "Whenever possible — finer is better", whyWrong: "Finer labels cost agreement." },
        { text: "Never", whyWrong: "Actionable, reliable splits are valuable." },
        { text: "Only if the model asks", whyWrong: "No." },
      ],
      hint: "Actionability + reliability.",
      explanation: "Split for distinct actions, verified by agreement.",
    },
  ],
  challenge: {
    id: "tx-ch-1",
    kind: "text",
    exType: "engineering",
    difficulty: "Expert",
    concept: "taxonomy-dimensions",
    prompt: "The product team wants 25 objection categories. Annotator pilot κ is 0.38 on those 25 and 0.74 on a 6-category version. Propose a design that serves both needs.",
    rubric: [
      { idea: "Hierarchy: 6 coarse parents with finer children", keywords: ["hierarch", "parent", "coarse", "children", "two-level", "sub"] },
      { idea: "Report/decide at the reliable level", keywords: ["report", "reliable", "coarse level", "parent level", "6"] },
      { idea: "Keep fine-grained as optional / free text / sub-reason", keywords: ["optional", "free text", "sub-reason", "secondary"] },
      { idea: "Promote children to official when agreement is sufficient", keywords: ["promote", "agreement", "κ", "kappa", "when reliable"] },
    ],
    minIdeas: 3,
    hint: "Two levels, used differently.",
    modelAnswer:
      "Use a two-level hierarchy: 6 reliable parent categories (κ 0.74) drive dashboards and KPIs; the 25 fine categories become children or a sub-reason field used for exploration, reported with caveats. Track per-child agreement; promote a child to an official reporting category once its κ and volume are sufficient, and merge children that stay unreliable.",
    explanation: "Hierarchies let you report where labels are reliable while keeping detail for discovery.",
  },
  related: ["text-classification", "open-closed-set", "annotation-guidelines"],
  terms: ["taxonomy", "mece", "hierarchical-classification", "multi-label"],
};
