import type { Lesson } from "../../types";

export const dialogueStructure: Lesson = {
  slug: "dialogue-structure",
  module: "nlp",
  order: 5,
  title: "Dialogue and Discourse Structure",
  tagline: "A call is not a bag of sentences: turns, dialogue acts, adjacency pairs and segments.",
  difficulty: "Intermediate",
  minutes: 30,
  stages: ["transcript", "classification", "evidence"],
  why: `A customer saying “yes” means nothing on its own. It means *I'm salaried* after “aap salaried ho?”, and *send me the link* after “shall I send the link?”. Conversations have structure: who speaks when (**[[turn-taking]]**), what each utterance does (**[[dialogue acts|dialogue-act]]**), which utterances belong together (**[[adjacency pairs|adjacency-pair]]**), and which phase the call is in (**[[segmentation]]**).

Every downstream stage benefits: evidence extraction looks for answers to qualification questions, intent classification weighs the closing more than the opening, and QA teams measure what agents do in each segment.`,
  concepts: [
    {
      title: "Dialogue acts",
      intuition: `Label each utterance by its *job*: greeting, question, answer, request, objection, refusal, confirmation, clarification, closing — and “inform” for statements like a sales pitch. The same words can do different jobs: “haan” can be an answer, a confirmation, or just a back-channel meaning “I'm listening”.`,
      technical: `Dialogue-act tagging assigns a communicative function to each functional segment, following schemes like DAMSL or ISO 24617-2. It's a sequence-labelling problem: context (previous acts, speaker) strongly conditions the label, so models that see the preceding turn (CRF, sequence transformers, or LLMs given the whole call) beat per-utterance classifiers.`,
      example: `Agent: “ji sir kitne ka chahiye” → **Question**. Customer: “around five lac” → **Answer**. Customer: “14 percent bahut zyada hai” → **Objection**. Customer: “nahi nahi rehne do, not interested” → **Refusal**.`,
    },
    {
      title: "Adjacency pairs and conversation segments",
      intuition: `Some utterances come in pairs: question → answer, offer → accept/decline, greeting → greeting. The first part makes the second expected. A bare answer is only interpretable through its pair.

Calls also move through phases: **Opening → Discovery → Qualification → Offer → Objection handling → Closing**. A topic shift (“aur credit card ka bhi bata do”) can start a new mini-conversation about another product.`,
      technical: `Conversation analysis defines an adjacency pair as two turns by different speakers where the first pair part (FPP) makes a specific second pair part (SPP) conditionally relevant. Computationally: link each FPP act to the nearest subsequent SPP act by the other speaker (with insertion sequences allowed). Segmentation can use act patterns, keyword cues, or topic-shift detection with embeddings (TextTiling-style similarity drops).`,
      example: `In c08, the customer's objection “to much hai yaar” is answered by the agent's counter-offer (5 years), and the customer's final “haan fir theek hai… process kya hai” closes the objection-handling segment with acceptance. A classifier reading only the objection turn gets the intent wrong.`,
    },
  ],
  questions: {
    what: "The structural organization of conversation: turns, the function of each utterance (dialogue acts), links between utterances (adjacency pairs) and phases (segments/topics).",
    why: "Meaning in dialogue is distributed across turns; single utterances are often uninterpretable.",
    problem: "It lets systems locate evidence (answers to specific questions), weight later stances over earlier ones, and analyze agent behaviour per phase.",
    how: "Annotate or predict acts per turn using the turn text plus context; link first and second pair parts; group turns into segments by act patterns or topic shifts.",
    onRealData: "ASR merges or splits turns, back-channels (“haan”, “ji”) interleave with speech, Hinglish discourse markers (“aur”, “toh”, “matlab”) signal shifts, and diarization errors break pairs.",
    whatCanGoWrong: "Ambiguous acts (Inform vs Answer), back-channels mistaken for agreement, pairs broken by insertion sequences, and topic shifts that mix intents for multiple products in one call.",
    howToEvaluate: "Act-level accuracy/macro-F1 against annotated turns, pair-linking F1, and segment boundary F1 (with tolerance windows). Measure agreement between annotators first — acts are subjective.",
    whenToUse: "Evidence extraction, agent QA (did the agent qualify, handle objections, close?), intent over time, and summarization structure.",
    whenNotToUse: "Don't build an elaborate act taxonomy if the downstream task only needs the final customer stance — an LLM given the whole call may suffice.",
    downstream: "Acts and pairs locate evidence; segments give context windows for long calls; act errors propagate into intent (e.g., reading a back-channel 'haan' as agreement).",
  },
  lab: {
    id: "dialogue-structure",
    title: "Conversation viewer & dialogue-act annotator",
    intro: "Label each utterance's dialogue act, compare with the reference, then see the conversation flow, adjacency pairs and segment boundaries built from your labels.",
    modes: ["precomputed", "computed"],
  },
  realWorld: {
    text: `A QA team wanted to know whether agents *qualify* customers before pitching. Dialogue-act tagging plus segmentation let them measure, per agent, the fraction of calls where a Qualification segment (employment, income, tenure questions answered by the customer) precedes the Offer segment. Agents with low qualification rates had 2× more post-sale cancellations — a finding impossible to get from call-level intent labels alone.`,
    transcript: [
      { speaker: "Agent", text: "Hello sir, how can I help you?" },
      { speaker: "Customer", text: "Mujhe loan ke regarding jaana tha." },
      { speaker: "Agent", text: "Sure sir. How much loan are you looking for?" },
      { speaker: "Customer", text: "Around 5 lakh." },
      { speaker: "Agent", text: "Okay sir. Are you currently employed?" },
      { speaker: "Customer", text: "Yes." },
    ],
  },
  mistakes: [
    { mistake: "Classifying utterances without context", why: "“Yes”, “haan”, “ok” change meaning with the preceding question.", fix: "Feed the previous turn(s) or the whole call; link adjacency pairs." },
    { mistake: "Treating back-channels as agreement", why: "“haan… haan…” while the agent talks often means 'I'm listening'.", fix: "Distinguish back-channel acts from answers/confirmations." },
    { mistake: "Letting an early objection decide the call", why: "Objections are often resolved later in the call.", fix: "Weight the final customer stance; model objection → resolution sequences." },
  ],
  decision: {
    question: "Do you need explicit dialogue structure, or can an LLM read the whole call?",
    useWhen: ["You measure agent behaviour per phase (QA, compliance)", "Calls are long and you need to select relevant segments", "Evidence must be tied to specific question→answer pairs"],
    avoidWhen: ["The only output is a call-level label and calls are short", "You can't afford to annotate acts reliably"],
    tradeoffs: [
      { a: "Explicit act tagging", b: "End-to-end LLM", note: "Explicit structure is measurable and reusable; end-to-end is simpler but opaque." },
      { a: "Fine-grained acts", b: "Coarse acts", note: "More categories capture nuance but lower agreement; start coarse." },
    ],
  },
  exercises: [
    {
      id: "dlg-ex-1",
      kind: "label",
      exType: "applied",
      difficulty: "Beginner",
      concept: "dialogue-acts",
      prompt: "Label each utterance with its dialogue act.",
      labels: ["Greeting", "Question", "Answer", "Request", "Objection", "Refusal", "Confirmation", "Closing"],
      passThreshold: 0.75,
      items: [
        { speaker: "Agent", text: "Hello sir, how can I help you?", answer: "Greeting" },
        { speaker: "Customer", text: "Mujhe loan ke regarding jaana tha.", answer: "Request" },
        { speaker: "Agent", text: "How much loan are you looking for?", answer: "Question" },
        { speaker: "Customer", text: "Around 5 lakh.", answer: "Answer" },
        { speaker: "Customer", text: "14 percent bahut zyada hai", answer: "Objection", note: "An objection states a reason against the offer." },
        { speaker: "Customer", text: "nahi rehne do, not interested", answer: "Refusal" },
        { speaker: "Customer", text: "haan bhej do", answer: "Confirmation", note: "Agrees to the agent's proposal to send documents." },
        { speaker: "Agent", text: "okay sir thank you for your time", answer: "Closing" },
      ],
      hint: "Ask: what is this utterance trying to DO?",
      explanation: "Objection vs Refusal is the classic confusion: an objection gives a reason and may be resolved; a refusal ends the negotiation.",
    },
    {
      id: "dlg-ex-2",
      kind: "mcq",
      exType: "conceptual",
      difficulty: "Intermediate",
      concept: "adjacency-pairs",
      transcript: [
        { speaker: "Agent", text: "sir aap salaried ho?" },
        { speaker: "Customer", text: "haan" },
        { speaker: "Agent", text: "aur loan kitne ka chahiye, 5 lakh theek hai?" },
        { speaker: "Customer", text: "haan" },
      ],
      prompt: "What does the customer's second “haan” tell you?",
      options: [
        { text: "It confirms 5 lakh is acceptable — but it's a response to a leading question, so the evidence is weak", correct: true },
        { text: "It confirms the customer is salaried", whyWrong: "That was the first 'haan'. Pairs matter." },
        { text: "Nothing — 'haan' is always a back-channel", whyWrong: "Here it's a second pair part to a direct question." },
        { text: "The customer wants to apply today", whyWrong: "Nothing about timing was asked." },
      ],
      hint: "Link each 'haan' to the question it answers.",
      explanation: "Adjacency pairs give 'haan' its meaning. Note also that a 'haan' to an agent's leading question is weaker evidence than the customer volunteering an amount.",
    },
    {
      id: "dlg-ex-3",
      kind: "text",
      exType: "engineering",
      difficulty: "Intermediate",
      concept: "segmentation",
      prompt: "Your intent classifier reads calls up to 40 minutes long and misses late acceptances after objections. Propose how dialogue structure could fix this.",
      rubric: [
        { idea: "Segment the call (e.g., objection handling / closing)", keywords: ["segment", "phase", "closing", "objection handling"] },
        { idea: "Prioritize the final customer stance / later turns", keywords: ["final", "last", "later", "most recent", "end of the call"] },
        { idea: "Model objection → resolution sequences / adjacency pairs", keywords: ["resolution", "resolved", "adjacency", "pair", "counter-offer"] },
        { idea: "Evaluate on calls with objections (a slice)", keywords: ["slice", "evaluate", "subset", "objection calls", "measure"] },
      ],
      minIdeas: 2,
      hint: "Where in the call does the final decision usually live?",
      modelAnswer:
        "Tag dialogue acts and segment the call; feed the classifier the objection-handling and closing segments (plus a summary of earlier ones) instead of truncating. Instruct/feature-engineer to judge the final customer stance, linking objections to agent counter-offers and the customer's response. Evaluate specifically on the slice of calls containing objections.",
      explanation: "Structure lets you select the right context and interpret late turns correctly.",
    },
  ],
  quiz: [
    {
      id: "dlg-q-1",
      kind: "mcq",
      difficulty: "Beginner",
      concept: "dialogue-acts",
      prompt: "A dialogue act describes…",
      options: [
        { text: "What an utterance does in the conversation (asking, answering, refusing…)", correct: true },
        { text: "Who spoke the utterance", whyWrong: "That's speaker attribution." },
        { text: "The topic of the call", whyWrong: "That's topic/segment." },
        { text: "The sentiment of the utterance", whyWrong: "Sentiment is a separate dimension." },
      ],
      hint: "Function, not content.",
      explanation: "Acts capture communicative function.",
    },
    {
      id: "dlg-q-2",
      kind: "mcq",
      difficulty: "Intermediate",
      concept: "dialogue-acts",
      prompt: "Customer: “haan… haan…” while the agent explains the processing fee. Most likely act?",
      options: [
        { text: "Back-channel (acknowledgement that they're listening)", correct: true },
        { text: "Confirmation of the purchase", whyWrong: "Nothing was proposed yet; it's listening behaviour." },
        { text: "Refusal", whyWrong: "No." },
        { text: "Request", whyWrong: "No." },
      ],
      hint: "It happens WHILE the other person talks.",
      explanation: "Back-channels signal attention, not agreement — a classic source of over-inferred interest.",
    },
    {
      id: "dlg-q-3",
      kind: "mcq",
      difficulty: "Intermediate",
      concept: "adjacency-pairs",
      prompt: "Which is an adjacency pair?",
      options: [
        { text: "Agent: 'Shall I send the link?' → Customer: 'haan bhej do'", correct: true },
        { text: "Agent: 'Hello' → Agent: 'How are you?'", whyWrong: "Same speaker — not a pair." },
        { text: "Customer: 'EMI zyada hai' → Customer: 'rate bhi zyada hai'", whyWrong: "Same speaker, both statements." },
        { text: "Two unrelated turns far apart", whyWrong: "Pairs are (near-)adjacent and functionally linked." },
      ],
      hint: "Different speakers; first part makes the second expected.",
      explanation: "Offer/question → accept/answer by the other speaker.",
    },
    {
      id: "dlg-q-4",
      kind: "mcq",
      difficulty: "Intermediate",
      concept: "segmentation",
      prompt: "“ok aur credit card ka bhi bata do” most likely marks…",
      options: [
        { text: "A topic shift to a new product", correct: true },
        { text: "The end of the call", whyWrong: "The customer is starting a new topic." },
        { text: "A refusal", whyWrong: "No refusal content." },
        { text: "A greeting", whyWrong: "No." },
      ],
      hint: "'aur' = 'and also'.",
      explanation: "Discourse markers like 'aur' often introduce a new topic — here a second product with its own intent.",
    },
    {
      id: "dlg-q-5",
      kind: "mcq",
      difficulty: "Advanced",
      concept: "segmentation",
      prompt: "Why does a call with an objection followed by acceptance trip up per-utterance classifiers?",
      options: [
        { text: "The objection turn looks negative in isolation; the resolution appears later", correct: true },
        { text: "Objections can't be tokenized", whyWrong: "Irrelevant." },
        { text: "Acceptance is never explicit", whyWrong: "It often is ('theek hai, process karo')." },
        { text: "Classifiers can't read Hinglish", whyWrong: "The failure is structural, not linguistic." },
      ],
      hint: "Where is the decisive evidence?",
      explanation: "Per-utterance decisions can't see resolution; structure-aware models (or whole-call LLMs) must weigh the final stance.",
    },
  ],
  challenge: {
    id: "dlg-ch-1",
    kind: "label",
    exType: "applied",
    difficulty: "Advanced",
    concept: "segmentation",
    prompt: "Assign each turn of call c08 to its segment.",
    labels: ["Opening", "Discovery", "Qualification", "Offer", "Objection handling", "Closing"],
    passThreshold: 0.66,
    items: [
      { speaker: "Agent", text: "sir aapka pre approved lone hai 3 lakh ka", answer: "Offer" },
      { speaker: "Customer", text: "emi kitna aayega", answer: "Offer" },
      { speaker: "Agent", text: "sir 3 saal ke liye approx 10 hazaar per month", answer: "Offer" },
      { speaker: "Customer", text: "to much hai yaar. and the ... the", answer: "Objection handling" },
      { speaker: "Agent", text: "sir tenure badha sakte hai 5 saal", answer: "Objection handling" },
      { speaker: "Customer", text: "haan fir theek hai 5 saal kar do. process kya hai", answer: "Closing" },
    ],
    hint: "An outbound offer call can start directly at the Offer segment.",
    explanation: "Segments follow function, not position: this call opens with an offer, moves into objection handling, and closes with acceptance.",
  },
  related: ["speaker-attribution", "grounding", "text-classification"],
  terms: ["dialogue-act", "adjacency-pair", "turn-taking", "segmentation", "topic-shift"],
};
