import type { Lesson } from "../../types";

export const ner: Lesson = {
  slug: "ner",
  module: "nlp",
  order: 7,
  title: "Named Entity Recognition",
  tagline: "Finding amounts, rates, tenures, banks and names in messy speech — and scoring it honestly.",
  difficulty: "Intermediate",
  minutes: 35,
  stages: ["ner"],
  why: `Structured fields drive decisions: the amount sets the product tier, the rate shows whether the agent quoted correctly, the competitor bank is market intelligence. **[[NER|ner]]** turns noisy speech into those fields.

In transcripts, entities hide behind Hinglish numbers (“pachas lakh”), misspellings (“home lon”), shorthand (“50 L”) and distractors (the *competitor's* rate is not the *offered* rate). And “did we find the entity?” has several defensible answers depending on how you score **[[span|entity-span]]** boundaries.`,
  concepts: [
    {
      title: "Entities as typed spans",
      intuition: `An entity is a stretch of text plus a type: \`5 lakh\` → AMOUNT, \`10.5 percent\` → RATE, \`5 years\` → TENURE. The hard part isn't the type — it's agreeing on exactly which words are included (“around 5 lakh” or “5 lakh”?).`,
      technical: `NER is usually framed as token classification with **[[BIO tags|bio-tagging]]** (B-AMOUNT, I-AMOUNT, O) or as span classification over candidate spans. Approaches: rules + **[[gazetteers|gazetteer]]** (precise, brittle), CRF/BiLSTM-CRF, fine-tuned transformers (token classification heads), and LLM extraction with structured output. Span annotation guidelines must define boundaries: include/exclude qualifiers ("around"), units ("lakh"), currency words.`,
      example: `“Sir I need a **personal loan**[LOAN] of **5 lakh**[AMOUNT] at around **10.5 percent**[RATE] for **5 years**[TENURE].”`,
    },
    {
      title: "Scoring: strict vs partial matching",
      intuition: `If the reference says “10.5 percent” and you tagged “around 10.5 percent”, did you get it right? **Strict** matching says no (and counts it as one false positive AND one false negative). **Partial** matching gives credit for overlap with the right type. Which one to use depends on what the downstream code needs.`,
      technical: `Span-level P/R/F1: TP = predicted spans matching a gold span. Strict: identical (start, end, type). Partial/overlap: overlapping with the same type (variants like SemEval's 'type', 'partial', 'exact' schemes). Report both; strict penalizes boundary disagreement that may be irrelevant to a downstream value parser, partial can hide boundary errors that matter (e.g., missing "lakh" changes the value by 100,000×).`,
      example: `Gold AMOUNT “pachas lakh”; predicted “pachas” as AMOUNT. Partial match: credited. Strict: FP + FN. Downstream parser: “pachas” = 50 ≠ 5,000,000 — the partial credit was misleading.`,
    },
  ],
  questions: {
    what: "Detecting spans of text that refer to entities of predefined types (amount, rate, tenure, bank, person, location, product…) and labelling their type.",
    why: "Downstream logic needs structured values, not free text.",
    problem: "It converts unstructured speech into fields that can be validated, aggregated and acted on.",
    how: "Rules/gazetteers, sequence-labelling models (BIO tagging), or LLMs with schemas; followed by value normalization (“five lac” → 500000).",
    onRealData: "Hinglish and word numbers (pachas lakh, teen saal), shorthand (50 L, PL), misspellings (home lon), competitor mentions, ranges (5-6 lakh), and entities split across turns.",
    whatCanGoWrong: "Boundary disagreements, extracting the competitor's rate as the offered rate, missing noisy variants, attributing an agent-mentioned amount to the customer, unit errors (lakh vs crore).",
    howToEvaluate: "Span-level precision/recall/F1 under strict and partial matching, per entity type, plus field-level accuracy after normalization (the value actually used).",
    whenToUse: "Whenever decisions depend on specific values or names.",
    whenNotToUse: "Don't tag everything that looks like an entity — define which entities matter for the decision and who said them.",
    downstream: "Entity errors propagate to eligibility, pricing checks, lead scoring and analytics; unit errors are especially costly.",
  },
  lab: {
    id: "ner",
    title: "NER annotation playground",
    intro: "Label entities by selecting spans, compare with the reference under strict and partial matching, and contrast with a transparent rule-based baseline.",
    modes: ["precomputed", "computed"],
  },
  realWorld: {
    text: `A rate-compliance check extracted every RATE entity in a call and compared the maximum against the approved rate card. It flagged 14% of calls as mis-selling. Almost all were false alarms: customers mentioning competitor rates (“Metro Finance 10.5 pe de raha hai”) or agents quoting ranges. The fix added *role* (who said it) and *relation* (whose offer) to the extraction: \`offered_rate\` must be spoken by the agent and refer to our product.`,
  },
  mistakes: [
    { mistake: "Extracting entities without attributing them", why: "A rate mentioned by the customer about a competitor is not the offered rate.", fix: "Extract (entity, speaker, relation) — e.g., offered_rate vs competitor_rate." },
    { mistake: "Reporting only partial-match F1", why: "It hides boundary errors that change values (missing 'lakh').", fix: "Report strict and partial, plus field-level accuracy after normalization." },
    { mistake: "Relying only on regexes", why: "Rules miss noisy variants ('home lon', 'apna business').", fix: "Use rules for high-precision patterns and a model for recall; measure both." },
  ],
  decision: {
    question: "Rules, a trained NER model, or an LLM extractor?",
    useWhen: ["Rules: formats are regular (numbers + units, known bank names)", "Trained model: high volume, stable schema, labelled data available", "LLM: few labels, many entity types, need for relations/roles"],
    avoidWhen: ["Rules alone on noisy ASR text", "LLM extraction without value validation and grounding checks"],
    tradeoffs: [
      { a: "Precision (rules)", b: "Recall (models)", note: "Combine: rules as high-precision layer, model for coverage." },
      { a: "Strict", b: "Partial scoring", note: "Choose the one aligned with how values are consumed downstream." },
    ],
  },
  exercises: [
    {
      id: "ner-ex-1",
      kind: "multi",
      exType: "applied",
      difficulty: "Beginner",
      concept: "ner-spans",
      prompt: "In “Metro Finance wale 11 percent de rahe the, aap kitna doge?”, which are entities? (Select all)",
      options: [
        { text: "Metro Finance → BANK", correct: true },
        { text: "11 percent → RATE", correct: true },
        { text: "aap → PERSON", whyWrong: "A pronoun is not a named entity." },
        { text: "kitna → AMOUNT", whyWrong: "'how much' is a question word, not an amount." },
      ],
      hint: "Named entities have specific referents.",
      explanation: "Metro Finance (BANK) and 11 percent (RATE). Note it's a competitor's rate — relation matters downstream.",
    },
    {
      id: "ner-ex-2",
      kind: "numeric",
      exType: "applied",
      difficulty: "Intermediate",
      concept: "ner-evaluation",
      prompt: "Gold has 4 entities. Your model predicts 5 spans: 2 exact matches, 1 with correct type but wrong boundary, 2 spurious. What is **strict** precision?",
      answer: 0.4,
      tolerance: 0.001,
      hint: "Strict TP counts only exact (start, end, type) matches.",
      explanation: "Strict TP = 2; predicted = 5 → precision = 2/5 = **0.4**. (Strict recall = 2/4 = 0.5; partial precision = 3/5 = 0.6.)",
    },
    {
      id: "ner-ex-3",
      kind: "json",
      exType: "engineering",
      difficulty: "Intermediate",
      concept: "ner-spans",
      prompt: "Extract entities from: “mujhe home lon chahiye pachas lakh ka, next month tak”. Return JSON with `loan_type` (\"home\"), `amount` (integer ₹), and `timeframe` (string, verbatim span).",
      starter: `{
  "loan_type": "",
  "amount": 0,
  "timeframe": ""
}`,
      checks: [
        { label: "loan_type is 'home'", test: (v) => v?.loan_type === "home" },
        { label: "amount = 5000000 (pachas lakh)", test: (v) => v?.amount === 5000000 },
        { label: "timeframe is the verbatim span 'next month'", test: (v) => typeof v?.timeframe === "string" && v.timeframe.toLowerCase().includes("next month") },
      ],
      hint: "pachas = 50; 1 lakh = 100,000.",
      modelAnswer: `{
  "loan_type": "home",
  "amount": 5000000,
  "timeframe": "next month"
}`,
      explanation: "Recognize the misspelled 'home lon', normalize the Hindi number word, and keep the timeframe verbatim.",
    },
    {
      id: "ner-ex-4",
      kind: "mcq",
      exType: "conceptual",
      difficulty: "Intermediate",
      concept: "ner-evaluation",
      prompt: "Why report BOTH strict and partial span matching for NER?",
      options: [
        { text: "Strict exposes boundary errors that can change values; partial shows whether the entity was found at all", correct: true },
        { text: "Partial matching is always the more correct one", whyWrong: "It can hide value-changing boundary errors (e.g., dropping 'lakh')." },
        { text: "Strict matching ignores entity types", whyWrong: "Strict requires exact boundaries AND the right type." },
        { text: "They always give the same number", whyWrong: "They differ whenever boundaries disagree." },
      ],
      hint: "What does each one forgive?",
      explanation: "Together they separate 'found it' from 'found exactly the right span'; field-level value accuracy then tells you what downstream code actually receives.",
    },
  ],
  quiz: [
    {
      id: "ner-q-1",
      kind: "mcq",
      difficulty: "Beginner",
      concept: "ner-spans",
      prompt: "In BIO tagging, 'personal loan' as a LOAN entity is tagged…",
      options: [
        { text: "personal/B-LOAN loan/I-LOAN", correct: true },
        { text: "personal/I-LOAN loan/B-LOAN", whyWrong: "B marks the beginning." },
        { text: "personal/O loan/B-LOAN", whyWrong: "'personal' is part of the entity." },
        { text: "personal/B-LOAN loan/B-LOAN", whyWrong: "That would be two separate entities." },
      ],
      hint: "B = beginning, I = inside.",
      explanation: "The first token gets B-, continuation tokens get I-.",
    },
    {
      id: "ner-q-2",
      kind: "mcq",
      difficulty: "Intermediate",
      concept: "ner-evaluation",
      prompt: "Under strict matching, predicting 'around 10.5 percent' when gold is '10.5 percent' counts as…",
      options: [
        { text: "One false positive and one false negative", correct: true },
        { text: "A true positive", whyWrong: "Boundaries differ." },
        { text: "Only a false negative", whyWrong: "The prediction is also an unmatched span." },
        { text: "Ignored", whyWrong: "It's counted." },
      ],
      hint: "An unmatched prediction AND an unmatched gold span.",
      explanation: "Strict matching double-penalizes boundary errors — one reason to also report partial matching.",
    },
    {
      id: "ner-q-3",
      kind: "mcq",
      difficulty: "Intermediate",
      concept: "ner-evaluation",
      prompt: "Rule-based NER on noisy transcripts typically shows…",
      options: [
        { text: "High precision, lower recall", correct: true },
        { text: "High recall, low precision", whyWrong: "Rules match specific patterns precisely and miss variants." },
        { text: "Perfect scores", whyWrong: "Noise breaks rules." },
        { text: "Identical precision and recall always", whyWrong: "No." },
      ],
      hint: "What happens to 'home lon' under a 'home loan' regex?",
      explanation: "Rules fire rarely but accurately; noisy variants are missed.",
    },
    {
      id: "ner-q-4",
      kind: "mcq",
      difficulty: "Advanced",
      concept: "ner-spans",
      prompt: "“mujhe 10.5 pe mil raha hai Metro Finance mein” — why is extracting 10.5 as `offered_rate` wrong?",
      options: [
        { text: "It's a competitor's rate reported by the customer, not the rate offered in this call", correct: true },
        { text: "10.5 isn't a valid rate", whyWrong: "It is a rate; the relation is wrong." },
        { text: "Rates must include the word 'percent'", whyWrong: "Surface form isn't the issue." },
        { text: "The customer can't mention rates", whyWrong: "They can; attribution matters." },
      ],
      hint: "Whose rate is it?",
      explanation: "Entity + role + relation: the customer mentions a competitor's rate.",
    },
    {
      id: "ner-q-5",
      kind: "mcq",
      difficulty: "Intermediate",
      concept: "ner-evaluation",
      prompt: "Which evaluation best reflects whether extracted amounts are usable downstream?",
      options: [
        { text: "Field-level accuracy of the normalized value (e.g., 5000000)", correct: true },
        { text: "Token-level accuracy of O tags", whyWrong: "Dominated by non-entity tokens." },
        { text: "Number of entities found", whyWrong: "Quantity, not correctness." },
        { text: "Partial-match F1 only", whyWrong: "Partial credit can hide value-changing errors." },
      ],
      hint: "What does the downstream code consume?",
      explanation: "Measure what's consumed: the normalized value.",
    },
  ],
  challenge: {
    id: "ner-ch-1",
    kind: "text",
    exType: "engineering",
    difficulty: "Expert",
    concept: "ner-spans",
    prompt: "Design the extraction output for a rate-compliance check that must not flag customers quoting competitor rates. What fields, and how do you evaluate it?",
    rubric: [
      { idea: "Separate offered_rate from competitor/customer-mentioned rates", keywords: ["offered_rate", "competitor", "separate", "relation", "whose"] },
      { idea: "Record speaker of each mention", keywords: ["speaker", "agent", "who said", "role"] },
      { idea: "Keep evidence span / turn index", keywords: ["evidence", "span", "turn", "quote"] },
      { idea: "Evaluate per field with labelled calls including competitor mentions", keywords: ["label", "per field", "gold", "competitor mentions", "slice", "precision"] },
    ],
    minIdeas: 3,
    hint: "Entity + role + relation + evidence.",
    modelAnswer:
      "Output {offered_rate: number|null, offered_rate_evidence: {turn, quote}, competitor_rates: [{bank, rate, turn}], rate_mentions: [{value, speaker, turn}]}. offered_rate must be an agent turn about our product. Evaluate field-level precision/recall of offered_rate on labelled calls, with a dedicated slice of calls containing competitor mentions, and track the false-alarm rate of the compliance flag.",
    explanation: "Relations and roles turn raw entities into decision-grade fields.",
  },
  related: ["text-normalization", "structured-output", "grounding"],
  terms: ["ner", "entity-span", "bio-tagging", "gazetteer"],
};
