import type { Lesson } from "../../types";

export const phoneticMatching: Lesson = {
  slug: "phonetic-matching",
  module: "nlp",
  order: 4,
  title: "Phonetic Matching",
  tagline: "Rahul, Raahul, Rahool: matching by sound when spelling can't be trusted.",
  difficulty: "Beginner",
  minutes: 20,
  stages: ["normalization", "ner"],
  why: `Indian names and Hindi words have no single Latin spelling, and ASR spells what it hears. The same customer can appear as *Mohammed*, *Mohammad*, *Muhammad* and *Mohd* across calls, CRM entries and transcripts. **[[Phonetic matching|phonetic-matching]]** encodes words by approximate pronunciation so spelling variants collide on the same key.

It's also dangerously generous: *loan* and *lone* sound identical, and *Kumar* / *Kumari* share a code but name different people. Knowing where phonetic keys help — and measuring where they hurt — is the point of this lesson.`,
  concepts: [
    {
      title: "Soundex: a 4-character sound code",
      intuition: `Keep the first letter, turn similar-sounding consonants into the same digit, drop vowels, and cut to four characters. Names that sound alike end up with the same code: Rahul, Raahul and Rahool all become **R400**.`,
      technical: `American **[[Soundex|soundex]]**: keep the first letter; map B F P V→1, C G J K Q S X Z→2, D T→3, L→4, M N→5, R→6; vowels (and Y) are dropped but separate repeated codes; H and W are ignored and do *not* separate codes; collapse adjacent identical codes; pad/truncate to 4. E.g. Ashcraft → A261, Tymczak → T522, Pfister → P236.`,
      example: `Lakshmi → L250 and Laxmi → L250 (K, S and X all map to 2 and collapse). Chaudhary, Choudhury and Chowdhury → C360. Use the lab's step-by-step view to trace any word.`,
    },
    {
      title: "Metaphone: pronunciation rules instead of letter classes",
      intuition: `Soundex only groups letters. **Metaphone** applies English pronunciation rules: PH sounds like F, a K before N is silent, TH is its own sound. It's more accurate for English words — but its rules are English rules, so Hindi names are only approximately handled.`,
      technical: `Original **[[Metaphone|metaphone]]** (Philips, 1990) transforms the string with ~20 context-sensitive rules (initial KN/GN/PN/WR drop the first letter, CH→X, PH→F, TH→0, silent GH, soft C/G before E/I/Y, vowels kept only initially) and produces a variable-length key. Double Metaphone later added alternate encodings for non-English origins.`,
      example: `Phone and Fone → FN. Knight → NT. Mohammed and Muhammad → MHMT. Kumar → KMR and Kumari → KMR: a false merge that would join two different customers' records.`,
    },
  ],
  questions: {
    what: "Encoding words into keys based on approximate pronunciation and comparing keys instead of spellings.",
    why: "Transliteration and ASR produce spelling variation that edit distance measures poorly (Chaudhary vs Chowdhury differ by several edits).",
    problem: "It clusters spelling variants of the same spoken word, especially names, for deduplication, lookup and entity linking.",
    how: "Rule-based encoders (Soundex, Metaphone, Double Metaphone, NYSIIS) map letters/letter-groups to sound classes and simplify.",
    onRealData: "Customer names in CRM vs transcripts (Srinivas / Shrinivas / Sreenivas), agent names, city names. Devanagari text can't be encoded at all without transliteration.",
    whatCanGoWrong: "Homophones merge (loan / lone), related but different names merge (Kumar / Kumari), names that sound similar but differ in the first letter split (Sharma / Verma is correct to split, but Kh/K spellings may split wrongly), and non-Latin scripts return nothing.",
    howToEvaluate: "Build labelled pairs (same entity / different entity) and compute pairwise precision and recall of 'same key ⇒ same entity', as the lab does.",
    whenToUse: "Name matching and deduplication, candidate generation before a stricter check, spoken-word matching after ASR.",
    whenNotToUse: "As the sole decision rule for merging customer records; for general vocabulary (homophones); for non-Latin scripts without transliteration.",
    downstream: "Wrong merges attach one customer's history to another; missed merges create duplicate leads and inflate counts.",
  },
  lab: {
    id: "phonetic-matching",
    title: "Phonetic encoder lab",
    intro: "Encode any list of words with Soundex and Metaphone, trace Soundex step by step, then measure pairwise precision/recall of phonetic keys versus edit distance on a labelled set of Indian name variants.",
    modes: ["computed"],
  },
  realWorld: {
    text: `A lender deduplicated leads by Soundex(first name) + Soundex(last name) + city. Duplicate leads fell 40% — and complaints rose: *Kumar Sharma* and *Kumari Sharma* (siblings) in the same city were merged, and one of them stopped receiving callbacks. The fix was to use phonetic keys only for **candidate generation**, then require an exact phone-number match or human confirmation before merging.`,
  },
  mistakes: [
    { mistake: "Treating equal phonetic codes as proof of identity", why: "Codes are coarse by design; different people/words collide.", fix: "Use phonetic keys to generate candidates; confirm with other evidence (phone, DOB, context)." },
    { mistake: "Applying English phonetic rules to Hindi names blindly", why: "Metaphone's rules model English orthography.", fix: "Measure on your own name pairs; consider transliteration-aware normalization." },
    { mistake: "Using phonetic matching on general vocabulary", why: "Homophones (loan/lone, EMI/Amy) create false matches.", fix: "Restrict to name/entity fields." },
  ],
  decision: {
    question: "Phonetic keys, edit distance, or both?",
    useWhen: ["Matching names with transliteration variants", "Generating candidates for deduplication or entity linking", "Short spoken words where spelling is unreliable"],
    avoidWhen: ["The decision is irreversible (merging records) without confirmation", "Input is not in Latin script", "You're matching general words with many homophones"],
    tradeoffs: [
      { a: "Phonetic keys", b: "Edit distance", note: "Phonetic keys catch long spelling variants (Chowdhury); edit distance catches small typos but penalizes long variants." },
      { a: "Recall", b: "Precision", note: "Coarser keys merge more variants and more strangers. Combine signals and measure." },
    ],
  },
  exercises: [
    {
      id: "pho-ex-1",
      kind: "mcq",
      exType: "applied",
      difficulty: "Beginner",
      concept: "phonetic-codes",
      prompt: "What is the Soundex code of **Rahul**?",
      options: [
        { text: "R400", correct: true },
        { text: "R540", whyWrong: "H and vowels are dropped; only L (4) contributes a digit." },
        { text: "R040", whyWrong: "Codes don't contain internal zeros; zeros are only padding." },
        { text: "RHL0", whyWrong: "That mixes Metaphone letters with Soundex padding." },
      ],
      hint: "Keep R, drop vowels and H, L → 4, pad with zeros.",
      explanation: "R + (a dropped, h ignored, u dropped) + L→4 → R4, padded → **R400**.",
    },
    {
      id: "pho-ex-2",
      kind: "mcq",
      exType: "conceptual",
      difficulty: "Intermediate",
      concept: "phonetic-limits",
      prompt: "Soundex gives Kumar and Kumari the same code. What kind of error would it cause in customer deduplication?",
      options: [
        { text: "False positive: two different people merged", correct: true },
        { text: "False negative: one person split into two", whyWrong: "That happens when variants get different codes." },
        { text: "No error — they're the same name", whyWrong: "Kumar and Kumari are different names (often different people)." },
        { text: "A parsing error", whyWrong: "The encoder works as designed." },
      ],
      hint: "Same code ⇒ predicted 'same'. Are they?",
      explanation: "The encoder predicts 'same entity' for different people — a false positive merge.",
    },
    {
      id: "pho-ex-3",
      kind: "text",
      exType: "engineering",
      difficulty: "Intermediate",
      concept: "phonetic-limits",
      prompt: "Design a customer-name matching step for linking transcript mentions to CRM records. How do you use phonetic codes safely?",
      rubric: [
        { idea: "Use phonetic codes for candidate generation / blocking", keywords: ["candidate", "blocking", "shortlist", "first pass", "retrieve"] },
        { idea: "Confirm with additional evidence (phone, account, context)", keywords: ["phone", "account", "dob", "confirm", "second signal", "context", "exact"] },
        { idea: "Measure precision/recall on labelled pairs", keywords: ["precision", "recall", "label", "pairs", "measure"] },
        { idea: "Handle non-Latin scripts via transliteration", keywords: ["translit", "devanagari", "script"] },
      ],
      minIdeas: 2,
      hint: "Phonetic keys are generous. What should follow them?",
      modelAnswer:
        "Transliterate to Latin if needed, compute phonetic keys to shortlist candidate CRM records (blocking), then confirm with a second signal — phone number, account ID, or context such as product and city — before linking. Evaluate pairwise precision/recall on labelled pairs and route ambiguous cases to human review.",
      explanation: "Phonetic keys are excellent for recall-oriented candidate generation, poor as a final decision.",
    },
  ],
  quiz: [
    {
      id: "pho-q-1",
      kind: "mcq",
      difficulty: "Beginner",
      concept: "phonetic-codes",
      prompt: "In Soundex, which letters map to the digit 2?",
      options: [
        { text: "C G J K Q S X Z", correct: true },
        { text: "B F P V", whyWrong: "Those map to 1." },
        { text: "M N", whyWrong: "Those map to 5." },
        { text: "Vowels", whyWrong: "Vowels are dropped." },
      ],
      hint: "Think of 'hard' consonants and sibilants.",
      explanation: "C G J K Q S X Z → 2.",
    },
    {
      id: "pho-q-2",
      kind: "mcq",
      difficulty: "Intermediate",
      concept: "phonetic-limits",
      prompt: "Why does `loan` vs `lone` illustrate a risk of phonetic matching on transcripts?",
      options: [
        { text: "Homophones get the same key, so different words match", correct: true },
        { text: "They get different keys", whyWrong: "They sound the same and get the same key." },
        { text: "Phonetic encoders can't handle 4-letter words", whyWrong: "Length is fine." },
        { text: "Soundex requires capital letters", whyWrong: "Encoders uppercase internally." },
      ],
      hint: "Say both words out loud.",
      explanation: "Homophones collide by design — fine for ASR-noise recovery, dangerous when the words mean different things.",
    },
    {
      id: "pho-q-3",
      kind: "mcq",
      difficulty: "Intermediate",
      concept: "phonetic-codes",
      prompt: "What does Metaphone do that Soundex doesn't?",
      options: [
        { text: "Applies context-sensitive pronunciation rules (PH→F, silent K in KN, TH sound)", correct: true },
        { text: "Handles Devanagari script", whyWrong: "Neither handles non-Latin script." },
        { text: "Uses machine learning", whyWrong: "Both are rule-based." },
        { text: "Always produces exactly 4 characters", whyWrong: "That's Soundex; Metaphone keys vary in length." },
      ],
      hint: "Rules about letter combinations.",
      explanation: "Metaphone models English pronunciation contexts rather than fixed letter classes.",
    },
    {
      id: "pho-q-4",
      kind: "mcq",
      difficulty: "Intermediate",
      concept: "phonetic-limits",
      prompt: "Soundex on the Devanagari string `राहुल` returns…",
      options: [
        { text: "Nothing useful — it only processes Latin letters", correct: true },
        { text: "R400", whyWrong: "It never sees Latin letters in this input." },
        { text: "The same code as 'Rahul' automatically", whyWrong: "Only after transliteration." },
        { text: "An error in all implementations", whyWrong: "Most return an empty key." },
      ],
      hint: "What alphabet are the rules defined on?",
      explanation: "Transliterate to Latin first, or use a script-aware scheme.",
    },
    {
      id: "pho-q-5",
      kind: "multi",
      difficulty: "Advanced",
      concept: "phonetic-limits",
      prompt: "In the lab's pairwise evaluation, which statements are true? (Select all)",
      options: [
        { text: "Phonetic keys have high recall on transliteration variants", correct: true },
        { text: "Edit distance ≤ 1 misses long variants like Chaudhary/Chowdhury", correct: true },
        { text: "Combining signals changes the precision/recall trade-off", correct: true },
        { text: "Phonetic keys have perfect precision", whyWrong: "Kumar/Kumari shows they don't." },
      ],
      hint: "Run the lab and read the FP/FN columns.",
      explanation: "Each method errs differently; measure, then combine.",
    },
  ],
  challenge: {
    id: "pho-ch-1",
    kind: "numeric",
    exType: "applied",
    difficulty: "Advanced",
    concept: "phonetic-codes",
    prompt: "Soundex for **Tymczak** is T522. How many letters in 'Tymczak' after the first letter contribute a digit to the final code? (Hint: count only letters that produce a new digit.)",
    answer: 3,
    tolerance: 0,
    hint: "T is kept. y dropped. m→5. c→2. z→2 (same as previous, collapsed). a dropped. k→2 (after a vowel, so kept).",
    explanation: "m (5), c (2), and k (2, kept because the vowel 'a' separates it from the previous 2) → T522. z collapses into c because they are adjacent with the same code.",
  },
  related: ["fuzzy-matching", "ner", "speaker-attribution"],
  terms: ["soundex", "metaphone", "phonetic-matching", "levenshtein"],
};
