import type { Lesson } from "../../types";

export const speakerAttribution: Lesson = {
  slug: "speaker-attribution",
  module: "nlp",
  order: 6,
  title: "Speaker Attribution from Text",
  tagline: "Who said it matters more than what was said: one wrong speaker label can fabricate a customer's intent.",
  difficulty: "Intermediate",
  minutes: 30,
  stages: ["speaker", "evidence", "decision"],
  why: `Agents ask leading questions (“so you want 5 lakh, right?”), paraphrase and pitch. If **[[diarization]]** or role assignment attributes those lines to the customer, every downstream stage sees customer “evidence” that the customer never said — and produces a confident, wrong, business-relevant output.

This is the textbook case of **[[error propagation]]**: a small upstream error that no downstream component can detect on its own. Speaker attribution therefore needs its own evaluation and, often, text-based checks on top of audio diarization.`,
  concepts: [
    {
      title: "Linguistic clues to speaker role",
      intuition: `Agents and customers talk differently. Agents greet, introduce the company, ask qualification questions, use scripted phrases and say “sir”. Customers state needs (“mujhe… chahiye”), give short answers (“haan”, “five lakh”), object and ask about costs and documents.

No single clue is reliable — customers say “sir” too — but together they give a strong signal.`,
      technical: `Role attribution can be framed as sequence labelling over turns with features: interrogatives and question marks, second-person address (“aap… ho?”), company self-reference, domain-script n-grams (“pre-approved”, “processing fee”), first-person need expressions, turn length, and position/alternation constraints (speakers usually alternate). A logistic model over such features is a transparent baseline; LLMs can do this with the whole call as context. Audio diarization gives "speaker 1/2" clusters; text cues map clusters to roles and flag inconsistent turns.`,
      example: `“Okay, how much are you looking for?” → strong agent cues (qualification question). “Five lakh.” → short answer → customer. “Yes sir.” → ambiguous in isolation; resolved only by its adjacency pair.`,
    },
    {
      title: "Error propagation",
      intuition: `Speaker error → wrong evidence attribution → wrong intent classification → wrong business decision. Each stage did its job correctly *given its input*, so none of them raises an alarm. The final output looks confident and well-evidenced.`,
      technical: `In a pipeline y = f_n(…f_2(f_1(x))), downstream components are validated on the distribution of correct upstream outputs. A shifted input (agent text labelled customer) moves them off-distribution; errors don't average out, they compound. Detection requires (a) per-stage evaluation, (b) cross-checks (e.g., evidence quotes must be customer turns *and* not interrogatives), and (c) confidence penalties when evidence comes only from a leading question.`,
      example: `In the lab, flip one speaker label in a 5-turn call: “sir aapko 5 lakh ka personal loan chahiye, right?” becomes customer evidence, the intent jumps from *Insufficient Evidence* to *Interested (0.90)*, and the decision becomes “HOT LEAD — application pre-filled for 5 lakh”.`,
    },
  ],
  questions: {
    what: "Assigning each utterance to a speaker role (Agent or Customer), from audio diarization and/or textual cues.",
    why: "All customer-centric outputs (intent, objections, consent) depend on knowing which words were the customer's.",
    problem: "It prevents agent speech — questions, paraphrases, pitches — from being treated as customer evidence.",
    how: "Diarization clusters voices; role mapping uses text cues (questions, scripts, self-reference, need expressions) and alternation constraints; LLMs can check consistency.",
    onRealData: "Mono telephony recordings, overlapping speech and short back-channels cause swapped or merged turns; Hinglish politeness ('sir', 'ji') appears on both sides.",
    whatCanGoWrong: "Leading questions attributed to customers; merged turns mixing both speakers; systematic swaps for a whole call; back-channels assigned to the wrong side.",
    howToEvaluate: "Turn-level role accuracy on a labelled sample, and — more importantly — accuracy on evidence-bearing turns, sliced by audio quality and agent.",
    whenToUse: "Always verify speaker roles for any customer-intent, consent or complaint extraction.",
    whenNotToUse: "Tasks that describe the whole conversation neutrally (topic tagging) are less sensitive — but still check.",
    downstream: "Wrong attribution fabricates evidence, inflates 'interested' rates, misattributes consent in compliance, and corrupts agent-performance metrics.",
  },
  lab: {
    id: "speaker-attribution",
    title: "Who said it? + error-propagation simulator",
    intro: "Assign speakers to unlabelled lines and see the linguistic cues behind each decision. Then flip speaker labels in a call and watch the error cascade through evidence, intent and the business decision.",
    modes: ["precomputed", "simulated"],
  },
  realWorld: {
    text: `A lender's “interested lead” rate jumped 11% after a telephony vendor switch. Nobody changed the model. Per-stage evaluation found that the new mono recordings degraded diarization: agent confirmations (“so you'll take 5 lakh, right?”) were attributed to customers in 8% of calls. Sales wasted thousands of callbacks. The fix combined stereo recording, a text-based role checker that flags customer-attributed interrogatives, and a rule that leading questions alone can't support “interested”.`,
    transcript: [
      { speaker: "Customer", text: "sir you want 5 lakh loan right" },
      { speaker: "Customer", text: "haan... matlab dekhte hai" },
      { speaker: "Agent", text: "great sir main application start kar deta hu" },
      { speaker: "Customer", text: "nahi abhi mat karo, pehle wife se baat karni hai" },
    ],
  },
  mistakes: [
    { mistake: "Trusting diarization labels as ground truth", why: "Diarization errors are common on mono, noisy, overlapping audio.", fix: "Evaluate diarization on a sample and add text-based consistency checks." },
    { mistake: "Accepting agent questions as customer evidence", why: "A leading question + 'hmm' is not a customer statement of intent.", fix: "Require evidence from customer turns that are not interrogatives; lower confidence when evidence is only a 'yes' to a leading question." },
    { mistake: "Only measuring end-to-end accuracy", why: "It can't reveal that speaker errors caused the intent errors.", fix: "Measure speaker attribution separately and on evidence-bearing turns." },
  ],
  decision: {
    question: "How much effort should go into speaker attribution?",
    useWhen: ["Outputs concern the customer's own statements (intent, consent, complaints)", "Recordings are mono or noisy", "Decisions are costly (sales routing, compliance)"],
    avoidWhen: ["You have reliable stereo channels per party (then verify, but don't over-engineer)"],
    tradeoffs: [
      { a: "Audio diarization", b: "Text-based roles", note: "Audio separates voices; text maps voices to roles and catches role swaps. Use both." },
      { a: "Strict evidence rules", b: "Recall", note: "Rejecting leading-question evidence lowers false leads but may miss customers who only said 'yes'. Measure both." },
    ],
  },
  exercises: [
    {
      id: "spk-ex-1",
      kind: "label",
      exType: "applied",
      difficulty: "Beginner",
      concept: "speaker-cues",
      prompt: "Speaker labels are missing. Who most likely said each line?",
      labels: ["Agent", "Customer"],
      passThreshold: 0.8,
      items: [
        { text: "Yes sir.", answer: "Customer", note: "Short acknowledgement; customers also say 'sir'." },
        { text: "Okay, how much are you looking for?", answer: "Agent" },
        { text: "Five lakh.", answer: "Customer" },
        { text: "Are you salaried?", answer: "Agent" },
        { text: "Yes.", answer: "Customer" },
      ],
      hint: "Who asks qualification questions, and who answers them?",
      explanation: "Qualification questions are agent-side; short answers and amounts are customer-side. 'Yes sir.' is the hardest: its role comes from the adjacent question.",
    },
    {
      id: "spk-ex-2",
      kind: "mcq",
      exType: "conceptual",
      difficulty: "Intermediate",
      concept: "error-propagation",
      prompt: "Why can't a well-built intent classifier detect that the agent's line was attributed to the customer?",
      options: [
        { text: "It only sees its input; given 'Customer: I want 5 lakh', predicting Interested is correct behaviour", correct: true },
        { text: "Classifiers can't read speaker labels", whyWrong: "They can; the label itself is wrong." },
        { text: "Because the model temperature is too high", whyWrong: "Sampling is unrelated." },
        { text: "It can — classifiers always check diarization", whyWrong: "No component does this unless you design it." },
      ],
      hint: "Is the classifier wrong given what it was told?",
      explanation: "Each stage is locally correct; the error originates upstream. Only per-stage evaluation or explicit cross-checks catch it.",
    },
    {
      id: "spk-ex-3",
      kind: "text",
      exType: "engineering",
      difficulty: "Advanced",
      concept: "error-propagation",
      prompt: "Propose two safeguards that stop diarization errors from producing false 'Interested' leads.",
      rubric: [
        { idea: "Evidence must come from customer turns that are not questions / leading questions", keywords: ["not a question", "interrogative", "leading", "question mark", "customer turn"] },
        { idea: "Text-based role consistency check on diarization output", keywords: ["role check", "consistency", "classifier", "cue", "verify speaker", "text-based"] },
        { idea: "Lower confidence / route to review when evidence is weak", keywords: ["confidence", "review", "human", "flag", "needs_review"] },
        { idea: "Measure speaker attribution accuracy separately", keywords: ["measure", "evaluate", "per-stage", "accuracy", "sample"] },
      ],
      minIdeas: 2,
      hint: "One safeguard on the speaker labels, one on how evidence is used.",
      modelAnswer:
        "(1) Run a text-based role checker over diarized turns and flag turns labelled Customer that look like agent speech (qualification questions, scripted phrases, company self-reference). (2) Require intent evidence to be a customer turn that isn't an interrogative; if the only 'evidence' is a yes to a leading question, cap confidence and set needs_review. Evaluate diarization/role accuracy on evidence-bearing turns monthly.",
      explanation: "Defence in depth: fix the labels where possible, and make downstream logic robust to the errors that remain.",
    },
  ],
  quiz: [
    {
      id: "spk-q-1",
      kind: "mcq",
      difficulty: "Beginner",
      concept: "speaker-cues",
      prompt: "“main Sunrise Bank se bol rahi hu” is most likely said by…",
      options: [
        { text: "The agent (company self-reference)", correct: true },
        { text: "The customer", whyWrong: "Customers rarely introduce themselves as calling from the bank." },
        { text: "Impossible to tell", whyWrong: "Company self-reference is a strong cue." },
        { text: "A third party", whyWrong: "No." },
      ],
      hint: "'I'm speaking from Sunrise Bank'.",
      explanation: "Self-identification with the company is one of the strongest agent cues.",
    },
    {
      id: "spk-q-2",
      kind: "mcq",
      difficulty: "Intermediate",
      concept: "speaker-cues",
      prompt: "Which cue is WEAKEST for identifying the agent in Indian call centres?",
      options: [
        { text: "Use of 'sir'", correct: true },
        { text: "Asking 'aap salaried ho?'", whyWrong: "Qualification questions are strongly agent-side." },
        { text: "Mentioning 'processing fee waive'", whyWrong: "Sales-script vocabulary is agent-side." },
        { text: "'main bank se bol raha hu'", whyWrong: "Strong agent cue." },
      ],
      hint: "Which cue do both sides use?",
      explanation: "Customers commonly address agents as 'sir' too.",
    },
    {
      id: "spk-q-3",
      kind: "mcq",
      difficulty: "Intermediate",
      concept: "error-propagation",
      prompt: "The chain 'speaker error → wrong evidence → wrong intent → wrong decision' is an example of…",
      options: [
        { text: "Error propagation in a pipeline", correct: true },
        { text: "Overfitting", whyWrong: "Different concept." },
        { text: "Class imbalance", whyWrong: "No." },
        { text: "Calibration", whyWrong: "No." },
      ],
      hint: "Upstream → downstream.",
      explanation: "Upstream errors become downstream inputs.",
    },
    {
      id: "spk-q-4",
      kind: "mcq",
      difficulty: "Intermediate",
      concept: "error-propagation",
      prompt: "The best metric to monitor for speaker attribution in an intent pipeline is…",
      options: [
        { text: "Role accuracy on evidence-bearing turns", correct: true },
        { text: "Average turn length", whyWrong: "Not a quality metric." },
        { text: "Number of turns per call", whyWrong: "Descriptive, not quality." },
        { text: "End-to-end intent accuracy", whyWrong: "Doesn't isolate speaker errors." },
      ],
      hint: "Which turns actually affect decisions?",
      explanation: "Errors on evidence turns are the ones that change outputs; weight your evaluation there.",
    },
    {
      id: "spk-q-5",
      kind: "multi",
      difficulty: "Advanced",
      concept: "speaker-cues",
      prompt: "Which features help a text-based role classifier? (Select all)",
      options: [
        { text: "Question marks / interrogative words", correct: true },
        { text: "Company self-reference", correct: true },
        { text: "First-person need expressions (mujhe… chahiye)", correct: true },
        { text: "The call's date", whyWrong: "Unrelated to role." },
      ],
      hint: "Three are linguistic role cues.",
      explanation: "Questions and self-reference point to the agent; stated needs point to the customer.",
    },
  ],
  challenge: {
    id: "spk-ch-1",
    kind: "evidence",
    exType: "applied",
    difficulty: "Advanced",
    concept: "speaker-cues",
    transcript: [
      { speaker: "Customer", text: "sir aapko 5 lakh ka personal loan chahiye, right?" },
      { speaker: "Customer", text: "hmm" },
      { speaker: "Agent", text: "main details bhej deta hu" },
      { speaker: "Customer", text: "ok" },
    ],
    claim: "The customer requested a 5 lakh personal loan.",
    verdicts: ["Supported", "Contradicted", "Insufficient evidence"],
    correctVerdict: "Insufficient evidence",
    evidenceTurns: [1, 3],
    prompt: "The diarization labels below may be wrong. Judge the claim using what the CUSTOMER plausibly said, and select the turns that are genuinely customer evidence.",
    hint: "Turn 1 addresses someone as 'sir' and asks 'aapko… chahiye, right?' — who asks that?",
    explanation: "Turn 1 is almost certainly the agent's leading question mislabelled as Customer. The customer's real words are 'hmm' and 'ok' — back-channels that don't establish a request.",
  },
  related: ["dialogue-structure", "per-stage-evaluation", "grounding"],
  terms: ["speaker-attribution", "diarization", "error-propagation", "adjacency-pair"],
};
