import type { Lesson } from "../../types";

export const textClassification: Lesson = {
  slug: "text-classification",
  module: "nlp",
  order: 8,
  title: "Text Classification",
  tagline: "Multi-class, multi-label, hierarchical — the label structure you choose decides what you can measure.",
  difficulty: "Intermediate",
  minutes: 35,
  stages: ["classification"],
  why: `“Is this customer interested?” sounds like one question. In real calls it's several: interested in *which* product, *existing* customer or new, *needs follow-up* or not. Forcing all of that into one label list — or splitting it wrongly — creates label disagreements, uninterpretable confusion matrices and metrics that can't be compared.

The structure of your labels — **[[multi-class]]**, **[[multi-label]]** or **[[hierarchical|hierarchical-classification]]** — is an engineering decision made *before* any model is trained or prompted.`,
  concepts: [
    {
      title: "Three label structures",
      intuition: `- **Multi-class**: pick exactly one (Interested / Not Interested / Unknown).
- **Multi-label**: pick any number (Interested + Existing Customer + Needs Follow-up).
- **Hierarchical**: pick a path in a tree (Loan → Personal Loan → Interested), and back off to a parent when unsure.`,
      technical: `Multi-class: softmax over K mutually exclusive classes; metrics from a K×K confusion matrix. Multi-label: K independent binary decisions (sigmoid or K yes/no questions); metrics per label, plus example-based measures (subset accuracy, [[Hamming loss|hamming-loss]]). Hierarchical: labels form a tree/DAG with consistency constraints (child ⇒ parent); solved top-down (local classifiers per node), flat with post-hoc consistency, or globally; evaluated per level or with hierarchical precision/recall.`,
      example: `c10: “mera already PL chal raha hai, top up mil sakta hai kya… credit card ka bhi bata do” is *interested* AND an *existing customer* AND has *cross-sell interest*. Multi-class must drop two of those facts.`,
    },
    {
      title: "Why taxonomy design creates evaluation problems",
      intuition: `If labels overlap (“Interested” vs “High Intent”), two annotators can both be right and still disagree. If there's no “Unknown” label, ambiguous calls get forced into a guess. If one list mixes product, intent and status, the confusion matrix mixes apples and oranges — and no metric on it means anything.`,
      technical: `Label noise from overlapping/undefined classes caps measurable accuracy at inter-annotator agreement and biases per-class metrics. Missing abstain classes shift ambiguous mass into majority classes, inflating their false positives. Mixed dimensions violate the mutual-exclusivity assumption of multi-class metrics. Fix structure first: one dimension per field, mutually exclusive options per field, an explicit abstain value.`,
      example: `A taxonomy {Interested, Existing Customer, Not Interested, Callback, Personal Loan} as multi-class: “existing customer asking for a top-up callback” fits three labels. Annotators split 3 ways, κ drops, and every metric inherits the noise.`,
    },
  ],
  questions: {
    what: "Assigning predefined category labels to text — one label, several, or a path in a hierarchy.",
    why: "Business processes route, count and act on categories.",
    problem: "It turns each call into decisions and aggregates (conversion funnels, objection rates, compliance flags).",
    how: "Rules, classical ML (TF-IDF + logistic regression), fine-tuned transformers, or LLM prompts with constrained label sets.",
    onRealData: "Calls contain multiple products and facts, hedged language, objections that get resolved, and third parties — all of which stress single-label schemes.",
    whatCanGoWrong: "Overlapping labels, missing abstain class, mixed dimensions, labels that never occur, and choosing multi-class when facts co-occur.",
    howToEvaluate: "Multi-class: confusion matrix, per-class P/R/F1, macro-F1. Multi-label: per-label P/R, Hamming loss, subset accuracy. Hierarchical: per-level metrics. Always alongside inter-annotator agreement.",
    whenToUse: "Multi-class for one mutually exclusive dimension; multi-label for co-occurring facts in one dimension; hierarchical when categories nest and back-off is useful.",
    whenNotToUse: "Don't use one multi-class list for multiple dimensions; don't use hierarchies deeper than your data supports.",
    downstream: "Label structure fixes the output schema, the annotation guideline, the metrics, and what dashboards can show.",
  },
  lab: {
    id: "text-classification",
    title: "Label-structure designer",
    intro: "Label the same snippets as multi-class and multi-label and compare the metrics. Then design your own label structure and stress-test it on real snippets with a taxonomy linter.",
    modes: ["precomputed", "computed"],
  },
  realWorld: {
    text: `A team tracked “Interested / Not Interested / Callback / Existing customer” as one multi-class label. Inter-annotator κ was 0.41 and never improved with training. Splitting into three fields — intent {interested, not_interested, insufficient_evidence}, customer_status {new, existing}, next_action {callback, none} — raised κ to 0.78 on the same calls without changing the annotators.`,
  },
  mistakes: [
    { mistake: "Mixing dimensions in one multi-class list", why: "Items legitimately belong to several labels; annotators and models disagree arbitrarily.", fix: "One field per dimension; mutually exclusive values within each." },
    { mistake: "No abstain / insufficient-evidence label", why: "Ambiguous calls are forced into a guess, inflating majority classes.", fix: "Add an explicit abstain value with a definition." },
    { mistake: "Evaluating multi-label with accuracy", why: "Subset accuracy is harsh and accuracy is ill-defined.", fix: "Report per-label P/R/F1 and Hamming loss." },
  ],
  decision: {
    question: "Multi-class, multi-label or hierarchical?",
    useWhen: ["Multi-class: exactly one answer per call on one dimension", "Multi-label: several co-occurring facts on the same dimension (objection types)", "Hierarchical: nested categories and you need to back off when unsure"],
    avoidWhen: ["Multi-class across dimensions", "Deep hierarchies with sparse leaves", "Multi-label lists that mix dimensions — use separate fields"],
    tradeoffs: [
      { a: "Simplicity", b: "Expressiveness", note: "Multi-class is easy to evaluate; multi-label captures reality but needs more annotation and metrics." },
      { a: "Fine-grained leaves", b: "Agreement", note: "More specific labels → more disagreement; hierarchies let you report at the level you can label reliably." },
    ],
  },
  exercises: [
    {
      id: "cls-ex-1",
      kind: "mcq",
      exType: "conceptual",
      difficulty: "Beginner",
      concept: "multiclass-vs-multilabel",
      prompt: "A call can mention several objections (rate AND documentation). Objection type should be…",
      options: [
        { text: "Multi-label", correct: true },
        { text: "Multi-class", whyWrong: "Multi-class forces one objection and drops the others." },
        { text: "Binary", whyWrong: "There are several objection types." },
        { text: "Regression", whyWrong: "Categories, not a number." },
      ],
      hint: "Can more than one be true at once?",
      explanation: "Co-occurring facts within one dimension → multi-label.",
    },
    {
      id: "cls-ex-2",
      kind: "numeric",
      exType: "applied",
      difficulty: "Intermediate",
      concept: "multiclass-vs-multilabel",
      prompt: "4 labels × 5 calls = 20 label decisions. The model gets 3 decisions wrong. What is the **Hamming loss**?",
      answer: 0.15,
      tolerance: 0.001,
      hint: "Wrong decisions / total decisions.",
      explanation: "3 / 20 = **0.15**. Subset accuracy could be as low as 2/5 if those errors fall on 3 different calls.",
    },
    {
      id: "cls-ex-3",
      kind: "json",
      exType: "engineering",
      difficulty: "Intermediate",
      concept: "hierarchical-labels",
      prompt: "Design an output object for c10 (existing personal-loan customer, wants a top-up, also asks about a credit card). Use separate fields: `intent` (one of interested/not_interested/insufficient_evidence), `customer_status` (new/existing), `products_of_interest` (array).",
      starter: `{
  "intent": "",
  "customer_status": "",
  "products_of_interest": []
}`,
      checks: [
        { label: "intent = interested", test: (v) => v?.intent === "interested" },
        { label: "customer_status = existing", test: (v) => v?.customer_status === "existing" },
        { label: "products_of_interest has 2 items", test: (v) => Array.isArray(v?.products_of_interest) && v.products_of_interest.length === 2 },
        { label: "includes a top-up and a credit card", test: (v) => Array.isArray(v?.products_of_interest) && v.products_of_interest.some((p: string) => /top/i.test(p)) && v.products_of_interest.some((p: string) => /card/i.test(p)) },
      ],
      hint: "One field per dimension; a list where several values can co-occur.",
      modelAnswer: `{
  "intent": "interested",
  "customer_status": "existing",
  "products_of_interest": ["personal_loan_top_up", "credit_card"]
}`,
      explanation: "Separate fields keep each dimension mutually exclusive where it should be and multi-valued where it must be.",
    },
  ],
  quiz: [
    {
      id: "cls-q-1",
      kind: "mcq",
      difficulty: "Beginner",
      concept: "multiclass-vs-multilabel",
      prompt: "In multi-class classification each example gets…",
      options: [
        { text: "Exactly one label", correct: true },
        { text: "Zero or more labels", whyWrong: "That's multi-label." },
        { text: "A path in a tree", whyWrong: "That's hierarchical." },
        { text: "A numeric score only", whyWrong: "That's regression/scoring." },
      ],
      hint: "Mutually exclusive.",
      explanation: "Exactly one of K classes.",
    },
    {
      id: "cls-q-2",
      kind: "mcq",
      difficulty: "Intermediate",
      concept: "hierarchical-labels",
      prompt: "A key advantage of hierarchical labels is…",
      options: [
        { text: "You can back off to a parent (Loan) when the child (Personal/Home) is unclear", correct: true },
        { text: "They always increase agreement", whyWrong: "Deep leaves often reduce agreement." },
        { text: "They remove the need for guidelines", whyWrong: "They need more guidelines." },
        { text: "They make evaluation simpler", whyWrong: "Evaluation gets more complex." },
      ],
      hint: "What if the product is unclear but it's clearly a loan?",
      explanation: "Back-off gives useful partial answers instead of forced guesses.",
    },
    {
      id: "cls-q-3",
      kind: "mcq",
      difficulty: "Intermediate",
      concept: "hierarchical-labels",
      prompt: "Your label list is {Interested, Existing Customer, Not Interested, Callback}. The core design flaw is…",
      options: [
        { text: "It mixes dimensions (intent, customer status, next action) in one list", correct: true },
        { text: "It has too few labels", whyWrong: "Count isn't the issue." },
        { text: "Labels should be lowercase", whyWrong: "Cosmetic." },
        { text: "It should be binary", whyWrong: "No." },
      ],
      hint: "Can one call be Existing Customer AND Interested?",
      explanation: "Mixed dimensions break mutual exclusivity.",
    },
    {
      id: "cls-q-4",
      kind: "mcq",
      difficulty: "Intermediate",
      concept: "multiclass-vs-multilabel",
      prompt: "Subset accuracy in multi-label evaluation is…",
      options: [
        { text: "The fraction of examples where ALL labels are exactly right", correct: true },
        { text: "The fraction of correct individual label decisions", whyWrong: "That's 1 − Hamming loss." },
        { text: "Macro-F1 over labels", whyWrong: "Different metric." },
        { text: "Always higher than Hamming accuracy", whyWrong: "It's usually lower (harsher)." },
      ],
      hint: "All or nothing per example.",
      explanation: "Subset accuracy is strict; complement it with per-label metrics.",
    },
    {
      id: "cls-q-5",
      kind: "mcq",
      difficulty: "Advanced",
      concept: "hierarchical-labels",
      prompt: "Removing the 'Unknown / insufficient evidence' option from an intent label set usually…",
      options: [
        { text: "Pushes ambiguous calls into other classes, inflating their false positives and lowering agreement", correct: true },
        { text: "Improves precision of every class", whyWrong: "Forced guesses add false positives." },
        { text: "Has no effect on metrics", whyWrong: "It changes the label distribution." },
        { text: "Makes annotation faster and more accurate", whyWrong: "Faster maybe; less accurate." },
      ],
      hint: "Where do the ambiguous calls go?",
      explanation: "Abstain classes absorb genuine ambiguity so it doesn't contaminate other classes.",
    },
  ],
  challenge: {
    id: "cls-ch-1",
    kind: "text",
    exType: "engineering",
    difficulty: "Advanced",
    concept: "hierarchical-labels",
    prompt: "Product asks for one dashboard number: '% of calls interested in any loan'. Your schema has product (personal/home/vehicle/unspecified) and intent per product. Explain how you'd compute and evaluate it, and what could make it misleading.",
    rubric: [
      { idea: "Aggregate across products: interested in at least one product", keywords: ["any", "at least one", "aggregate", "or across", "union"] },
      { idea: "Handle insufficient evidence explicitly (exclude/report separately)", keywords: ["insufficient", "abstain", "separately", "exclude", "denominator"] },
      { idea: "Evaluate the aggregate against gold labels (per-level metrics)", keywords: ["gold", "evaluate", "precision", "recall", "per level", "parent level"] },
      { idea: "Misleading due to class imbalance / calibration / sampling", keywords: ["imbalance", "prevalence", "sample", "calibrat", "confidence interval", "bias"] },
    ],
    minIdeas: 3,
    hint: "Parent-level metric from child-level predictions.",
    modelAnswer:
      "Compute a parent-level label: interested_any = any(intent[p] == interested). Report insufficient-evidence calls separately (don't silently count them as not interested). Evaluate the parent-level label against gold (precision/recall at the parent level) because child-level errors (wrong product) may not matter here. Report with a confidence interval; beware that precision at low prevalence is fragile and that model/labeler bias toward 'interested' inflates the number.",
    explanation: "Hierarchies let you report reliably at the level the business needs — if you evaluate at that level.",
  },
  related: ["taxonomy-design", "macro-micro", "annotation-guidelines"],
  terms: ["multi-class", "multi-label", "hierarchical-classification", "hamming-loss", "taxonomy"],
};
