import type { GlossaryTerm, ModuleId } from "./types";

const g = (
  id: string,
  term: string,
  module: ModuleId,
  lesson: string | undefined,
  simple: string,
  technical: string,
  example: string,
  why: string,
  related: string[],
  aliases: string[] = [],
): GlossaryTerm => ({ id, term, module, lesson, simple, technical, example, why, related, aliases });

export const GLOSSARY: GlossaryTerm[] = [
  /* ------------------------------ NLP ------------------------------ */
  g("token", "Token", "nlp", "tokenization",
    "The unit of text a language model actually reads — often a word piece, not a whole word.",
    "An integer-indexed entry in a model's vocabulary produced by a tokenizer (e.g. byte-level BPE). Models consume and emit sequences of token IDs; pricing and context limits are measured in tokens.",
    "'personal' may be one token while 'persnal' may be split into 'pers' + 'nal'.",
    "Cost, latency, context limits and chunking are all computed in tokens, not words or characters.",
    ["tokenization", "bpe", "context-window", "token-id"], ["tokens"]),
  g("tokenization", "Tokenization", "nlp", "tokenization",
    "Splitting text into the pieces a model understands.",
    "A deterministic mapping from a string to a sequence of vocabulary IDs, typically via pre-tokenization (regex splitting) followed by a subword algorithm such as BPE or Unigram LM.",
    "'mujhe loan chahiye' → ['m','ujhe',' loan',' ch','ahi','ye'] (exact splits depend on the tokenizer).",
    "Different scripts and spellings produce very different token counts for the same meaning.",
    ["token", "bpe", "sentencepiece", "subword"], ["tokenizer"]),
  g("bpe", "Byte-Pair Encoding (BPE)", "nlp", "tokenization",
    "A tokenizer that learns to glue together the most frequent character pairs into bigger chunks.",
    "Starting from bytes/characters, BPE iteratively merges the most frequent adjacent pair in a training corpus, producing a merge table. Encoding applies merges in learned priority order. Byte-level BPE guarantees any string is representable.",
    "If ' loan' appears often in training data it becomes a single token; a rare misspelling like ' lon' may not.",
    "Explains why frequent English words are cheap and rare spellings, scripts or code-mixed text are more expensive.",
    ["tokenization", "subword", "vocabulary", "sentencepiece"], ["byte pair encoding"]),
  g("sentencepiece", "SentencePiece", "nlp", "tokenization",
    "A tokenizer toolkit that treats text as a raw stream (including spaces), so it works for any language.",
    "A language-independent subword tokenizer library implementing BPE and Unigram-LM; it encodes whitespace as a visible symbol (▁) and does not require pre-splitting on spaces.",
    "'▁personal▁loan' — the ▁ marks where a space was.",
    "Common in multilingual models; it handles scripts without spaces and code-mixed text more uniformly.",
    ["bpe", "tokenization", "subword"]),
  g("subword", "Subword tokenization", "nlp", "tokenization",
    "Breaking rare words into smaller known pieces instead of treating them as unknown.",
    "A vocabulary strategy between character-level and word-level models: frequent strings become single units, rare strings decompose into multiple units, eliminating out-of-vocabulary failures.",
    "'chahiye' → 'ch' + 'ahi' + 'ye'.",
    "Noisy and code-mixed text never breaks the tokenizer, but it costs more tokens.",
    ["bpe", "token"]),
  g("vocabulary", "Vocabulary", "nlp", "tokenization",
    "The fixed list of tokens a model knows.",
    "The finite set of symbols (typically 32k–200k+) the tokenizer can output; each entry maps to an embedding row in the model.",
    "o200k_base has roughly 200,000 entries.",
    "Larger vocabularies usually compress multilingual text better, at the cost of larger embedding tables.",
    ["token", "token-id"]),
  g("token-id", "Token ID", "nlp", "tokenization",
    "The number that represents a token inside the model.",
    "An integer index into the vocabulary/embedding matrix. The model never sees characters — only these IDs.",
    "' loan' → 11057 (the actual ID depends on the tokenizer).",
    "Debugging tokenization means looking at IDs and their decoded strings.",
    ["token", "vocabulary"]),
  g("chunking", "Chunking", "nlp", "tokenization",
    "Splitting a long text into smaller pieces that fit the model's context.",
    "Partitioning a document into segments under a token budget, ideally on semantic boundaries (turns, segments) with overlap, then processing each chunk and aggregating results.",
    "A 30,000-token call split into 11,000-token chunks at turn boundaries with 2 turns of overlap.",
    "Naive fixed-size chunks cut numbers and question→answer pairs apart, losing evidence.",
    ["context-window", "token", "segmentation"], ["chunk", "chunks"]),
  g("context-window", "Context window", "llm", "context-engineering",
    "How much text (in tokens) the model can consider at once.",
    "The maximum number of tokens (input + output) a model can attend over in a single forward pass sequence. Content beyond it must be truncated, summarized or retrieved.",
    "A 128k-token window holds roughly a few hundred pages of English, fewer of Hinglish.",
    "Determines whether a long call plus rulebook fits in one request and what it costs.",
    ["token", "lost-in-the-middle", "prompt-bloat"], ["context length", "context limit"]),
  g("normalization", "Text normalization", "nlp", "text-normalization",
    "Cleaning text into a more consistent form before processing.",
    "Deterministic or learned transformations — case folding, Unicode normalization, punctuation/whitespace canonicalization, spelling correction, transliteration, abbreviation expansion — that map surface variants to a canonical representation.",
    "'personal lon ke liye' → 'personal loan ke liye'.",
    "Improves matching and consistency, but every step can destroy information (negation, emphasis, casing).",
    ["romanization", "levenshtein"], ["text normalization"]),
  g("romanization", "Romanization", "nlp", "text-normalization",
    "Writing a language like Hindi using the Latin alphabet.",
    "Transliteration of a non-Latin script into Latin characters. Informal romanization has no standard spelling, producing many variants for one word.",
    "'chahiye', 'chaiye', 'chahie', 'chahye' all mean 'need'.",
    "Exact-match rules and keyword lists silently miss variants.",
    ["normalization", "hinglish", "code-switching"], ["transliteration", "romanized hindi"]),
  g("hinglish", "Hinglish", "nlp", "text-normalization",
    "Mixed Hindi and English speech, usually written in Latin script.",
    "A code-mixed variety combining Hindi grammar/lexicon with English lexicon, common in Indian call-centre conversations.",
    "'mujhe personal loan chahiye but rate kam hona chahiye'.",
    "Many NLP tools assume one language per utterance and fail on mixed input.",
    ["code-switching", "romanization"]),
  g("code-switching", "Code-switching", "nlp", "text-normalization",
    "Switching between languages within a conversation or even a sentence.",
    "Alternation between two or more languages at inter- or intra-sentential boundaries.",
    "'EMI kitna aayega for 3 years?'",
    "Language ID, spelling correction and NER must handle mixed spans.",
    ["hinglish", "romanization"], ["code-mixing"]),
  g("asr", "ASR / Speech-to-text", "nlp", undefined,
    "Software that converts audio into text.",
    "Automatic Speech Recognition maps acoustic signals to token sequences, typically with an encoder-decoder or CTC model. Output contains substitutions, deletions, insertions and no reliable punctuation.",
    "Audio 'loan' transcribed as 'lone'.",
    "Every downstream stage inherits ASR errors — design for them.",
    ["wer", "diarization"], ["stt", "speech to text", "speech-to-text"]),
  g("wer", "Word Error Rate (WER)", "nlp", undefined,
    "The percentage of words the transcription got wrong.",
    "WER = (S + D + I) / N, where S, D, I are substitutions, deletions, insertions from a minimum edit alignment and N is the number of reference words.",
    "Reference 'personal loan chahiye', hypothesis 'personal lone chahiye' → WER = 1/3.",
    "Transcript quality is a key slicing dimension in error analysis.",
    ["asr", "levenshtein"]),
  g("diarization", "Speaker diarization", "nlp", "speaker-attribution",
    "Figuring out 'who spoke when' in audio.",
    "Segmenting audio into speaker-homogeneous regions and clustering them into speaker identities; distinct from assigning roles (Agent vs Customer).",
    "Diarization says 'Speaker 1' and 'Speaker 2'; role attribution decides Speaker 1 is the Agent.",
    "Diarization errors swap who said what — a major source of wrong evidence.",
    ["speaker-attribution", "asr"]),
  g("levenshtein", "Levenshtein distance", "nlp", "fuzzy-matching",
    "The minimum number of single-character edits to turn one string into another.",
    "Edit distance with unit-cost insertions, deletions and substitutions, computed by dynamic programming in O(mn).",
    "'persnal' → 'personal' = 1 (insert 'o').",
    "The basic building block of fuzzy matching against product names, names and keywords.",
    ["edit-distance", "jaro-winkler", "fuzzy-matching"], ["levenshtein"]),
  g("edit-distance", "Edit distance", "nlp", "fuzzy-matching",
    "A family of measures counting how many edits separate two strings.",
    "Generic term for string metrics defined by minimum-cost edit sequences (Levenshtein, Damerau-Levenshtein with transpositions, Hamming for equal-length strings).",
    "Damerau counts 'lnoa' → 'loan' as 1 transposition; Levenshtein counts 2.",
    "Choice of edit operations changes what counts as 'close'.",
    ["levenshtein"]),
  g("fuzzy-matching", "Fuzzy matching", "nlp", "fuzzy-matching",
    "Matching strings that are similar but not identical.",
    "Approximate string matching using a similarity function and a decision threshold, optionally over a candidate dictionary.",
    "Matching 'persnal lon' to the catalogue entry 'personal loan'.",
    "Thresholds trade false positives against false negatives.",
    ["levenshtein", "jaro-winkler", "jaccard"]),
  g("jaro-winkler", "Jaro-Winkler similarity", "nlp", "fuzzy-matching",
    "A similarity score that rewards strings sharing the same beginning.",
    "Jaro similarity counts matching characters within a window and transpositions; Winkler adds a bonus l·p·(1−J) for a common prefix of length l ≤ 4 (p usually 0.1).",
    "'Rahul' vs 'Rahool' scores high because they share 'Rah'.",
    "Good for short names; can over-match short strings with a shared prefix.",
    ["levenshtein", "fuzzy-matching"]),
  g("jaccard", "Jaccard similarity", "nlp", "fuzzy-matching",
    "Overlap between two sets divided by their union.",
    "J(A,B) = |A∩B| / |A∪B|, applied to token sets or character n-gram sets.",
    "Tokens {personal, loan} vs {loan, personal} → 1.0 (word order ignored).",
    "Robust to reordering, blind to order-dependent meaning.",
    ["n-gram", "fuzzy-matching"]),
  g("n-gram", "n-gram", "nlp", "fuzzy-matching",
    "A sequence of n consecutive characters or words.",
    "Contiguous subsequences of length n used as features for similarity, language modelling and indexing.",
    "Character bigrams of 'loan': lo, oa, an.",
    "Character n-grams make similarity robust to small spelling errors.",
    ["jaccard", "tf-idf"]),
  g("soundex", "Soundex", "nlp", "phonetic-matching",
    "An old algorithm that gives similar-sounding names the same code.",
    "Keeps the first letter, maps consonants to 6 digit classes (B/F/P/V=1, C/G/J/K/Q/S/X/Z=2, D/T=3, L=4, M/N=5, R=6), drops vowels/H/W/Y, collapses adjacent duplicates, pads to 4 characters.",
    "Rahul, Raahul, Rahool → R400.",
    "Useful for name matching despite spelling variation; designed for English surnames.",
    ["metaphone", "phonetic-matching"]),
  g("metaphone", "Metaphone", "nlp", "phonetic-matching",
    "A smarter phonetic code that uses English pronunciation rules.",
    "A rule-based phonetic encoding (Lawrence Philips, 1990) handling digraphs (PH→F, TH→0, SH→X), silent letters and context-dependent consonants.",
    "'Phone' and 'Fone' → FN.",
    "More accurate than Soundex for English; still English-centric for Indian names.",
    ["soundex", "phonetic-matching"]),
  g("phonetic-matching", "Phonetic matching", "nlp", "phonetic-matching",
    "Matching words by how they sound instead of how they are spelled.",
    "Encoding strings into phonetic keys and comparing keys (or key similarity) instead of surface forms.",
    "'Mohammed' and 'Muhammad' share Soundex M530.",
    "Handles transliteration variation in names; produces false matches for different words that sound alike.",
    ["soundex", "metaphone"]),
  g("dialogue-act", "Dialogue act", "nlp", "dialogue-structure",
    "What an utterance is doing in the conversation — asking, answering, refusing…",
    "A functional label for an utterance's communicative intent (e.g., DAMSL/ISO 24617-2 categories such as question, inform, request, commit).",
    "'kitne ka chahiye?' → Question; 'around five lac' → Answer.",
    "Lets you find where evidence lives (answers to qualification questions) and segment calls.",
    ["adjacency-pair", "turn-taking", "segmentation"], ["dialogue acts", "speech act"]),
  g("adjacency-pair", "Adjacency pair", "nlp", "dialogue-structure",
    "Two utterances that naturally go together, like a question and its answer.",
    "A conversation-analysis unit of two turns by different speakers where the first part makes a specific second part relevant (question→answer, offer→accept/decline, greeting→greeting).",
    "Agent: 'aap salaried ho?' → Customer: 'haan'.",
    "A bare 'haan' is only interpretable through the question it answers.",
    ["dialogue-act", "turn-taking"], ["adjacency pairs"]),
  g("turn-taking", "Turn-taking", "nlp", "dialogue-structure",
    "How speakers alternate in a conversation.",
    "The organization of speaker changes, including overlaps, interruptions and back-channels ('haan', 'ji').",
    "Back-channel 'hmm' from the customer while the agent explains is not agreement.",
    "Transcripts merge or split turns incorrectly; downstream logic must be robust to it.",
    ["adjacency-pair", "diarization"]),
  g("segmentation", "Conversation segmentation", "nlp", "dialogue-structure",
    "Splitting a call into phases like opening, discovery, offer, objection and closing.",
    "Partitioning a dialogue into contiguous topical or functional segments, e.g., via dialogue-act patterns or topic-shift detection.",
    "Opening → Discovery → Qualification → Offer → Objection handling → Closing.",
    "Lets you look for intent evidence in the right segment and measure agent behaviour per phase.",
    ["dialogue-act", "topic-shift"]),
  g("topic-shift", "Topic shift", "nlp", "dialogue-structure",
    "The moment the conversation moves to a new subject.",
    "A boundary where the discourse topic changes, often signalled by markers ('aur', 'by the way', 'ek aur baat').",
    "'ok aur credit card ka bhi bata do' shifts from top-up to credit card.",
    "A single call can contain multiple intents for multiple products.",
    ["segmentation"]),
  g("speaker-attribution", "Speaker attribution", "nlp", "speaker-attribution",
    "Deciding which person (agent or customer) said each line.",
    "Assigning speaker identities or roles to utterances, from audio diarization and/or text cues (questions, politeness markers, domain phrases).",
    "'aap salaried ho?' is almost certainly the agent.",
    "If the agent's words are attributed to the customer, the system fabricates customer intent.",
    ["diarization", "error-propagation"]),
  g("error-propagation", "Error propagation", "nlp", "speaker-attribution",
    "An early mistake causing more mistakes later in the pipeline.",
    "In a sequential pipeline, the output distribution of each stage is conditioned on upstream outputs; upstream errors shift downstream inputs outside what downstream stages were validated on.",
    "Wrong speaker → wrong evidence → wrong intent → wrong sales action.",
    "End-to-end accuracy hides where the failure originated.",
    ["per-stage-evaluation", "pipeline"]),
  g("ner", "Named Entity Recognition (NER)", "nlp", "ner",
    "Finding and labelling things like amounts, names, dates and products in text.",
    "Sequence labelling that identifies entity spans and assigns types, typically framed as token classification with BIO tags or as span/LLM extraction.",
    "'5 lakh' → AMOUNT; '10.5 percent' → RATE.",
    "Entities fill structured fields used for routing and decisions.",
    ["entity-span", "bio-tagging", "gazetteer"], ["named entity recognition"]),
  g("entity-span", "Entity span", "nlp", "ner",
    "The exact stretch of text that makes up an entity.",
    "A contiguous character or token range [start, end) with a type label; evaluation compares predicted and gold spans by exact or partial overlap.",
    "Is the amount '5 lakh' or 'around 5 lakh'? Guidelines must decide.",
    "Boundary disagreements lower strict-match scores even when the extraction is useful.",
    ["ner", "bio-tagging"]),
  g("bio-tagging", "BIO tagging", "nlp", "ner",
    "A labelling scheme marking the Beginning, Inside and Outside of entities.",
    "Each token gets B-TYPE (first token of an entity), I-TYPE (continuation) or O (outside), converting span extraction into token classification.",
    "'personal/B-LOAN loan/I-LOAN of/O 5/B-AMOUNT lakh/I-AMOUNT'.",
    "How classic NER models and many annotation tools represent spans.",
    ["ner", "entity-span"], ["iob"]),
  g("gazetteer", "Gazetteer", "nlp", "ner",
    "A lookup list of known entity names.",
    "A curated dictionary of entity surface forms (bank names, cities, products) used for rule-based matching or as model features.",
    "A list of all bank names you partner with.",
    "Cheap, precise, but misses unseen variants unless combined with fuzzy matching.",
    ["ner", "fuzzy-matching"]),
  g("multi-class", "Multi-class classification", "nlp", "text-classification",
    "Choose exactly one label from several.",
    "Each instance receives exactly one label from K > 2 mutually exclusive classes; typically softmax output.",
    "Interested / Not interested / Insufficient evidence.",
    "Forces mutual exclusivity — wrong when labels can co-occur.",
    ["multi-label", "hierarchical-classification"], ["multiclass"]),
  g("multi-label", "Multi-label classification", "nlp", "text-classification",
    "Each example can have any number of labels at once.",
    "Each instance receives a subset of labels; usually modelled as K independent binary decisions (sigmoid outputs) and evaluated with per-label or example-based metrics.",
    "{Interested, Existing customer, Needs follow-up}.",
    "Needed when a call contains several facts at once; evaluation is more complex.",
    ["multi-class", "hamming-loss"], ["multilabel"]),
  g("hamming-loss", "Hamming loss", "eval", "text-classification",
    "Fraction of individual label decisions that were wrong in multi-label classification.",
    "Mean over instances and labels of the XOR between predicted and gold binary label vectors.",
    "3 labels × 2 examples, 1 wrong decision → 1/6.",
    "Gives partial credit where subset accuracy gives none.",
    ["multi-label"]),
  g("hierarchical-classification", "Hierarchical classification", "nlp", "text-classification",
    "Labels arranged in a tree, from general to specific.",
    "Classification over a label hierarchy (tree/DAG) where predictions must be consistent with ancestor relations; can be solved top-down, flat with constraints, or globally.",
    "Loan → Personal Loan → Interested.",
    "Lets you back off to a parent label when evidence for the child is weak.",
    ["taxonomy", "multi-class"], ["hierarchical labels"]),

  /* ------------------------------ LLM ------------------------------ */
  g("system-prompt", "System prompt", "llm", "prompt-engineering",
    "Standing instructions that set the model's role and rules for the whole conversation.",
    "A privileged message placed before user turns that conditions all subsequent generation; often holds role, policy, output format and constraints.",
    "'You are an auditor of loan-sales calls. Only use evidence spoken by the customer.'",
    "Stable instructions belong here — and form a cacheable prefix.",
    ["few-shot", "prompt-caching"], ["system instruction"]),
  g("zero-shot", "Zero-shot prompting", "llm", "prompt-engineering",
    "Asking the model to do a task with instructions only, no examples.",
    "Task specification purely via natural-language instructions without in-context demonstrations.",
    "'Classify the customer's intent as interested, not_interested or insufficient_evidence.'",
    "Fast to write; weaker on ambiguous boundaries and custom label definitions.",
    ["few-shot", "in-context-learning"], ["zero shot"]),
  g("few-shot", "Few-shot prompting", "llm", "prompt-engineering",
    "Showing the model a few worked examples inside the prompt.",
    "Including k input→output demonstrations in context so the model infers the mapping (in-context learning). Example choice, order and label balance affect results.",
    "Two labelled transcripts: one 'interested', one 'insufficient_evidence'.",
    "Great for teaching boundaries — and for accidentally teaching biases (label imbalance, surface cues).",
    ["zero-shot", "in-context-learning"], ["few shot", "k-shot"]),
  g("in-context-learning", "In-context learning", "llm", "prompt-engineering",
    "The model picking up a task from examples in the prompt, without retraining.",
    "Conditioning a pretrained model on demonstrations in its input so that its predictions adapt to the task; no gradient updates occur.",
    "After three Hinglish examples the model handles 'chahiye' correctly.",
    "Cheaper and faster to iterate than fine-tuning.",
    ["few-shot"], ["icl"]),
  g("structured-output", "Structured output", "llm", "structured-output",
    "Making the model return machine-readable data like JSON.",
    "Constraining or instructing generation to follow a schema (JSON Schema, function/tool signatures), optionally enforced by constrained decoding and always validated after generation.",
    "{\"intent\": \"interested\", \"amount\": 500000}",
    "Downstream code needs reliable fields, types and enums.",
    ["json-schema", "constrained-decoding"], ["json output"]),
  g("json-schema", "JSON Schema", "llm", "structured-output",
    "A formal description of what valid JSON must look like.",
    "A vocabulary (draft 2020-12 etc.) for declaring types, required properties, enums, ranges and additionalProperties that validators can check.",
    "\"intent\": {\"enum\": [\"interested\", \"not_interested\", \"insufficient_evidence\"]}",
    "Turns 'the model usually returns the right shape' into a checkable contract.",
    ["structured-output", "constrained-decoding"]),
  g("constrained-decoding", "Constrained decoding", "llm", "structured-output",
    "Only letting the model pick tokens that keep the output valid.",
    "At each decoding step, logits for tokens that would violate a grammar/schema are masked to −∞, guaranteeing syntactically valid output (e.g., grammar-constrained or JSON-mode generation).",
    "After '\"intent\": \"' only tokens that can continue one of the enum values are allowed.",
    "Guarantees format, not truth — a valid enum can still be the wrong label.",
    ["json-schema", "structured-output"], ["constrained generation", "grammar-constrained decoding"]),
  g("context-engineering", "Context engineering", "llm", "context-engineering",
    "Deciding exactly what goes into the model's context, in what order.",
    "The design of the full input — instructions, rules, examples, retrieved evidence, conversation state — under token, cost and attention constraints.",
    "Putting the rulebook first (cacheable), the transcript next and the question last.",
    "The same model performs very differently depending on what it's shown.",
    ["context-window", "lost-in-the-middle", "prompt-bloat"]),
  g("lost-in-the-middle", "Lost in the middle", "llm", "context-engineering",
    "Models often use information at the start or end of a long prompt better than in the middle.",
    "An empirically observed U-shaped retrieval accuracy curve over position in long contexts (Liu et al., 2023). Magnitude varies by model and has decreased in newer models, but position effects remain worth measuring.",
    "The key 'nahi chahiye' buried at turn 60 of 120 is more likely to be missed.",
    "Place critical instructions and evidence deliberately; measure on your own model.",
    ["context-window", "context-rot"]),
  g("context-rot", "Context rot", "llm", "context-engineering",
    "Quality degrading as the context gets longer and noisier.",
    "Informal term for performance decline with increasing input length and irrelevant content, even well within the nominal context window.",
    "Adding 30 unrelated policy pages makes the intent label less reliable.",
    "More context is not free — it can hurt accuracy.",
    ["lost-in-the-middle", "prompt-bloat"]),
  g("prompt-bloat", "Prompt bloat", "llm", "context-engineering",
    "Prompts growing with rules and examples until they are expensive and confusing.",
    "Accretion of instructions, redundant examples and irrelevant context over iterations, increasing cost/latency and often introducing contradictory rules.",
    "A 12,000-token rulebook where 90% is irrelevant to intent classification.",
    "Every token is paid for on every call.",
    ["context-rot", "prompt-caching"]),
  g("rag", "Retrieval-Augmented Generation (RAG)", "llm", "rag-agents",
    "Looking up relevant documents and adding them to the prompt before the model answers.",
    "A pattern where a retriever (lexical, dense or hybrid) selects passages from an external corpus and injects them into the context for grounded generation.",
    "Retrieving the current rate sheet to check whether the agent quoted the correct rate.",
    "Only needed when the answer depends on knowledge not already in the input.",
    ["agent", "semantic-search", "embedding"], ["retrieval augmented generation"]),
  g("agent", "Agent", "llm", "rag-agents",
    "An LLM system that decides its own next steps and calls tools in a loop.",
    "A control loop where a model selects actions (tool calls), observes results and iterates until a goal or stop condition; non-deterministic control flow.",
    "An LLM that searches a CRM, schedules a callback and writes notes.",
    "Powerful but harder to test, cost-bound and audit than a fixed pipeline.",
    ["rag", "pipeline"], ["agents", "agentic"]),
  g("grounding", "Grounding", "llm", "grounding",
    "Making sure the model's answers are based on the provided source text.",
    "Constraining generation so each claim is attributable to supplied evidence, usually by requiring citations/spans and verifying them.",
    "Intent 'interested' must cite a customer utterance that shows interest.",
    "Ungrounded outputs cannot be audited or trusted.",
    ["faithfulness", "evidence-span", "entailment"]),
  g("faithfulness", "Faithfulness", "llm", "grounding",
    "Whether an output accurately reflects the source, without adding or distorting.",
    "The degree to which generated content is entailed by the input context; distinct from factuality with respect to the world.",
    "Summary says 'customer wants 5 lakh' but the customer never gave an amount → unfaithful.",
    "The core property you verify in transcript analysis.",
    ["grounding", "hallucination"]),
  g("evidence-span", "Evidence span", "llm", "grounding",
    "The exact quote from the transcript that supports an answer.",
    "A contiguous substring (or turn range) of the source cited as justification for a claim; verifiable by string matching and entailment.",
    "\"main kal tak apply kar dunga\" supports intent=interested.",
    "Makes outputs auditable and lets reviewers check the model quickly.",
    ["grounding", "entailment"], ["evidence"]),
  g("entailment", "Entailment", "llm", "grounding",
    "When one statement logically follows from another.",
    "In natural language inference (NLI), a premise entails a hypothesis if a typical reader would infer the hypothesis is true given the premise; alternatives are contradiction and neutral (insufficient evidence).",
    "'I will apply tomorrow' entails 'the customer intends to apply'.",
    "Separates 'supported' from 'not mentioned' from 'contradicted'.",
    ["nli", "grounding", "insufficient-evidence"]),
  g("nli", "Natural Language Inference (NLI)", "llm", "grounding",
    "Deciding if a claim is supported, contradicted, or neither, given a text.",
    "A three-way classification task (entailment / contradiction / neutral) over premise–hypothesis pairs, often used to verify generated claims.",
    "Premise: 'I might consider it'. Hypothesis: 'Customer will apply'. → neutral.",
    "A reusable verification step in extraction pipelines.",
    ["entailment"]),
  g("insufficient-evidence", "Insufficient evidence", "eval", "grounding",
    "The honest label for 'the transcript doesn't tell us'.",
    "An explicit abstention class used when neither the positive nor negative label is entailed by the evidence.",
    "'Maybe someday' for purchase intent.",
    "Without it, annotators and models are forced to guess, which destroys label quality.",
    ["entailment", "annotation-guideline"]),
  g("hallucination", "Hallucination", "llm", "hallucination",
    "When a model states something not supported by its input or by reality.",
    "Generated content that is unfaithful to the source (intrinsic: contradicts it; extrinsic: adds unverifiable information) or factually wrong.",
    "Output says 'rate agreed: 11%' when no rate was discussed.",
    "Silent, fluent, confident — so it must be detected with verification, not intuition.",
    ["faithfulness", "grounding"], ["hallucinations"]),
  g("llm-as-judge", "LLM-as-a-judge", "llm", "llm-judge",
    "Using an LLM to grade other outputs.",
    "Prompting a model to score or compare candidate outputs against a rubric or reference; a scalable but biased measurement instrument that must be validated against human labels.",
    "Judge compares answer A vs B for faithfulness.",
    "Cheap evaluation at scale — but not ground truth.",
    ["position-bias", "verbosity-bias", "self-preference-bias"], ["llm judge", "llm-judge"]),
  g("position-bias", "Position bias", "llm", "llm-judge",
    "A judge preferring whichever answer is shown first (or second).",
    "Systematic dependence of pairwise judgments on presentation order, detectable by swapping order and measuring inconsistency.",
    "A wins when shown first; B wins when order is swapped.",
    "Always evaluate both orders.",
    ["llm-as-judge"]),
  g("verbosity-bias", "Verbosity bias", "llm", "llm-judge",
    "A judge preferring longer answers even when they're not better.",
    "Correlation between judge scores and output length independent of quality.",
    "A padded, confident explanation beats a short correct label.",
    "Can push your system toward long, costly, less precise outputs.",
    ["llm-as-judge"]),
  g("self-preference-bias", "Self-preference bias", "llm", "llm-judge",
    "A model judging its own outputs (or its family's) more favourably.",
    "Judges assigning higher scores to outputs with lower perplexity under the judge model, often those generated by the same model family.",
    "Model X rates Model X's summaries higher than humans do.",
    "Use a different family as judge or validate against humans.",
    ["llm-as-judge"]),
  g("temperature", "Temperature", "llm", "sampling",
    "A knob that changes how strongly the model prefers its most likely next token.",
    "Logits are divided by T before softmax: p_i ∝ exp(z_i/T). T<1 sharpens the distribution, T>1 flattens it; T→0 approaches greedy argmax decoding.",
    "At T=0.2 the model almost always outputs 'interested'; at T=1.5 lower-ranked labels appear.",
    "Controls variability; low temperature suits classification and extraction.",
    ["top-p", "softmax", "logits"]),
  g("top-p", "Top-p (nucleus) sampling", "llm", "sampling",
    "Only sample from the smallest set of tokens that together cover p of the probability.",
    "Sort tokens by probability, keep the minimal prefix whose cumulative mass ≥ p, renormalize, sample.",
    "With p=0.9, rare tail tokens are never chosen.",
    "Cuts off unlikely nonsense while keeping some diversity.",
    ["temperature"], ["nucleus sampling", "top p"]),
  g("logits", "Logits", "llm", "sampling",
    "The raw scores the model gives each possible next token.",
    "Unnormalized real-valued outputs of the final layer; softmax converts them into a probability distribution.",
    "interested: 4.1, insufficient: 2.9, not_interested: 1.2.",
    "Temperature and constrained decoding operate on logits.",
    ["softmax", "temperature"]),
  g("softmax", "Softmax", "llm", "sampling",
    "Turns scores into probabilities that sum to 1.",
    "softmax(z)_i = exp(z_i) / Σ_j exp(z_j).",
    "Logits [2, 1, 0] → [0.67, 0.24, 0.09].",
    "Explains why temperature changes the whole distribution, not just the top token.",
    ["logits", "temperature"]),
  g("greedy-decoding", "Greedy decoding", "llm", "sampling",
    "Always pick the single most likely next token.",
    "Decoding that selects argmax at each step; equivalent to the T→0 limit. Not guaranteed to find the most likely full sequence.",
    "Always output 'interested' if it's the top token.",
    "Maximizes repeatability, but real APIs can still vary slightly between calls.",
    ["temperature"]),
  g("max-tokens", "Max tokens", "llm", "sampling",
    "The cap on how many tokens the model may generate.",
    "A hard limit on output length; generation stops (with a length stop reason) when reached, possibly mid-structure.",
    "max_tokens=20 cuts a JSON object in half.",
    "Too low → truncated/invalid JSON; too high → cost and latency risk.",
    ["structured-output"], ["max_tokens"]),
  g("moe", "Mixture-of-Experts (MoE)", "llm", "model-selection",
    "A model made of many 'expert' sub-networks where only a few run for each token.",
    "Sparse architecture where a router activates k of N expert feed-forward blocks per token; total parameters ≫ active parameters, lowering compute per token for a given capacity while keeping memory requirements high.",
    "A model with 8 experts, 2 active per token.",
    "Can offer large-model quality at lower per-token compute; memory and serving complexity remain.",
    ["dense-model", "latency"], ["mixture of experts"]),
  g("dense-model", "Dense model", "llm", "model-selection",
    "A model where every parameter is used for every token.",
    "Standard transformer where all feed-forward weights participate in each forward pass; compute scales with total parameters.",
    "A 7B dense model runs all 7B parameters per token.",
    "Simpler serving; cost and latency scale with size.",
    ["moe"]),
  g("latency", "Latency", "llm", "model-selection",
    "How long you wait for a response.",
    "End-to-end response time, typically decomposed into time-to-first-token (prefill) and per-token generation time (decode) plus network/queueing.",
    "p95 latency of 2.4s for a 300-token output.",
    "Real-time agent assist has hard latency budgets; batch analytics does not.",
    ["ttft", "throughput"]),
  g("ttft", "Time to first token (TTFT)", "llm", "caching-batching",
    "How long until the first word of the answer appears.",
    "Latency of the prefill phase (processing the prompt) plus queueing; grows with input length and is reduced by prompt caching.",
    "A 6,000-token rulebook prompt has a noticeably longer TTFT than a 500-token prompt.",
    "Dominant latency term for long-input, short-output tasks like classification.",
    ["latency", "prompt-caching"]),
  g("throughput", "Throughput", "llm", "model-selection",
    "How much work the system completes per unit time.",
    "Requests or tokens processed per second across concurrent requests; improved by batching at the cost of per-request latency.",
    "10,000 transcripts/hour.",
    "Batch workloads optimize throughput and cost, not latency.",
    ["batching", "latency"]),
  g("prompt-caching", "Prompt caching", "llm", "caching-batching",
    "Reusing the already-processed beginning of a prompt across many calls.",
    "Providers store the attention key/value state for a prompt prefix; later requests with an identical prefix skip recomputation and are billed at a discounted cached-input rate (cache writes may cost a premium; caches expire).",
    "A 5,000-token rulebook shared by 100,000 calls.",
    "Large cost and latency savings — only if the static content comes first and is byte-identical.",
    ["ttft", "batching", "system-prompt"], ["caching", "prefix caching"]),
  g("batching", "Batching", "llm", "caching-batching",
    "Processing many requests together instead of one at a time.",
    "Either server-side dynamic batching for throughput, or asynchronous batch APIs that trade latency (hours) for a discount.",
    "Submitting last night's 200k calls as one batch job.",
    "Cheaper for offline analytics; unsuitable for real-time needs.",
    ["throughput", "prompt-caching"], ["batch processing"]),
  g("pipeline", "Multi-stage pipeline", "llm", "pipeline-design",
    "Breaking a task into several steps, each handled by a component.",
    "A DAG of components (deterministic code, classifiers, LLM calls) with explicit interfaces; enables per-stage evaluation, routing and parallelism.",
    "Normalize → NER → Classify → Extract evidence → Verify.",
    "Decomposition improves debuggability but adds latency, cost and error compounding.",
    ["router", "error-propagation"], ["pipelines"]),
  g("router", "Router", "llm", "pipeline-design",
    "A step that sends each input down the appropriate path.",
    "A classifier or rule that dispatches inputs to specialized sub-pipelines (e.g., cheap model for simple cases, strong model or human for hard ones).",
    "Short, clean calls → small model; ambiguous → larger model + human review.",
    "Cuts cost while protecting quality on hard cases.",
    ["pipeline"], ["routing"]),

  /* ---------------------------- Evaluation ------------------------- */
  g("annotation-guideline", "Annotation guideline (codebook)", "eval", "annotation-guidelines",
    "The rulebook annotators follow when labelling data.",
    "A document specifying label definitions, inclusion/exclusion criteria, positive/negative/borderline examples, edge-case rulings and escalation procedures.",
    "INTERESTED: customer explicitly expresses willingness to pursue the product.",
    "Label quality — and therefore every metric — depends on it.",
    ["iaa", "gold-set", "insufficient-evidence"], ["codebook", "guidelines"]),
  g("gold-set", "Gold set", "eval", "gold-set-design",
    "A carefully labelled set of examples treated as the reference answer.",
    "A held-out, high-quality labelled dataset (often adjudicated by multiple annotators) used to measure system performance.",
    "300 calls labelled by two annotators with disagreements adjudicated.",
    "If the gold set is wrong or leaked, every conclusion is wrong.",
    ["train-dev-test", "annotation-guideline"], ["golden set", "gold standard"]),
  g("iaa", "Inter-annotator agreement (IAA)", "eval", "inter-annotator-agreement",
    "How consistently different people label the same data.",
    "Statistics quantifying agreement between annotators, ideally corrected for chance (Cohen's κ, Fleiss' κ, Krippendorff's α).",
    "Two annotators agree on 85% of calls, κ = 0.62.",
    "An upper bound on how well any model can be measured against those labels.",
    ["cohens-kappa", "fleiss-kappa", "krippendorff-alpha"], ["inter-annotator agreement", "inter annotator agreement"]),
  g("cohens-kappa", "Cohen's kappa", "eval", "inter-annotator-agreement",
    "Agreement between two annotators after removing agreement expected by chance.",
    "κ = (p_o − p_e) / (1 − p_e), where p_o is observed agreement and p_e = Σ_k p_A(k)·p_B(k) is chance agreement from each annotator's marginal label distribution.",
    "p_o = 0.90, p_e = 0.82 → κ = 0.44.",
    "Raw agreement looks great when one label dominates; κ reveals it.",
    ["iaa", "fleiss-kappa", "chance-agreement"], ["kappa", "cohen's kappa", "cohen kappa"]),
  g("chance-agreement", "Chance agreement", "eval", "inter-annotator-agreement",
    "How often annotators would agree just by guessing with their usual label frequencies.",
    "Expected agreement p_e computed from the product of annotators' marginal distributions (Cohen) or pooled distribution (Fleiss/Scott).",
    "If both label 'interested' 90% of the time, p_e ≈ 0.82.",
    "The reason raw agreement ≠ agreement beyond chance.",
    ["cohens-kappa"], ["expected agreement"]),
  g("fleiss-kappa", "Fleiss' kappa", "eval", "inter-annotator-agreement",
    "Kappa for more than two annotators.",
    "Generalizes Scott's π to a fixed number of raters per item: κ = (P̄ − P̄_e)/(1 − P̄_e), with P̄ the mean per-item pairwise agreement and P̄_e from pooled category proportions.",
    "Three annotators label 20 calls → κ = 0.51.",
    "Standard for crowdsourced labelling with multiple raters.",
    ["cohens-kappa", "krippendorff-alpha"], ["fleiss kappa"]),
  g("krippendorff-alpha", "Krippendorff's alpha", "eval", "inter-annotator-agreement",
    "A flexible agreement statistic that handles any number of annotators, missing labels and different data types.",
    "α = 1 − D_o/D_e, the ratio of observed to expected disagreement computed from a coincidence matrix, with a distance metric for nominal, ordinal, interval or ratio data.",
    "Some annotators skipped some calls; α still works.",
    "Useful when building reliable human-labelled datasets with real-world messiness.",
    ["cohens-kappa", "fleiss-kappa"], ["krippendorff alpha", "alpha"]),
  g("confusion-matrix", "Confusion matrix", "eval", "classification-metrics",
    "A table of predicted vs actual labels.",
    "A K×K count matrix where cell (i, j) counts instances with gold label i predicted as j; binary case yields TP, FP, FN, TN.",
    "TP=40, FP=10, FN=20, TN=930.",
    "Every classification metric is derived from it.",
    ["precision", "recall", "f1"]),
  g("precision", "Precision", "eval", "classification-metrics",
    "Of the items the model flagged, how many were actually right?",
    "Precision = TP / (TP + FP); the positive predictive value.",
    "Model flags 50 interested customers, 40 truly are → 0.80.",
    "High precision means sales teams don't waste calls on false leads.",
    ["recall", "f1", "confusion-matrix"], ["ppv"]),
  g("recall", "Recall", "eval", "classification-metrics",
    "Of the items that were actually positive, how many did the model find?",
    "Recall = TP / (TP + FN); sensitivity / true positive rate.",
    "60 truly interested customers, model finds 40 → 0.67.",
    "High recall means you don't miss genuine opportunities.",
    ["precision", "f1", "sensitivity"], ["sensitivity", "tpr", "true positive rate"]),
  g("f1", "F1 score", "eval", "classification-metrics",
    "A single number that balances precision and recall.",
    "Harmonic mean F1 = 2PR/(P+R); F-beta weights recall β times as much as precision.",
    "P=0.8, R=0.67 → F1 ≈ 0.73.",
    "Punishes a model that trades one metric away entirely.",
    ["precision", "recall", "macro-f1"], ["f1 score", "f-score", "f-beta"]),
  g("accuracy", "Accuracy", "eval", "classification-metrics",
    "Fraction of all predictions that were correct.",
    "(TP + TN) / N; dominated by the majority class under imbalance.",
    "Predicting 'not interested' for everyone at 1% prevalence → 99% accuracy.",
    "Misleading for rare events.",
    ["class-imbalance", "f1"]),
  g("specificity", "Specificity", "eval", "classification-metrics",
    "Of the truly negative items, how many did the model correctly leave alone?",
    "TN / (TN + FP); true negative rate; 1 − false positive rate.",
    "930 of 940 uninterested customers correctly not flagged → 0.989.",
    "Often high by default under imbalance; watch precision instead.",
    ["precision", "recall"], ["tnr"]),
  g("macro-f1", "Macro F1", "eval", "macro-micro",
    "Average the F1 of each class equally, regardless of size.",
    "Macro-F1 = (1/K) Σ_k F1_k; each class weighted equally.",
    "Rare 'Ambiguous' class counts as much as 'Interested'.",
    "Exposes failure on rare classes that micro/accuracy hide.",
    ["micro-f1", "weighted-f1"], ["macro averaging", "macro f1"]),
  g("micro-f1", "Micro F1", "eval", "macro-micro",
    "Pool all decisions together, then compute F1.",
    "Sum TP, FP, FN over classes and compute F1 from totals; for single-label multi-class this equals accuracy.",
    "Dominated by the 80% 'Interested' class.",
    "Reflects per-instance performance; hides rare-class failures.",
    ["macro-f1", "accuracy"], ["micro averaging", "micro f1"]),
  g("weighted-f1", "Weighted F1", "eval", "macro-micro",
    "Average per-class F1 weighted by how common each class is.",
    "Σ_k (n_k/N) F1_k; a compromise between macro and micro.",
    "Close to the majority class's F1 on skewed data.",
    "Often reported by default (e.g., sklearn 'weighted avg') — know what it hides.",
    ["macro-f1", "micro-f1"], ["weighted f1"]),
  g("class-imbalance", "Class imbalance", "eval", "class-imbalance",
    "When one label is much more common than others.",
    "A skewed prior over classes; affects metric interpretation, sampling, thresholding and training.",
    "1% of calls contain a compliance violation.",
    "Accuracy becomes meaningless; precision collapses at low prevalence.",
    ["base-rate", "accuracy", "stratified-sampling"], ["imbalance", "imbalanced data"]),
  g("base-rate", "Base rate (prevalence)", "eval", "class-imbalance",
    "How common the positive class is in reality.",
    "The prior probability P(y=1). Precision = sens·prev / (sens·prev + (1−spec)·(1−prev)) depends on it directly.",
    "A 95%-sensitive, 95%-specific detector at 1% prevalence has precision ≈ 16%.",
    "The same model has very different precision on different traffic.",
    ["class-imbalance", "precision"], ["prevalence", "base rate", "base rates"]),
  g("stratified-sampling", "Stratified sampling", "eval", "class-imbalance",
    "Sampling so each important group is represented in known proportions.",
    "Partition the population into strata (by label, language, agent…) and sample within each; use sampling weights to recover population estimates.",
    "Sample 50 from each of 'clean' and 'noisy' transcripts.",
    "Guarantees enough rare examples to measure them.",
    ["class-imbalance", "gold-set"], ["stratification"]),
  g("train-dev-test", "Train / dev / test split", "eval", "gold-set-design",
    "Separate data for building, tuning, and final checking.",
    "Disjoint partitions: train (fit/prompt examples), development (iterate/tune), test (one-shot final estimate). Repeated use of the test set turns it into a dev set.",
    "Few-shot examples come from train; prompt iterations use dev; test is touched once.",
    "Prevents fooling yourself with optimistic numbers.",
    ["gold-set", "prompt-overfitting"], ["data split", "dev set", "test set", "validation set"]),
  g("prompt-overfitting", "Prompt overfitting", "eval", "gold-set-design",
    "Tweaking a prompt until it scores well on your test set but not on new data.",
    "Selection bias from repeatedly evaluating prompt variants on the same labelled set; the best observed score is an upward-biased estimate of true performance (winner's curse).",
    "Visible test 0.91 → hidden test 0.83.",
    "Makes every reported number untrustworthy.",
    ["train-dev-test"], ["test set overfitting", "winner's curse"]),
  g("per-stage-evaluation", "Per-stage evaluation", "eval", "per-stage-evaluation",
    "Measuring each pipeline step separately, not just the final answer.",
    "Evaluating each component on its own gold labels (and optionally with gold upstream inputs) to attribute end-to-end errors to stages.",
    "Speaker attribution 0.93, NER 0.88, classification given gold inputs 0.91.",
    "Tells you what to fix first.",
    ["error-propagation", "error-analysis"], ["per stage evaluation", "component evaluation"]),
  g("calibration", "Calibration", "eval", "calibration",
    "Whether a model's confidence matches how often it's right.",
    "A model is calibrated if P(y = ŷ | confidence = c) = c for all c; measured with reliability diagrams, ECE and Brier score.",
    "Among predictions with confidence 0.8, about 80% are correct.",
    "Confidence thresholds for auto-approve vs human review only work if confidence is calibrated.",
    ["ece", "reliability-diagram", "brier-score"]),
  g("ece", "Expected Calibration Error (ECE)", "eval", "calibration",
    "The average gap between confidence and accuracy.",
    "ECE = Σ_b (n_b/N)·|acc(b) − conf(b)| over confidence bins b.",
    "Bin 0.9: accuracy 0.72 → gap 0.18.",
    "One-number summary of miscalibration (sensitive to binning).",
    ["calibration", "reliability-diagram"], ["expected calibration error"]),
  g("brier-score", "Brier score", "eval", "calibration",
    "Mean squared error of predicted probabilities.",
    "BS = (1/N) Σ (p_i − y_i)²; a proper scoring rule combining calibration and discrimination.",
    "Predicting 0.9 for a negative case adds 0.81.",
    "Rewards honest probabilities.",
    ["calibration"]),
  g("reliability-diagram", "Reliability diagram", "eval", "calibration",
    "A chart of predicted confidence vs actual accuracy.",
    "Plot of per-bin empirical accuracy against mean confidence; the diagonal is perfect calibration; below the diagonal = overconfident.",
    "Points under the diagonal at high confidence mean the model is overconfident.",
    "The first plot to draw before trusting confidence scores.",
    ["calibration", "ece"], ["calibration curve"]),
  g("temperature-scaling", "Temperature scaling", "eval", "calibration",
    "A simple fix that stretches or squashes confidence scores to be more honest.",
    "Post-hoc calibration dividing logits by a scalar T fitted on a validation set (minimizing NLL); preserves ranking.",
    "T=1.8 softens an overconfident classifier.",
    "Cheap recalibration when you have logits or scores.",
    ["calibration", "temperature"]),
  g("error-analysis", "Error analysis", "eval", "error-analysis",
    "Systematically studying where and why a model fails.",
    "Slicing performance by metadata, clustering failures, inspecting examples and forming/verifying root-cause hypotheses.",
    "F1 drops from 0.90 on clean to 0.62 on noisy transcripts.",
    "Turns a metric into an engineering plan.",
    ["slice", "root-cause-analysis"]),
  g("slice", "Slice", "eval", "error-analysis",
    "A subset of data defined by some attribute.",
    "A metadata-defined subpopulation (agent, language, quality, segment) over which metrics are computed separately.",
    "All noisy Hinglish outbound calls.",
    "Aggregate metrics hide slice-level failures.",
    ["error-analysis"], ["slicing", "data slice"]),
  g("root-cause-analysis", "Root-cause analysis", "eval", "error-analysis",
    "Finding the underlying reason for failures, not just where they appear.",
    "Iteratively testing hypotheses (e.g., controlling for confounders) to identify the causal factor behind a slice's degraded performance.",
    "Agent B's low F1 is really caused by Agent B handling more noisy calls.",
    "Prevents fixing the wrong thing.",
    ["error-analysis", "slice"], ["root cause"]),
  g("confidence-interval", "Confidence interval", "eval", "significance",
    "A range of plausible values for a metric given sampling noise.",
    "An interval procedure that covers the true parameter with a stated long-run frequency (e.g., 95%); for proportions, Wilson intervals are preferred over the normal approximation.",
    "Accuracy 0.84, 95% CI [0.78, 0.89] on 200 examples.",
    "Two prompts with overlapping CIs may not really differ.",
    ["statistical-significance", "bootstrap"], ["ci", "confidence intervals"]),
  g("statistical-significance", "Statistical significance", "eval", "significance",
    "Evidence that a difference is unlikely to be pure chance.",
    "A result where the p-value under a null hypothesis (e.g., no difference) falls below a pre-chosen α; says nothing about effect size or practical importance.",
    "Prompt B beats A by 3 points, p = 0.21 → not significant.",
    "Stops you shipping noise.",
    ["p-value", "confidence-interval", "mcnemar"], ["significance"]),
  g("p-value", "p-value", "eval", "significance",
    "How surprising your result would be if there were truly no difference.",
    "P(test statistic at least as extreme as observed | null hypothesis). Not the probability the null is true.",
    "p = 0.03 → such a gap would arise by chance ~3% of the time if the prompts were equal.",
    "Commonly misinterpreted; pair it with effect sizes and CIs.",
    ["statistical-significance"]),
  g("mcnemar", "McNemar's test", "eval", "significance",
    "A significance test for comparing two models on the same examples.",
    "A paired test on discordant counts b (A right, B wrong) and c (A wrong, B right): χ² = (|b−c|−1)²/(b+c), or an exact binomial test.",
    "b=12, c=25 → B is better, p ≈ 0.049.",
    "Uses the pairing, so it's more powerful than comparing two independent accuracies.",
    ["statistical-significance", "paired-test"], ["mcnemar's test"]),
  g("paired-test", "Paired test", "eval", "significance",
    "A comparison that uses the fact both systems saw the same inputs.",
    "Tests on per-item differences (McNemar, paired bootstrap, sign test) that remove between-item variance.",
    "Both prompts run on the same 300 calls.",
    "Detects real differences with far fewer examples.",
    ["mcnemar", "bootstrap"]),
  g("bootstrap", "Bootstrap", "eval", "significance",
    "Estimating uncertainty by resampling your evaluation set many times.",
    "Draw B resamples with replacement, recompute the metric on each, and take percentiles as a confidence interval.",
    "1,000 resamples of 300 calls → F1 CI [0.71, 0.80].",
    "Works for any metric, including F1 and kappa.",
    ["confidence-interval", "paired-test"]),
  g("statistical-power", "Statistical power", "eval", "significance",
    "The chance your experiment detects a real difference if one exists.",
    "1 − β: probability of rejecting the null when a specified alternative is true; increases with sample size and effect size.",
    "Detecting a 2-point accuracy gain needs thousands of examples.",
    "Small eval sets can't distinguish close prompts.",
    ["sample-size"], ["power"]),
  g("sample-size", "Sample size", "eval", "significance",
    "How many examples you evaluate on.",
    "N determines standard error (∝ 1/√N) and therefore CI width and power.",
    "Going from 100 to 400 examples halves the CI width.",
    "Plan it before running experiments.",
    ["statistical-power", "confidence-interval"]),

  /* ------------------------- Information extraction --------------------- */
  g("taxonomy", "Taxonomy", "ie", "taxonomy-design",
    "An organized set of categories, often a tree.",
    "A controlled vocabulary of labels with defined relations (parent/child, exclusivity) and definitions, used consistently for annotation and prediction.",
    "Loan → {Personal, Home, Vehicle}.",
    "Bad taxonomies create unresolvable annotation disagreements and meaningless metrics.",
    ["mece", "hierarchical-classification", "open-set"]),
  g("mece", "MECE", "ie", "taxonomy-design",
    "Mutually Exclusive, Collectively Exhaustive: categories don't overlap and together cover everything.",
    "A property of a partition: every item belongs to exactly one category. Requires an explicit 'other/insufficient' category in practice.",
    "{Interested, Not interested, Insufficient evidence} for a single dimension.",
    "Non-MECE label sets make single-label annotation ambiguous.",
    ["taxonomy"]),
  g("closed-set", "Closed-set classification", "ie", "open-closed-set",
    "Predict only from a fixed, predefined list of labels.",
    "Classification where the label space is fixed at design time; unknown categories must map to an existing label or 'other'.",
    "Objection ∈ {rate, eligibility, timing, documentation, other}.",
    "Consistent, governable, comparable over time.",
    ["open-set", "taxonomy"], ["closed set"]),
  g("open-set", "Open-set extraction", "ie", "open-closed-set",
    "Let the model describe categories in its own words and discover new ones.",
    "Generation or clustering where categories are not fixed a priori; outputs must be normalized/clustered to be aggregated.",
    "Model outputs 'wants lower EMI' and 'EMI too high' as separate reasons.",
    "Discovers unknown issues but drifts and fragments without governance.",
    ["closed-set", "clustering"], ["open set"]),
  g("embedding", "Embedding", "ie", "embeddings",
    "A list of numbers representing the meaning of a piece of text.",
    "A dense vector from a neural encoder, trained so that semantically similar inputs map to nearby points (e.g., sentence-transformers with contrastive objectives).",
    "'borrow money' and 'personal loan' have nearby vectors despite no shared words.",
    "Powers semantic search, clustering, deduplication and retrieval.",
    ["cosine-similarity", "semantic-search", "tf-idf"], ["embeddings", "sentence embedding", "vector"]),
  g("cosine-similarity", "Cosine similarity", "ie", "embeddings",
    "How closely two vectors point in the same direction.",
    "cos(u, v) = u·v / (‖u‖‖v‖), in [−1, 1]; for normalized embeddings equals the dot product.",
    "cos('EMI too high', 'rate is high') = 0.62 (model-dependent).",
    "The standard similarity for embeddings; absolute values are not comparable across models.",
    ["embedding"], ["cosine"]),
  g("semantic-search", "Semantic search", "ie", "embeddings",
    "Finding text by meaning rather than exact words.",
    "Ranking documents by embedding similarity to a query embedding, often with approximate nearest-neighbour indexes; commonly combined with lexical search (hybrid).",
    "Query 'customer can't afford the EMI' finds 'bahut mehenga hai'.",
    "Handles paraphrase and some cross-lingual variation.",
    ["embedding", "rag"]),
  g("tf-idf", "TF-IDF", "ie", "embeddings",
    "Weights words by how often they appear in a document, discounted by how common they are overall.",
    "tf(t,d)·log(N/df(t)); produces sparse lexical vectors; similarity depends on shared surface forms.",
    "'loan' is common (low idf); 'foreclosure' is rare (high idf).",
    "A strong, cheap baseline — but blind to synonyms.",
    ["embedding", "c-tf-idf"], ["tfidf"]),
  g("clustering", "Clustering", "ie", "clustering",
    "Grouping similar items without predefined labels.",
    "Unsupervised partitioning of points by similarity (k-means, hierarchical, density-based like HDBSCAN).",
    "Objection snippets grouping into rate, eligibility and timing concerns.",
    "Discovers themes to feed taxonomy design.",
    ["k-means", "hdbscan", "bertopic"]),
  g("k-means", "k-means", "ie", "clustering",
    "Splits points into k groups around k centre points.",
    "Iteratively assigns points to the nearest centroid and recomputes centroids to minimize within-cluster squared distance; requires choosing k and assumes roughly spherical clusters.",
    "k=3 on objection embeddings.",
    "Simple and fast; forces every point into a cluster (no noise label).",
    ["clustering", "silhouette"], ["kmeans"]),
  g("silhouette", "Silhouette score", "ie", "clustering",
    "How well each point fits its own cluster versus the nearest other cluster.",
    "s = (b − a) / max(a, b), where a is mean intra-cluster distance and b is mean distance to the nearest other cluster; averaged over points, in [−1, 1].",
    "k=3 gives 0.41, k=6 gives 0.22.",
    "A heuristic for choosing k — not a substitute for reading clusters.",
    ["k-means"]),
  g("bertopic", "BERTopic", "ie", "clustering",
    "A topic modelling method built from embeddings + clustering + keyword extraction.",
    "Pipeline: sentence embeddings → UMAP dimensionality reduction → HDBSCAN clustering → class-based TF-IDF to describe each cluster with keywords.",
    "Topic 3: 'rate, interest, high, kam'.",
    "Strong default for discovering themes in short texts.",
    ["umap", "hdbscan", "c-tf-idf", "clustering"]),
  g("umap", "UMAP", "ie", "clustering",
    "A method to squash high-dimensional vectors into 2–5 dimensions while keeping neighbours close.",
    "Uniform Manifold Approximation and Projection: builds a fuzzy k-NN graph and optimizes a low-dimensional layout preserving local structure.",
    "384-dim embeddings → 5 dims before clustering.",
    "Makes density clustering work better; distances in the plot are not globally meaningful.",
    ["bertopic", "pca"]),
  g("hdbscan", "HDBSCAN", "ie", "clustering",
    "A clustering method that finds dense groups and labels the rest as noise.",
    "Hierarchical density-based clustering that extracts stable clusters across density thresholds; does not require k and marks outliers as −1.",
    "Twelve snippets fit no cluster → noise.",
    "Honest about outliers; sensitive to min_cluster_size.",
    ["bertopic", "clustering"]),
  g("c-tf-idf", "Class-based TF-IDF (c-TF-IDF)", "ie", "clustering",
    "TF-IDF computed per cluster, to find the words that describe each cluster.",
    "Treats all documents in a cluster as one document and computes term importance relative to other clusters.",
    "Cluster keywords: 'emi, zyada, high'.",
    "Gives clusters human-readable names.",
    ["bertopic", "tf-idf"], ["ctfidf"]),
  g("pca", "PCA", "ie", "embeddings",
    "Finds the directions along which the data varies the most, to plot it in 2D.",
    "Principal Component Analysis: projects data onto top eigenvectors of the covariance matrix; linear and variance-preserving.",
    "384-dim embeddings projected to 2D for visualization.",
    "Quick, deterministic visualization; can hide non-linear structure.",
    ["umap", "embedding"], ["principal component analysis"]),
  g("topic-modeling", "Topic modeling", "ie", "clustering",
    "Automatically finding the main themes in a collection of texts.",
    "Unsupervised discovery of latent themes, classically LDA (word co-occurrence) and more recently embedding-based methods like BERTopic.",
    "Themes across 50k calls: rate concern, documentation, timing.",
    "Feeds open-set discovery and taxonomy revision.",
    ["bertopic", "clustering"], ["topic model", "topic modelling"]),
];

export const GLOSSARY_MAP: Record<string, GlossaryTerm> = Object.fromEntries(GLOSSARY.map((t) => [t.id, t]));

/** Resolve a term by id, name or alias (case-insensitive). */
export function findTerm(key: string): GlossaryTerm | undefined {
  const k = key.trim().toLowerCase();
  if (GLOSSARY_MAP[k]) return GLOSSARY_MAP[k];
  return GLOSSARY.find(
    (t) => t.term.toLowerCase() === k || t.aliases?.some((a) => a.toLowerCase() === k),
  );
}
