import type { Lesson } from "../../types";

export const cachingBatching: Lesson = {
  slug: "caching-batching",
  module: "llm",
  order: 9,
  title: "Prompt Caching and Batching",
  tagline: "Stop paying full price to re-read the same 5,000-token rulebook 100,000 times.",
  difficulty: "Intermediate",
  minutes: 25,
  stages: ["classification", "decision"],
  why: `In a transcript pipeline, most of each prompt is identical across calls: the system prompt, the labelling rulebook, the few-shot examples. Only the transcript changes. Without **[[prompt caching|prompt-caching]]**, you pay to process that static prefix on every single call — often 70–80% of your input bill.

**[[Batching]]** attacks cost from the other side: if results can wait (nightly analytics), asynchronous batch processing typically trades hours of latency for a substantial discount and higher throughput. Both are architecture decisions, not afterthoughts.`,
  concepts: [
    {
      title: "How prompt caching works",
      intuition: `The model processes your prompt left to right. If the beginning of today's prompt is byte-for-byte identical to a recent one, the provider can reuse the already-computed work for that prefix instead of recomputing it. You pay a reduced rate for the reused part — and the answer starts sooner.`,
      technical: `During prefill, transformers compute key/value (KV) tensors for every input token. Providers can store the KV state for a prompt prefix and reuse it for later requests sharing that exact prefix. Billing typically distinguishes cache writes (sometimes at a premium), cache reads (at a steep discount) and uncached input. Caches have a time-to-live, so hit rates depend on traffic patterns. Any change in the prefix (a timestamp, a reordered rule) breaks the match from that point on. The exact mechanics, multipliers and minimum sizes differ by provider — check their docs.`,
      example: `100,000 calls × (5,000 rulebook + 1,000 conversation) tokens. Without caching: 600M input tokens at full price. With a 95% hit rate and cache reads at 0.1× price, the rulebook portion costs roughly a tenth — cutting the input bill by ~70%. Try it in the lab.`,
    },
    {
      title: "Batching: latency for price and throughput",
      intuition: `Instead of sending 200,000 requests one by one and waiting for each, you submit them as one job and collect results later. The provider can schedule them efficiently, so it's cheaper — but you might wait hours.`,
      technical: `Two meanings: (1) **server-side dynamic batching** — inference servers group concurrent requests to raise GPU utilization (throughput ↑, per-request latency ↑); (2) **asynchronous batch APIs** — submit a file of independent requests; results arrive within a completion window at a discount. Batch APIs suit offline, independent work (nightly classification, backfills, evaluations); they're unsuitable for real-time paths and for workflows where each step depends on the previous result.`,
      example: `Nightly intent analytics on yesterday's calls: batch + cached rulebook. Live agent assist: neither batch API nor long prompts — a small model with a short, cached prompt.`,
    },
  ],
  questions: {
    what: "Prompt caching reuses processed prompt prefixes across requests; batching groups requests for efficiency (server-side) or discounted async processing (batch APIs).",
    why: "Transcript pipelines repeat large static prompts and often don't need instant answers.",
    problem: "They cut cost (and, for caching, latency) without changing model quality.",
    how: "Put static content first and keep it byte-identical; monitor cache hit rates; route offline workloads to batch processing.",
    onRealData: "Rulebooks and examples are large and stable; transcripts vary; nightly analytics can wait; live assist can't.",
    whatCanGoWrong: "Dynamic content (timestamps, customer names) at the start of the prompt breaks caching; cache expiry between sparse calls lowers hit rates; batch jobs used for latency-sensitive paths.",
    howToEvaluate: "Track cached vs uncached input tokens, hit rate, cost per call and TTFT before/after; batch job completion times.",
    whenToUse: "Caching: any repeated prefix of meaningful size. Batching: offline, independent requests.",
    whenNotToUse: "Batch APIs for real-time needs; caching tiny or constantly changing prompts.",
    downstream: "Caching changes the economics of long rulebooks and few-shot examples; batching changes when results are available.",
  },
  lab: {
    id: "caching-batching",
    title: "Cost simulator",
    intro: "Enter call volume, rulebook and conversation sizes, prices, cache multipliers, hit rate and batch discount. Compare no caching, caching, batching and both — and see what happens if the static content isn't first.",
    modes: ["computed"],
  },
  realWorld: {
    text: `A team enabled prompt caching but saw almost no savings. Their prompt began with “Today is {date}. Call ID {id}.” — unique per call, so no prefix ever matched. Moving call metadata after the rulebook raised the cache hit rate from ~0% to 93% and cut monthly input cost by 68% with identical outputs.`,
  },
  mistakes: [
    { mistake: "Putting per-call metadata at the start of the prompt", why: "The prefix differs every time; nothing is reused.", fix: "Static content first; dynamic content last." },
    { mistake: "Editing the rulebook text casually", why: "Any change invalidates the cache (and changes behaviour).", fix: "Version prompts; change them deliberately." },
    { mistake: "Using batch APIs for live flows", why: "Completion windows are long.", fix: "Batch only offline, independent work." },
  ],
  decision: {
    question: "Should this workload use caching, batching, both or neither?",
    useWhen: ["Caching: large static prefix reused across many calls within the cache lifetime", "Batching: results can wait; requests are independent", "Both: nightly analytics with a shared rulebook"],
    avoidWhen: ["Batching for real-time", "Caching when prompts are small or unique per call"],
    tradeoffs: [
      { a: "Batch discount", b: "Latency", note: "Hours of delay for lower price — fine for analytics, fatal for assist." },
      { a: "Long cached rulebook", b: "Prompt bloat", note: "Caching makes long prompts cheaper, not free, and doesn't fix distraction." },
    ],
  },
  exercises: [
    {
      id: "cb-ex-1",
      kind: "numeric",
      exType: "applied",
      difficulty: "Intermediate",
      concept: "prompt-caching",
      prompt: "100,000 calls, rulebook 5,000 tokens, conversation 1,000 tokens, $3 per 1M input. With **no caching**, what is the rulebook's share of input cost in dollars?",
      answer: 1500,
      tolerance: 1,
      unit: "$",
      hint: "100,000 × 5,000 tokens at $3/M.",
      explanation: "500M tokens × $3/M = **$1,500** of a $1,800 input bill — 83% spent re-reading the same rules.",
    },
    {
      id: "cb-ex-2",
      kind: "numeric",
      exType: "applied",
      difficulty: "Advanced",
      concept: "prompt-caching",
      prompt: "Same setup. Caching: 100% hit rate, cache reads cost 0.1× the input price (ignore writes). What is the new total INPUT cost in dollars?",
      answer: 450,
      tolerance: 1,
      unit: "$",
      hint: "Rulebook at 0.1× + conversation at full price.",
      explanation: "Rulebook: $1,500 × 0.1 = $150. Conversation: 100M × $3/M = $300. Total **$450** (vs $1,800).",
    },
    {
      id: "cb-ex-3",
      kind: "mcq",
      exType: "conceptual",
      difficulty: "Intermediate",
      concept: "batching",
      prompt: "Which workload is the best fit for an asynchronous batch API?",
      options: [
        { text: "Re-classifying last quarter's 2M calls with a new prompt", correct: true },
        { text: "Suggesting responses to agents during live calls", whyWrong: "Needs sub-second latency." },
        { text: "An agent loop where each step depends on the previous tool result", whyWrong: "Requests aren't independent." },
        { text: "A customer-facing chatbot", whyWrong: "Interactive." },
      ],
      hint: "Independent and not time-critical.",
      explanation: "Backfills and offline evaluations are ideal batch jobs.",
    },
    {
      id: "cb-ex-4",
      kind: "text",
      exType: "engineering",
      difficulty: "Intermediate",
      concept: "prompt-caching",
      prompt: "Restructure this prompt for caching and explain why: `[call ID + date] [transcript] [rulebook, 5k tokens] [4 examples] [task + output format]`.",
      rubric: [
        { idea: "Static content first (rulebook, examples, instructions)", keywords: ["rulebook first", "static", "first", "prefix", "beginning"] },
        { idea: "Per-call content last (call ID, date, transcript)", keywords: ["last", "end", "after", "dynamic", "per-call", "per call"] },
        { idea: "Keep the static prefix byte-identical / versioned", keywords: ["identical", "byte", "version", "unchanged", "same"] },
        { idea: "Monitor cache hit rate or cached tokens", keywords: ["hit rate", "monitor", "cached tokens", "cost"] },
      ],
      minIdeas: 2,
      hint: "Which parts are identical across calls?",
      modelAnswer:
        "New order: [system + rulebook] [4 examples] [task + output format] — all static and byte-identical, forming the cached prefix — then [call ID + date + transcript] at the end (optionally followed by a one-line reminder of the task). The old prompt started with a unique call ID, so no prefix ever matched. Version the static block so edits are deliberate, and monitor the cached-token share and hit rate after deploying.",
      explanation: "Caching rewards stable prefixes: static first, dynamic last.",
    },
  ],
  quiz: [
    {
      id: "cb-q-1",
      kind: "mcq",
      difficulty: "Beginner",
      concept: "prompt-caching",
      prompt: "Prompt caching reuses…",
      options: [
        { text: "Computation for an identical prompt prefix", correct: true },
        { text: "Previous answers to the same question", whyWrong: "That's response caching, a different thing." },
        { text: "The model weights", whyWrong: "Weights are always loaded." },
        { text: "The tokenizer", whyWrong: "No." },
      ],
      hint: "Prefix.",
      explanation: "KV state of a shared prefix is reused; outputs are still generated fresh.",
    },
    {
      id: "cb-q-2",
      kind: "mcq",
      difficulty: "Intermediate",
      concept: "prompt-caching",
      prompt: "Your prompt starts with the call ID. Cache hit rate is ~0%. Why?",
      options: [
        { text: "The prefix differs on every call, so there's nothing identical to reuse", correct: true },
        { text: "Call IDs are too long", whyWrong: "Length isn't the issue; uniqueness is." },
        { text: "Caching only works for English", whyWrong: "No." },
        { text: "The rulebook is too short", whyWrong: "It's after the unique part anyway." },
      ],
      hint: "What must match?",
      explanation: "Move per-call data after the static prefix.",
    },
    {
      id: "cb-q-3",
      kind: "mcq",
      difficulty: "Intermediate",
      concept: "prompt-caching",
      prompt: "Besides cost, prompt caching mainly improves…",
      options: [
        { text: "Time to first token", correct: true },
        { text: "Model accuracy", whyWrong: "Outputs are unchanged." },
        { text: "Output length", whyWrong: "No." },
        { text: "Tokenization", whyWrong: "No." },
      ],
      hint: "Less prefill work.",
      explanation: "Reused prefill → faster first token.",
    },
    {
      id: "cb-q-4",
      kind: "multi",
      difficulty: "Intermediate",
      concept: "prompt-caching",
      prompt: "Which reduce the cache hit rate? (Select all)",
      options: [
        { text: "Long gaps between calls exceeding the cache lifetime", correct: true },
        { text: "Editing a single character in the rulebook", correct: true },
        { text: "Putting a timestamp before the rulebook", correct: true },
        { text: "Varying the transcript at the end of the prompt", whyWrong: "Content after the prefix doesn't affect prefix matching." },
      ],
      hint: "Expiry and prefix changes.",
      explanation: "Hits need identical prefixes within the cache lifetime.",
    },
    {
      id: "cb-q-5",
      kind: "mcq",
      difficulty: "Advanced",
      concept: "batching",
      prompt: "Server-side dynamic batching increases throughput because…",
      options: [
        { text: "Weights loaded for one forward pass serve many requests, improving GPU utilization", correct: true },
        { text: "It skips tokens", whyWrong: "No." },
        { text: "It lowers per-request latency", whyWrong: "It usually raises it." },
        { text: "It shortens prompts", whyWrong: "No." },
      ],
      hint: "Memory bandwidth amortization.",
      explanation: "Batching amortizes the cost of reading weights over more tokens.",
    },
  ],
  challenge: {
    id: "cb-ch-1",
    kind: "numeric",
    exType: "applied",
    difficulty: "Expert",
    concept: "prompt-caching",
    prompt: "Rulebook 5,000 tokens, 100,000 calls, $3/M input. Hit rate 90%; cache writes (misses) cost 1.25× and reads 0.1×. What is the rulebook's input cost in dollars?",
    answer: 322.5,
    tolerance: 0.6,
    unit: "$",
    hint: "Full-price rulebook cost is $1,500. Split 10% at 1.25× and 90% at 0.1×.",
    explanation: "$1,500 × (0.10 × 1.25 + 0.90 × 0.10) = $1,500 × 0.215 = **$322.50**. Hit rate matters: at 50% it would be $1,012.",
  },
  related: ["context-engineering", "model-selection", "tokenization"],
  terms: ["prompt-caching", "batching", "ttft", "throughput", "system-prompt"],
};
