import type { Lesson } from "../../types";

export const contextEngineering: Lesson = {
  slug: "context-engineering",
  module: "llm",
  order: 3,
  title: "Context Engineering",
  tagline: "What goes into the context window, in what order — and why more context can make answers worse.",
  difficulty: "Intermediate",
  minutes: 35,
  stages: ["classification", "evidence"],
  why: `Modern models accept huge **[[context windows|context-window]]**, so it's tempting to stuff in everything: the full rulebook, old calls, the product catalogue, policy PDFs. Every token costs money on every call, adds latency, and gives the model more places to look in the wrong direction.

**[[Context engineering|context-engineering]]** is deciding what the model sees: relevant rules and examples, the transcript, pre-extracted evidence, the question — ordered so stable parts are cacheable and critical parts aren't buried.`,
  concepts: [
    {
      title: "Budget, relevance and order",
      intuition: `Treat the context window like a briefing document for a busy expert. Include what they need, leave out what they don't, put the standing instructions first and the actual question last. Irrelevant pages don't just waste money — they distract.`,
      technical: `Per-call input cost ∝ total tokens; prefill latency grows with input length; [[prompt caching|prompt-caching]] only reuses an identical prefix, so static blocks (system prompt, rulebook, examples) should come first and dynamic blocks (transcript, retrieved evidence, query) after. Irrelevant content ([[prompt bloat|prompt-bloat]]) increases the chance of attending to distractors and of conflicting instructions ([[context rot|context-rot]]).`,
      example: `System (180) + rulebook (2,400) + examples (900) + conversation (1,300) + query (90) ≈ 4.9k tokens. Adding a 9k-token HR handbook and a 6k-token catalogue triples cost and makes the call's evidence a small island in the middle.`,
    },
    {
      title: "Position effects: lost in the middle",
      intuition: `Models tend to use information at the very beginning and very end of a long context more reliably than information in the middle. The effect varies a lot between models and has shrunk in newer ones — which is exactly why you measure it on yours instead of assuming.`,
      technical: `Liu et al. (2023, “Lost in the Middle”) reported a U-shaped accuracy curve over the position of the relevant document in multi-document QA. Needle-in-a-haystack tests probe the same effect. Mitigations: keep contexts short and relevant, place critical instructions at the start and the question at the end, pre-extract evidence and put it near the query, and test positions explicitly for your model and prompt.`,
      example: `A 60-call haystack with the key customer note at call #2, #30 and #59: run it in the lab against a real model (backend required) — one trial per position is an anecdote; repeat with many needles for a measurement.`,
    },
    {
      title: "Retrieval vs stuffing",
      intuition: `Stuffing = put everything in every call. Retrieval = pick the relevant pieces per call. Stuffing is simple and never misses a document; retrieval is cheaper and more focused but can miss what matters.`,
      technical: `Choose by corpus size, change frequency and relevance ratio. Small and stable (a 2k-token rulebook) → include as cached prefix. Large and mostly irrelevant per call (400 pages of policy) → retrieve top-k chunks (see [[RAG|rag]]) and evaluate retrieval recall. For long transcripts, segment selection (e.g., objection-handling + closing segments) is a form of retrieval within the call.`,
      example: `For intent classification, the needed knowledge is the label definitions (small, static) and the call itself. No retrieval needed — just a lean, well-ordered context.`,
    },
  ],
  questions: {
    what: "The design of everything placed in a model's input: instructions, knowledge, examples, conversation state, retrieved evidence and the query.",
    why: "Output quality, cost and latency all depend on what the model sees and where.",
    problem: "It prevents prompt bloat, distraction and position effects while enabling caching.",
    how: "Budget tokens per block, include only relevant content, order static→dynamic, pre-extract evidence, measure position sensitivity.",
    onRealData: "Long calls (30+ minutes), long rulebooks, repeated history from previous calls, and multiple products per call.",
    whatCanGoWrong: "Context overflow, bloat, buried evidence, conflicting duplicated rules (v1 and v2 rulebook), dynamic content breaking the cache prefix.",
    howToEvaluate: "Ablate blocks (with/without), vary positions, track cost and latency per call, and measure accuracy on long-call slices.",
    whenToUse: "Every LLM system; it matters most for long inputs and high volume.",
    whenNotToUse: "Don't micro-optimize token counts on low-volume prototypes before measuring quality.",
    downstream: "Context design sets cost per decision, latency, cache hit rate and accuracy on long calls.",
  },
  lab: {
    id: "context-engineering",
    title: "Context-window simulator",
    intro: "Toggle and reorder context blocks, watch token usage, cost, cacheable prefix and warnings update. Then explore the beginning/middle/end position experiment — simulated, or for real against a model through the backend.",
    modes: ["computed", "simulated", "real-model"],
  },
  realWorld: {
    text: `A team concatenated the last three calls with each new call “for context”. Accuracy on the current call's intent dropped 4 points: the model sometimes answered based on an older call where the customer had been interested. Cost rose 2.7×. Replacing history with a two-line structured summary (“previous outcome: not interested, reason: rate”) placed after the current transcript restored accuracy and cut cost.`,
  },
  mistakes: [
    { mistake: "More context = better answers", why: "Irrelevant tokens cost money and distract.", fix: "Add blocks only when an ablation shows they help." },
    { mistake: "Dynamic content before static content", why: "The prefix differs every call, so nothing is cached.", fix: "Static first: system, rules, examples; then transcript and query." },
    { mistake: "Duplicated or conflicting instructions", why: "Old and new rulebooks both present → inconsistent behaviour.", fix: "Version and deduplicate prompt components." },
    { mistake: "Assuming position effects without measuring", why: "They differ across models and prompts.", fix: "Run a position experiment on your model." },
  ],
  decision: {
    question: "Stuff it or retrieve it?",
    useWhen: ["Stuff: small, stable, always-relevant knowledge (label definitions)", "Retrieve: large, changing, mostly irrelevant-per-call corpora", "Select segments: very long calls"],
    avoidWhen: ["Stuffing large corpora into every call", "Retrieval when the answer is always in the transcript"],
    tradeoffs: [
      { a: "Long context", b: "Cost", note: "Every token is paid per call; caching softens static blocks, not dynamic ones." },
      { a: "Retrieval", b: "Stuffing", note: "Retrieval is focused but can miss; stuffing never misses but dilutes and costs more." },
    ],
  },
  exercises: [
    {
      id: "ctx-ex-1",
      kind: "mcq",
      exType: "conceptual",
      difficulty: "Beginner",
      concept: "context-budget",
      prompt: "Which ordering best supports prompt caching?",
      options: [
        { text: "System prompt → rulebook → examples → transcript → question", correct: true },
        { text: "Transcript → system prompt → rulebook → question", whyWrong: "The first tokens differ per call, so no shared prefix." },
        { text: "Question → transcript → rulebook", whyWrong: "Dynamic content first breaks the prefix." },
        { text: "Order doesn't matter for caching", whyWrong: "Caching reuses identical prefixes only." },
      ],
      hint: "What stays identical across calls?",
      explanation: "Static content first forms a reusable prefix.",
    },
    {
      id: "ctx-ex-2",
      kind: "numeric",
      exType: "applied",
      difficulty: "Intermediate",
      concept: "context-budget",
      prompt: "Your context is 4,900 relevant tokens. You add a 9,100-token handbook and a 6,200-token catalogue, both irrelevant. What fraction of the context is now irrelevant? (decimal, 2 places)",
      answer: 0.76,
      tolerance: 0.01,
      hint: "irrelevant / (relevant + irrelevant).",
      explanation: "15,300 / 20,200 ≈ **0.76**. Three quarters of every call's input cost buys distraction.",
    },
    {
      id: "ctx-ex-3",
      kind: "text",
      exType: "engineering",
      difficulty: "Advanced",
      concept: "lost-in-middle",
      prompt: "Design an experiment to test whether your model misses evidence placed in the middle of long transcripts.",
      rubric: [
        { idea: "Insert a known fact (needle) at controlled positions", keywords: ["needle", "insert", "position", "beginning", "middle", "end"] },
        { idea: "Many trials / multiple needles per position", keywords: ["many", "repeat", "trials", "multiple", "sample size"] },
        { idea: "Vary context length", keywords: ["length", "long", "short", "tokens"] },
        { idea: "Report accuracy per position with confidence intervals", keywords: ["accuracy", "confidence interval", "ci", "per position", "compare"] },
        { idea: "Use realistic distractors from real transcripts", keywords: ["realistic", "distractor", "real transcripts", "similar"] },
      ],
      minIdeas: 3,
      hint: "Control the variable (position), repeat enough, measure uncertainty.",
      modelAnswer:
        "Build haystacks from real call notes (realistic distractors), insert a verifiable needle (e.g., a unique amount) at 0%, 25%, 50%, 75%, 100% positions, at several context lengths (4k, 16k, 64k). Run ≥50 needles per cell at temperature 0, score exact-match answers, and report accuracy per position with Wilson CIs. Compare positions with a paired test on the same needles.",
      explanation: "A controlled, repeated, uncertainty-aware experiment beats anecdotes and generic claims.",
    },
  ],
  quiz: [
    {
      id: "ctx-q-1",
      kind: "mcq",
      difficulty: "Beginner",
      concept: "context-budget",
      prompt: "“Prompt bloat” refers to…",
      options: [
        { text: "Prompts accumulating instructions and content that no longer help, raising cost and confusion", correct: true },
        { text: "Models generating very long outputs", whyWrong: "That's verbosity." },
        { text: "Tokenizers producing many tokens", whyWrong: "Related to cost, but not the concept." },
        { text: "Prompt caching failures", whyWrong: "Different issue." },
      ],
      hint: "It grows over iterations.",
      explanation: "Bloat comes from accreting rules/examples/docs without pruning.",
    },
    {
      id: "ctx-q-2",
      kind: "mcq",
      difficulty: "Intermediate",
      concept: "lost-in-middle",
      prompt: "The 'lost in the middle' finding says that…",
      options: [
        { text: "Relevant information in the middle of a long context is often used less reliably than at the start or end", correct: true },
        { text: "Models ignore the end of prompts", whyWrong: "The end is typically well used." },
        { text: "All models are equally affected", whyWrong: "Effects vary by model; measure yours." },
        { text: "Middle tokens cost more", whyWrong: "Pricing is per token regardless of position." },
      ],
      hint: "U-shaped curve.",
      explanation: "Position matters in long contexts; magnitude is model-dependent.",
    },
    {
      id: "ctx-q-3",
      kind: "mcq",
      difficulty: "Intermediate",
      concept: "retrieval-vs-stuffing",
      prompt: "A 2,000-token label rulebook that changes monthly should be…",
      options: [
        { text: "Included in every prompt as a cached static prefix", correct: true },
        { text: "Retrieved with a vector database per call", whyWrong: "Overkill; it's small and always relevant." },
        { text: "Left out — the model knows the labels", whyWrong: "The model doesn't know your definitions." },
        { text: "Summarized by the model each call", whyWrong: "Adds cost and variance." },
      ],
      hint: "Small + always relevant.",
      explanation: "Small, always-relevant knowledge belongs in the prompt (cached).",
    },
    {
      id: "ctx-q-4",
      kind: "multi",
      difficulty: "Intermediate",
      concept: "context-budget",
      prompt: "Which reduce cost without hurting accuracy in a typical intent pipeline? (Select all)",
      options: [
        { text: "Removing irrelevant documents from the context", correct: true },
        { text: "Deduplicating old/new rulebook versions", correct: true },
        { text: "Moving static blocks first to enable caching", correct: true },
        { text: "Truncating the transcript at a fixed token count", whyWrong: "May cut the decisive final turns." },
      ],
      hint: "One of these can remove evidence.",
      explanation: "Prune, deduplicate and order for caching; don't blindly truncate evidence.",
    },
    {
      id: "ctx-q-5",
      kind: "mcq",
      difficulty: "Advanced",
      concept: "retrieval-vs-stuffing",
      prompt: "Replacing three previous full transcripts with a short structured summary of prior outcomes mainly…",
      options: [
        { text: "Keeps useful history while removing distracting content and cost", correct: true },
        { text: "Always loses important information", whyWrong: "It can, but a good summary keeps what matters." },
        { text: "Breaks prompt caching", whyWrong: "The summary is dynamic either way." },
        { text: "Increases latency", whyWrong: "Fewer tokens → lower latency." },
      ],
      hint: "Compression of context.",
      explanation: "Structured summaries preserve signal at a fraction of the tokens and reduce confusion with the current call.",
    },
  ],
  challenge: {
    id: "ctx-ch-1",
    kind: "numeric",
    exType: "applied",
    difficulty: "Advanced",
    concept: "context-budget",
    prompt: "A 16k-token window. Static prefix = 3,500 tokens, reserved output = 500 tokens, question = 100 tokens. Long calls average 1.25 tokens per word. What is the maximum call length in **words** that fits without chunking?",
    answer: 9520,
    tolerance: 10,
    unit: "words",
    hint: "Available = 16,000 − 3,500 − 500 − 100 tokens; divide by tokens per word.",
    explanation: "16,000 − 4,100 = 11,900 tokens ÷ 1.25 ≈ **9,520 words**. (Using 16,384 as the window gives ≈9,827 — know which your provider means.)",
  },
  related: ["caching-batching", "rag-agents", "tokenization"],
  terms: ["context-window", "context-engineering", "lost-in-the-middle", "context-rot", "prompt-bloat", "prompt-caching"],
};
