import type { Lesson } from "../../types";

export const grounding: Lesson = {
  slug: "grounding",
  module: "llm",
  order: 4,
  title: "Grounding and Faithfulness",
  tagline: "Answer + Evidence + Reasoning: every claim must point at words that were actually said.",
  difficulty: "Intermediate",
  minutes: 35,
  stages: ["evidence", "verification"],
  why: `“The customer is interested” is an opinion. “The customer is interested — evidence: *‘haan bhej do, main kal tak apply kar dunga’* (turn 10, customer)” is an auditable claim. **[[Grounding|grounding]]** forces every output to cite its support; **[[faithfulness]]** asks whether the output is actually entailed by that support.

This single design choice makes errors visible (reviewers check quotes in seconds), enables automatic verification (does the quote exist? was it the customer? does it entail the claim?), and turns “we don't know” into a legitimate answer instead of a guess.`,
  concepts: [
    {
      title: "Three verdicts: supported, contradicted, insufficient evidence",
      intuition: `Given a transcript and a claim, there are three honest answers:
- **Supported** — the transcript implies it.
- **Contradicted** — the transcript implies it's false.
- **[[Insufficient evidence|insufficient-evidence]]** — the transcript doesn't settle it.

Most grounding errors come from merging the last two: treating “not said” as “false”, or treating “plausible” as “said”.`,
      technical: `This is the natural language inference ([[NLI|nli]]) triplet: [[entailment]], contradiction, neutral. A claim is entailed if a typical reader would infer it from the premise. For transcripts, the premise is the relevant customer turns (plus the questions they answer). Verification can be done by an NLI model or an LLM prompted as a verifier with the claim and cited spans only.`,
      example: `“I might consider a loan next month… I said I might consider it.” Claim: “The customer is definitely interested.” → **Insufficient evidence** (not contradicted: interest isn't ruled out; not supported: no commitment).`,
    },
    {
      title: "Evidence spans",
      intuition: `An **[[evidence span|evidence-span]]** is the exact quote that supports the answer. Good evidence is verbatim (can be found by string search), from the right speaker, minimal (just the decisive part), and complete (includes the resolution if there's an objection).`,
      technical: `Represent evidence as {turn_index, speaker, quote, char_offsets}. Automatic checks: (1) quote exists in the original transcript (normalized string match); (2) speaker matches the claim's subject (customer claims need customer turns — but claims about the agent's offer need agent turns); (3) entailment check between quote(s) and claim; (4) completeness: later turns don't contradict (resolved objections). Evaluate evidence with overlap metrics against gold evidence turns.`,
      example: `Claim: “The customer was offered 10.5%.” Evidence: agent turn “sir 14 percent se start hota hai” → **Contradicted**; 10.5% was the competitor's rate the customer mentioned. Here agent speech IS valid evidence because the claim is about the agent's offer.`,
    },
  ],
  questions: {
    what: "Requiring outputs to be supported by, and traceable to, specific parts of the source (grounding); and the degree to which outputs are entailed by it (faithfulness).",
    why: "Fluent outputs can be unsupported; without citations, errors are invisible and unauditable.",
    problem: "It makes each decision verifiable by humans and machines and gives a principled way to say 'unknown'.",
    how: "Require {answer, evidence spans, reasoning}; verify quotes exist, check speaker, check entailment; allow insufficient_evidence.",
    onRealData: "Hedges, agent paraphrases, resolved objections, third-party mentions and sarcasm all create claims that look supported by a partial quote.",
    whatCanGoWrong: "Cherry-picked quotes (the objection, not the resolution), paraphrased 'quotes' that don't exist, agent speech cited as customer evidence, 'not mentioned' treated as 'false'.",
    howToEvaluate: "Verdict accuracy, evidence overlap (precision/recall of cited turns vs gold), quote-existence rate, speaker-correctness rate.",
    whenToUse: "Any output a human might dispute or act on: intent, consent, compliance, complaints.",
    whenNotToUse: "Pure aggregate topic stats where individual audit isn't needed — still useful for sampling audits.",
    downstream: "Evidence enables verification stages, faster human review, dispute resolution and error analysis.",
  },
  lab: {
    id: "grounding",
    title: "Evidence-based verification",
    intro: "For each claim, select the evidence turns in the transcript, choose Supported / Contradicted / Insufficient evidence, and write your reasoning. Get the reference verdict and see your answer as an auditable record.",
    modes: ["precomputed"],
  },
  realWorld: {
    text: `A dispute team received a complaint: “I never agreed to this loan.” The system's record showed intent=interested with evidence “haan… theek hai” (turn 14). Replaying turn 13 revealed the agent's question: “sir aapko documents WhatsApp kar du?” — the customer agreed to receive documents, not to the loan. The evidence field made the error findable in two minutes and led to a new verifier rule: evidence must entail the specific claim, not merely be positive.`,
    transcript: [
      { speaker: "Customer", text: "I might consider a loan next month." },
      { speaker: "Agent", text: "So you want a loan?" },
      { speaker: "Customer", text: "I said I might consider it." },
    ],
  },
  mistakes: [
    { mistake: "Treating 'not mentioned' as 'false'", why: "It converts uncertainty into confident negatives.", fix: "Use a three-way verdict with insufficient evidence." },
    { mistake: "Citing a positive-sounding quote that answers a different question", why: "'haan' to 'shall I send documents?' ≠ agreeing to the loan.", fix: "Include the adjacent question; check entailment of the specific claim." },
    { mistake: "Accepting paraphrased quotes", why: "They can't be verified and often distort.", fix: "Require verbatim quotes; string-check them." },
  ],
  decision: {
    question: "How strict should evidence requirements be?",
    useWhen: ["Decisions are contestable or regulated", "Humans review outputs", "You need a verification stage"],
    avoidWhen: ["Never skip entirely for customer-facing decisions — at least sample-audit"],
    tradeoffs: [
      { a: "Strict evidence rules", b: "Coverage", note: "More outputs become insufficient_evidence; that's honest, and you can route them to review." },
      { a: "Longer outputs (evidence + reasoning)", b: "Cost/latency", note: "Evidence adds tokens but pays for itself in debuggability." },
    ],
  },
  exercises: [
    {
      id: "gr-ex-1",
      kind: "evidence",
      exType: "applied",
      difficulty: "Beginner",
      concept: "entailment",
      transcript: [
        { speaker: "Customer", text: "I might consider a loan next month." },
        { speaker: "Agent", text: "So you want a loan?" },
        { speaker: "Customer", text: "I said I might consider it." },
      ],
      claim: "The customer is definitely interested.",
      verdicts: ["Supported", "Contradicted", "Insufficient evidence"],
      correctVerdict: "Insufficient evidence",
      evidenceTurns: [0, 2],
      prompt: "Is the customer definitely interested? Select the evidence and a verdict.",
      hint: "What would 'definitely interested' require? Does anything rule interest out?",
      explanation: "The customer hedges ('might', 'next month') and corrects the agent. Not supported (no commitment), not contradicted (interest isn't ruled out) → insufficient evidence.",
    },
    {
      id: "gr-ex-2",
      kind: "evidence",
      exType: "applied",
      difficulty: "Intermediate",
      concept: "evidence-spans",
      transcript: [
        { speaker: "Agent", text: "sir aapka pre approved lone hai 3 lakh ka" },
        { speaker: "Customer", text: "emi kitna aayega" },
        { speaker: "Agent", text: "sir 3 saal ke liye approx 10 hazaar per month" },
        { speaker: "Customer", text: "to much hai yaar" },
        { speaker: "Agent", text: "sir tenure badha sakte hai 5 saal" },
        { speaker: "Customer", text: "haan fir theek hai 5 saal kar do. process kya hai" },
      ],
      claim: "The customer rejected the offer because the EMI was too high.",
      verdicts: ["Supported", "Contradicted", "Insufficient evidence"],
      correctVerdict: "Contradicted",
      evidenceTurns: [3, 5],
      prompt: "Verify the claim.",
      hint: "Read to the end of the call.",
      explanation: "The objection (turn 4) was resolved: turn 6 accepts the 5-year option. Citing only turn 4 is cherry-picking.",
    },
    {
      id: "gr-ex-3",
      kind: "text",
      exType: "engineering",
      difficulty: "Advanced",
      concept: "evidence-spans",
      prompt: "List automatic checks a verification stage should run on {intent, evidence} outputs before accepting them.",
      rubric: [
        { idea: "Quote exists verbatim in the transcript", keywords: ["exists", "verbatim", "string match", "found in"] },
        { idea: "Quote is from the correct speaker", keywords: ["speaker", "customer turn", "agent"] },
        { idea: "Quote entails the claim (NLI/LLM verifier)", keywords: ["entail", "nli", "support", "verifier"] },
        { idea: "Later turns don't contradict (completeness / resolution)", keywords: ["later", "resolved", "contradict", "complete", "final"] },
        { idea: "Route failures to review / lower confidence", keywords: ["review", "confidence", "flag", "needs_review"] },
      ],
      minIdeas: 3,
      hint: "Existence, speaker, entailment, completeness, then what to do on failure.",
      modelAnswer:
        "1) Existence: normalized substring match of the quote in the original transcript. 2) Speaker: the matched turn's speaker matches the claim's subject. 3) Entailment: an NLI model/LLM verifier checks quote(s) + adjacent question entail the claim. 4) Completeness: scan later customer turns for contradictions (resolved objections, retractions). 5) Any failure → lower confidence, needs_review = true, log the failure type.",
      explanation: "Cheap deterministic checks catch most fabricated or misattributed evidence before an expensive verifier call.",
    },
    {
      id: "gr-ex-4",
      kind: "mcq",
      exType: "conceptual",
      difficulty: "Intermediate",
      concept: "entailment",
      prompt: "Why keep 'Insufficient evidence' as a separate verdict instead of treating every unsupported claim as false?",
      options: [
        { text: "'The transcript doesn't say' differs from 'the transcript says the opposite'; merging them turns uncertainty into confident negatives", correct: true },
        { text: "It makes the model faster", whyWrong: "Speed isn't the reason." },
        { text: "Because contradiction can't be detected", whyWrong: "It can; it's a separate verdict." },
        { text: "It's only needed for English transcripts", whyWrong: "It applies to any language." },
      ],
      hint: "Not mentioned vs ruled out.",
      explanation: "A three-way verdict (supported / contradicted / insufficient) keeps 'we don't know' honest, and those cases can be routed to review instead of becoming false negatives.",
    },
  ],
  quiz: [
    {
      id: "gr-q-1",
      kind: "mcq",
      difficulty: "Beginner",
      concept: "entailment",
      prompt: "In NLI terms, 'insufficient evidence' corresponds to…",
      options: [
        { text: "Neutral", correct: true },
        { text: "Contradiction", whyWrong: "Contradiction means the premise implies the claim is false." },
        { text: "Entailment", whyWrong: "Entailment means the claim follows." },
        { text: "Hallucination", whyWrong: "That's a property of an output, not a verdict." },
      ],
      hint: "Neither implied true nor false.",
      explanation: "Neutral = the premise doesn't settle the hypothesis.",
    },
    {
      id: "gr-q-2",
      kind: "mcq",
      difficulty: "Intermediate",
      concept: "evidence-spans",
      prompt: "For the claim “the agent offered 14%”, which turn is valid evidence?",
      options: [
        { text: "Agent: “sir 14 percent se start hota hai”", correct: true },
        { text: "Customer: “14 percent bahut zyada hai”", whyWrong: "It echoes the rate but the claim is about what the agent offered — the agent's turn is the direct evidence." },
        { text: "Customer: “not interested”", whyWrong: "Unrelated to the offer." },
        { text: "None — only customer speech counts", whyWrong: "Speaker requirements depend on the claim's subject." },
      ],
      hint: "Whose action is the claim about?",
      explanation: "Evidence must come from the speaker the claim is about.",
    },
    {
      id: "gr-q-3",
      kind: "mcq",
      difficulty: "Intermediate",
      concept: "entailment",
      prompt: "“haan bhej do” answering “documents WhatsApp kar du?” supports which claim?",
      options: [
        { text: "The customer agreed to receive documents", correct: true },
        { text: "The customer agreed to take the loan", whyWrong: "Agreeing to receive documents ≠ agreeing to the loan." },
        { text: "The customer is not interested", whyWrong: "No." },
        { text: "Nothing", whyWrong: "It supports the narrower claim." },
      ],
      hint: "Read it with its question.",
      explanation: "Evidence entails specific claims; overgeneralizing is a grounding error.",
    },
    {
      id: "gr-q-4",
      kind: "multi",
      difficulty: "Intermediate",
      concept: "evidence-spans",
      prompt: "Properties of good evidence spans (select all):",
      options: [
        { text: "Verbatim", correct: true },
        { text: "From the right speaker", correct: true },
        { text: "Include the resolution when there was an objection", correct: true },
        { text: "As long as possible to be safe", whyWrong: "Minimal, decisive spans are easier to verify." },
      ],
      hint: "Verifiable, attributable, complete — but minimal.",
      explanation: "Verbatim, attributed, complete, minimal.",
    },
    {
      id: "gr-q-5",
      kind: "mcq",
      difficulty: "Advanced",
      concept: "entailment",
      prompt: "Why is 'Answer + Evidence + Reasoning' better than 'Answer' alone even if accuracy is identical?",
      options: [
        { text: "It makes errors detectable, reviewable and verifiable, and supports disputes", correct: true },
        { text: "It always increases accuracy", whyWrong: "Not always; its main value is auditability." },
        { text: "It reduces cost", whyWrong: "It adds output tokens." },
        { text: "It removes the need for evaluation", whyWrong: "You still evaluate." },
      ],
      hint: "Think about the day something goes wrong.",
      explanation: "Evidence turns silent errors into inspectable ones.",
    },
  ],
  challenge: {
    id: "gr-ch-1",
    kind: "evidence",
    exType: "applied",
    difficulty: "Advanced",
    concept: "entailment",
    transcript: [
      { speaker: "Agent", text: "sir personal loan offer hai aapke liye 10.99 percent pe" },
      { speaker: "Customer", text: "mujhe nahi chahiye,, par mere bhai ko chahiye tha shayad" },
      { speaker: "Agent", text: "sir unka number share kar sakte hai" },
      { speaker: "Customer", text: "main usko bol dunga woh call karega" },
    ],
    claim: "The customer's brother wants a personal loan.",
    verdicts: ["Supported", "Contradicted", "Insufficient evidence"],
    correctVerdict: "Insufficient evidence",
    evidenceTurns: [1],
    prompt: "Verify the claim about the third party.",
    hint: "'chahiye tha shayad' — how certain is that?",
    explanation: "“shayad” (maybe) and past tense (“chahiye tha”) make it a hedged second-hand report. Not supported as a present, definite want; not contradicted either.",
  },
  related: ["hallucination", "llm-judge", "speaker-attribution"],
  terms: ["grounding", "faithfulness", "evidence-span", "entailment", "nli", "insufficient-evidence"],
};
