import type { Lesson } from "../../types";

export const llmJudge: Lesson = {
  slug: "llm-judge",
  module: "llm",
  order: 5,
  title: "LLM-as-a-Judge",
  tagline: "A scalable measurement instrument with known biases — validate it before you trust it.",
  difficulty: "Advanced",
  minutes: 35,
  stages: ["verification", "evaluation"],
  why: `Humans can't grade 100,000 reasoning strings a week. An **[[LLM judge|llm-as-judge]]** can — cheaply and consistently. But a judge is a *measurement instrument*, and instruments have biases: it may prefer the first answer shown, the longer answer, answers written by its own model family, and it may share the generator's blind spots.

If you optimize your system against an unvalidated judge, you optimize for the judge's biases. This lesson is about using judges the way scientists use instruments: calibrate against a reference, measure the biases, and keep auditing.`,
  concepts: [
    {
      title: "Known judge biases",
      intuition: `- **[[Position bias|position-bias]]**: prefers whichever answer is shown first (or second).
- **[[Verbosity bias|verbosity-bias]]**: prefers longer, more confident-sounding answers.
- **[[Self-preference|self-preference-bias]]**: rates its own family's outputs higher.
- **Correlated errors**: can't catch mistakes it would make itself (e.g., Hinglish sarcasm).
- **Judge disagreement**: two judges often disagree — scores depend on the instrument.`,
      technical: `Position bias is measured by swapping order in pairwise comparisons and computing the flip rate. Verbosity bias: correlation between score and length within correct and within incorrect answers. Self-preference: compare judge win-rates with human win-rates for outputs from different families. Correlated errors: approval rate of wrong answers on slices where the generator fails (e.g., sarcasm) vs elsewhere. Report judge–human agreement with Cohen's κ on a stratified sample.`,
      example: `In the lab, a long, fluent, wrong answer to “I might consider it next month” gets 4/5 from the judge, while the short correct “insufficient_evidence” gets 3/5.`,
    },
    {
      title: "Using judges responsibly",
      intuition: `Give the judge a rubric and a reference answer, evaluate both orders, score components separately (label, evidence, reasoning), use a different model family where possible, and compare the judge with careful human labels on a sample before trusting it.`,
      technical: `Protocol: (1) Rubric-based, reference-guided prompts with discrete scales and explicit criteria (“length is not a criterion”). (2) Pairwise judgments in both orders; wins only when consistent. (3) Validation set of ~100–300 human-labelled items, stratified by slice; report κ and per-slice agreement. (4) Periodic audits and re-validation on judge/prompt/model changes. (5) Prefer deterministic metrics whenever a reference exists.`,
      example: `For intent labels, you don't need a judge: compare to gold labels. Use a judge for the *reasoning* field's faithfulness — and validate that judge against humans.`,
    },
  ],
  questions: {
    what: "Using an LLM to score or compare outputs according to a rubric or reference.",
    why: "Human evaluation doesn't scale to large volumes or rapid iteration.",
    problem: "It provides fast, cheap, consistent-ish quality signals for open-ended outputs.",
    how: "Prompt a judge model with the input, candidate output(s), rubric and optionally a reference; parse a score or preference.",
    onRealData: "Judges often share generators' weaknesses on Hinglish, sarcasm and hedges; they may reward confident English prose over terse correct labels.",
    whatCanGoWrong: "Position, verbosity and self-preference biases; correlated errors; drift when the judge model changes; Goodhart effects when you optimize against it.",
    howToEvaluate: "Judge–human agreement (κ) on a stratified sample; flip rate under order swap; score–length correlation; per-slice agreement.",
    whenToUse: "Open-ended quality (reasoning faithfulness, summary quality) at scale — after validation.",
    whenNotToUse: "When a deterministic reference comparison exists (exact labels, fields); as the only source of truth.",
    downstream: "Judge scores often gate releases and prompt changes; biased judges push systems toward verbose, judge-pleasing outputs.",
  },
  lab: {
    id: "llm-judge",
    title: "Judge simulator",
    intro: "Be the human judge on eight answers, then compare with an LLM judge and the reference. Explore position bias (order swaps), verbosity bias (score vs length) and self-preference/correlated errors with interactive simulations.",
    modes: ["precomputed", "simulated"],
  },
  realWorld: {
    text: `A team used a judge to pick between two prompt versions. The judge preferred version B in 68% of pairs. Swapping presentation order dropped that to 51%: most of B's “advantage” was position bias, because B had always been shown first. After evaluating both orders and validating against 200 human judgments (κ = 0.63 overall, 0.31 on Hinglish sarcasm), they used the judge for English reasoning quality only and kept humans on the sarcasm slice.`,
  },
  mistakes: [
    { mistake: "Treating judge scores as ground truth", why: "The judge is a biased instrument.", fix: "Validate against human labels; report κ." },
    { mistake: "Pairwise judging in one order only", why: "Position bias masquerades as a preference.", fix: "Judge both orders; count consistent wins only." },
    { mistake: "Using the same model family as generator and judge", why: "Self-preference and shared blind spots inflate scores.", fix: "Use a different family or measure the bias." },
    { mistake: "Using a judge where exact metrics exist", why: "Adds noise and cost to something you can compute exactly.", fix: "Compare to gold labels directly." },
  ],
  decision: {
    question: "Should I use an LLM judge?",
    useWhen: ["Open-ended outputs without a single correct reference", "You have human labels to validate the judge", "You'll audit periodically"],
    avoidWhen: ["Exact-match evaluation is possible", "No validation data exists", "The judge shares known blind spots with the generator on the slice you care about"],
    tradeoffs: [
      { a: "Human judges", b: "LLM judges", note: "Humans are slower and costlier but are the reference; LLM judges scale but need validation." },
      { a: "Pairwise", b: "Absolute scoring", note: "Pairwise is more sensitive but has position bias; absolute scores drift and compress." },
    ],
  },
  exercises: [
    {
      id: "jd-ex-1",
      kind: "mcq",
      exType: "conceptual",
      difficulty: "Intermediate",
      concept: "judge-bias",
      prompt: "A judge prefers answer A when A is shown first, and answer B when B is shown first. This is…",
      options: [
        { text: "Position bias", correct: true },
        { text: "Verbosity bias", whyWrong: "Lengths didn't change." },
        { text: "Self-preference", whyWrong: "Nothing about model families." },
        { text: "Calibration", whyWrong: "Unrelated." },
      ],
      hint: "What changed between the two judgments?",
      explanation: "Only the order changed, and so did the verdict.",
    },
    {
      id: "jd-ex-2",
      kind: "numeric",
      exType: "applied",
      difficulty: "Intermediate",
      concept: "judge-validation",
      prompt: "On 100 items, human and judge both say 'correct' 60 times, both 'incorrect' 20 times, disagree 20 times. Humans say 'correct' 70 times total; the judge says 'correct' 70 times total. Compute Cohen's κ (2 decimals).",
      answer: 0.52,
      tolerance: 0.01,
      hint: "pₒ = (60+20)/100. pₑ = 0.7·0.7 + 0.3·0.3.",
      explanation: "pₒ = 0.80, pₑ = 0.49 + 0.09 = 0.58, κ = (0.80 − 0.58)/(1 − 0.58) = 0.22/0.42 ≈ **0.52** — moderate agreement, despite 80% raw agreement.",
    },
    {
      id: "jd-ex-3",
      kind: "text",
      exType: "engineering",
      difficulty: "Advanced",
      concept: "judge-validation",
      prompt: "Design a protocol to validate an LLM judge that will score the faithfulness of 'reason' fields.",
      rubric: [
        { idea: "Human-labelled validation sample", keywords: ["human", "label", "sample", "gold"] },
        { idea: "Stratify by slices (language, noise, sarcasm)", keywords: ["stratif", "slice", "hinglish", "sarcasm", "noisy"] },
        { idea: "Report agreement (kappa) / accuracy vs humans", keywords: ["kappa", "κ", "agreement", "accuracy"] },
        { idea: "Test biases (order swap, length)", keywords: ["order", "swap", "position", "length", "verbosity"] },
        { idea: "Re-validate on changes / periodic audits", keywords: ["re-validate", "revalidate", "audit", "periodic", "drift", "change"] },
      ],
      minIdeas: 3,
      hint: "Treat it like calibrating a new measurement instrument.",
      modelAnswer:
        "Sample ~200 outputs stratified by language, transcript quality and hard slices (sarcasm, resolved objections). Have two humans label faithfulness with a rubric, adjudicate, measure human κ. Run the judge with the same rubric; report judge–human κ overall and per slice, plus score–length correlation. Freeze the judge prompt/model version; re-validate on any change and audit a monthly sample.",
      explanation: "A judge is trustworthy only on the slices where it has been shown to agree with humans.",
    },
  ],
  quiz: [
    {
      id: "jd-q-1",
      kind: "mcq",
      difficulty: "Beginner",
      concept: "judge-validation",
      prompt: "Why isn't an LLM judge automatically ground truth?",
      options: [
        { text: "It's a model with its own errors and biases; its agreement with humans must be measured", correct: true },
        { text: "It is — larger models are always right", whyWrong: "Size doesn't remove bias." },
        { text: "Judges can't read transcripts", whyWrong: "They can." },
        { text: "Only because it's expensive", whyWrong: "Cost isn't the reason." },
      ],
      hint: "Instrument vs truth.",
      explanation: "Validate the instrument before trusting its readings.",
    },
    {
      id: "jd-q-2",
      kind: "mcq",
      difficulty: "Intermediate",
      concept: "judge-bias",
      prompt: "A long, confident, wrong answer outscores a short correct one. This illustrates…",
      options: [
        { text: "Verbosity bias", correct: true },
        { text: "Position bias", whyWrong: "Order isn't involved." },
        { text: "Temperature", whyWrong: "No." },
        { text: "Prompt caching", whyWrong: "No." },
      ],
      hint: "What differs between the answers?",
      explanation: "Length and fluency sway judges.",
    },
    {
      id: "jd-q-3",
      kind: "mcq",
      difficulty: "Intermediate",
      concept: "judge-bias",
      prompt: "Generator and judge both miss Hinglish sarcasm. The judge approves most sarcasm errors. This is…",
      options: [
        { text: "Correlated errors", correct: true },
        { text: "Position bias", whyWrong: "No ordering involved." },
        { text: "Verbosity bias", whyWrong: "Length isn't the issue." },
        { text: "Class imbalance", whyWrong: "No." },
      ],
      hint: "Shared blind spots.",
      explanation: "A judge can't catch mistakes it would make itself.",
    },
    {
      id: "jd-q-4",
      kind: "mcq",
      difficulty: "Intermediate",
      concept: "judge-bias",
      prompt: "Best mitigation for position bias in pairwise comparisons:",
      options: [
        { text: "Evaluate both orders and only count consistent wins", correct: true },
        { text: "Always put the new system second", whyWrong: "Just moves the bias." },
        { text: "Increase temperature", whyWrong: "Adds noise, not fairness." },
        { text: "Use shorter answers", whyWrong: "Different bias." },
      ],
      hint: "Make order irrelevant by design.",
      explanation: "Swap orders; treat flips as ties; report the flip rate.",
    },
    {
      id: "jd-q-5",
      kind: "mcq",
      difficulty: "Advanced",
      concept: "judge-validation",
      prompt: "Intent labels have gold references. Should you use an LLM judge to score them?",
      options: [
        { text: "No — compare to gold labels directly with exact metrics", correct: true },
        { text: "Yes — judges are more nuanced", whyWrong: "Nuance adds noise when an exact reference exists." },
        { text: "Yes, but only with temperature 1", whyWrong: "No." },
        { text: "Only for English calls", whyWrong: "Exact metrics apply everywhere." },
      ],
      hint: "Is there a single correct answer to compare against?",
      explanation: "Exact metrics are free, deterministic and unbiased.",
    },
  ],
  challenge: {
    id: "jd-ch-1",
    kind: "mcq",
    exType: "engineering",
    difficulty: "Expert",
    concept: "judge-validation",
    prompt: "Your judge's overall κ with humans is 0.70, but on the sarcasm slice it's 0.25. Your new prompt improves judge scores most on sarcasm calls. What do you conclude?",
    options: [
      { text: "The improvement on sarcasm can't be trusted from the judge; verify that slice with human labels", correct: true },
      { text: "Great — sarcasm is solved", whyWrong: "The judge is least reliable exactly where the gain appears." },
      { text: "Overall κ 0.70 means all slices are reliable", whyWrong: "Aggregates hide slice failures." },
      { text: "Retrain the generator on judge scores", whyWrong: "That optimizes the judge's biases." },
    ],
    hint: "Where is the instrument unreliable?",
    explanation: "Per-slice validation matters: trust the judge only where it agrees with humans.",
  },
  related: ["inter-annotator-agreement", "grounding", "hallucination"],
  terms: ["llm-as-judge", "position-bias", "verbosity-bias", "self-preference-bias", "cohens-kappa"],
};
