import type { Lesson } from "../../types";

export const modelSelection: Lesson = {
  slug: "model-selection",
  module: "llm",
  order: 8,
  title: "Model Selection",
  tagline: "Quality, cost, latency, context, reliability — pick the model that satisfies the constraints, then optimize.",
  difficulty: "Advanced",
  minutes: 35,
  stages: ["classification", "decision"],
  why: `“Use the best model” is not an engineering decision. The best model for a 1-second live agent-assist budget is not the best model for a nightly batch of 3 million calls, and neither is the right one when a regulator forbids sending data outside the bank.

Model selection is constrained optimization: first eliminate models that violate hard constraints (latency, context, data residency, quality floor), then optimize the objective (cost or quality) among what's left — using numbers measured on *your* data.`,
  concepts: [
    {
      title: "The dimensions that matter",
      intuition: `- **Quality** on your gold set (not a public leaderboard).
- **Cost** per call = input tokens × input price + output tokens × output price.
- **[[Latency|latency]]**: p50 and especially p95.
- **Context length**: does your longest call + prompt fit?
- **Reliability**: valid structured output rate, uptime, rate limits.
- **Deployment**: external API vs on-prem (data residency).`,
      technical: `Cost per month = N_calls × (T_in·p_in + T_out·p_out) for API models, or fixed infrastructure cost for self-hosting (plus ops). Latency ≈ queueing + prefill (∝ input tokens) + decode (∝ output tokens / tokens-per-second). [[Throughput|throughput]] vs latency: batching raises throughput and per-request latency. Measure quality as macro-F1 on a stratified gold set with CIs; compare models with paired tests.`,
      example: `Nightly batch, 3M calls × 2,500 in / 80 out tokens: a $15/$60 model costs ≈ $127k/month; a $2.5/$10 model ≈ $21k. If both clear the quality floor, the objective picks the cheaper one.`,
    },
    {
      title: "Dense vs mixture-of-experts, big vs small",
      intuition: `A **[[dense model|dense-model]]** uses all its parameters for every token. A **[[mixture-of-experts|moe]]** model has many “expert” blocks but routes each token through only a few, so it can be large in knowledge but cheaper per token to run. Small models are fast and cheap; large ones handle hard cases better.`,
      technical: `MoE: a router selects k of N expert feed-forward networks per token; active parameters ≪ total parameters, reducing FLOPs per token, while memory must still hold all experts. Serving efficiency depends on batching and expert load balance. Model size is not a direct proxy for task quality — distillation, instruction tuning and domain fit matter; benchmark on your data.`,
      example: `A common pattern: a small model handles clear calls; low-confidence or ambiguous calls route to a large model; a sample goes to humans. You pay large-model prices only where they buy accuracy.`,
    },
  ],
  questions: {
    what: "Choosing which model(s) serve each workload given quality, cost, latency, context, reliability and deployment constraints.",
    why: "No model is best on every dimension; workloads have different constraints.",
    problem: "It avoids overpaying, missing latency budgets, or violating data policies while meeting quality needs.",
    how: "Define constraints and objective; benchmark candidates on your gold set (quality, validity, latency, tokens); eliminate infeasible; optimize; consider routing.",
    onRealData: "Hinglish tokenization changes cost per call across providers; noisy calls may need larger models; long disputed calls need long context.",
    whatCanGoWrong: "Choosing by leaderboard; ignoring p95 latency; ignoring token-count differences between tokenizers; forgetting rate limits; silent model updates.",
    howToEvaluate: "Per-model: macro-F1 with CIs, JSON validity rate, p50/p95 latency, tokens and cost per call — all on the same stratified sample.",
    whenToUse: "At design time and whenever prices, models or workloads change.",
    whenNotToUse: "Don't switch models on a single anecdotal failure; measure on the gold set.",
    downstream: "Model choice fixes cost per decision, latency budget, need for routing/verification and data governance.",
  },
  lab: {
    id: "model-selection",
    title: "Model-selection simulator",
    intro: "Five fictional models, four workloads with hard constraints. Choose a model and justify it; then see monthly cost, feasibility against each constraint and the reasoning. Also explore latency vs throughput under batching.",
    modes: ["precomputed", "computed", "simulated"],
  },
  realWorld: {
    text: `A team used their strongest model for everything: live assist, nightly analytics and disputes. Live assist missed its 1-second budget 30% of the time, and the analytics bill was 6× forecast. They split by workload: a small fast model for assist (with a narrower task), a mid-size MoE model for batch (quality floor met, 80% cheaper), and the strongest long-context model only for the few hundred monthly disputes.`,
  },
  mistakes: [
    { mistake: "Choosing by public leaderboards", why: "Leaderboards don't measure Hinglish call transcripts with your labels.", fix: "Benchmark on your stratified gold set." },
    { mistake: "Ignoring p95 latency", why: "Averages hide the slow tail users experience.", fix: "Set budgets on p95/p99." },
    { mistake: "Comparing price per token across providers", why: "Tokenizers differ; tokens per call differ.", fix: "Compare cost per call (or per decision) on real transcripts." },
    { mistake: "One model for every workload", why: "Constraints differ radically across workloads.", fix: "Select per workload; consider routing." },
  ],
  decision: {
    question: "How do you pick a model for a workload?",
    useWhen: ["Eliminate by hard constraints (latency, context, residency, quality floor)", "Then optimize the stated objective", "Consider routing when difficulty varies across inputs"],
    avoidWhen: ["Optimizing quality when the objective is cost (or vice versa) without saying so"],
    tradeoffs: [
      { a: "Accuracy", b: "Cost", note: "Is +3 points worth 5× cost? Express it in business value per call." },
      { a: "Accuracy", b: "Latency", note: "Real-time workloads trade quality for speed; batch doesn't have to." },
      { a: "External API", b: "Self-hosted", note: "Self-hosting gives control and residency but adds ops cost and usually lower quality per dollar." },
    ],
  },
  exercises: [
    {
      id: "ms-ex-1",
      kind: "numeric",
      exType: "applied",
      difficulty: "Intermediate",
      concept: "model-tradeoffs",
      prompt: "300,000 calls/month, 2,000 input + 100 output tokens per call. Price: $2.50 per 1M input, $10 per 1M output. Monthly cost in dollars?",
      answer: 1800,
      tolerance: 1,
      unit: "$",
      hint: "300k × (2000×2.5 + 100×10) / 1e6.",
      explanation: "Per call: (5,000 + 1,000)/1e6 = $0.006. × 300,000 = **$1,800**.",
    },
    {
      id: "ms-ex-2",
      kind: "mcq",
      exType: "conceptual",
      difficulty: "Intermediate",
      concept: "moe",
      prompt: "Why can a mixture-of-experts model be cheaper per token than a dense model of similar total size?",
      options: [
        { text: "Only a few experts run per token, so compute per token is much lower", correct: true },
        { text: "It has fewer total parameters", whyWrong: "Total parameters can be larger; active parameters are fewer." },
        { text: "It doesn't need memory for inactive experts", whyWrong: "All experts must still be loaded." },
        { text: "It uses a smaller vocabulary", whyWrong: "Unrelated." },
      ],
      hint: "Active vs total parameters.",
      explanation: "Sparse activation lowers FLOPs per token; memory footprint stays large.",
    },
    {
      id: "ms-ex-3",
      kind: "text",
      exType: "engineering",
      difficulty: "Advanced",
      concept: "model-tradeoffs",
      prompt: "Propose a model strategy for: live agent assist (p95 < 1 s) + nightly intent analytics (3M calls, macro-F1 ≥ 0.85) + monthly disputes (300 long calls, max accuracy).",
      rubric: [
        { idea: "Different models per workload", keywords: ["per workload", "different model", "separate", "each workload"] },
        { idea: "Small/fast model for live assist due to latency", keywords: ["small", "fast", "latency", "p95"] },
        { idea: "Cheapest model meeting the quality floor for batch", keywords: ["cheapest", "cost", "floor", "0.85", "batch"] },
        { idea: "Strongest long-context model for disputes", keywords: ["long context", "strongest", "largest", "dispute", "accuracy"] },
        { idea: "Benchmark on own gold set / route hard cases", keywords: ["gold", "benchmark", "route", "measure"] },
      ],
      minIdeas: 3,
      hint: "Constraints differ per workload.",
      modelAnswer:
        "Assist: a small, fast model with a narrow task (p95 budget first). Batch: benchmark candidates on the gold set, keep those with macro-F1 ≥ 0.85 (with CI), pick the cheapest per call — optionally route low-confidence calls to a larger model. Disputes: the most accurate model whose context fits ~45k tokens; cost is irrelevant at 300 calls. Pin versions and re-benchmark on changes.",
      explanation: "Per-workload constraints → per-workload choices.",
    },
  ],
  quiz: [
    {
      id: "ms-q-1",
      kind: "mcq",
      difficulty: "Beginner",
      concept: "model-tradeoffs",
      prompt: "The first step in model selection should be…",
      options: [
        { text: "Eliminate models that violate hard constraints", correct: true },
        { text: "Pick the highest leaderboard score", whyWrong: "Leaderboards don't reflect your constraints or data." },
        { text: "Pick the cheapest", whyWrong: "Might fail the quality floor." },
        { text: "Pick the newest", whyWrong: "Newest ≠ fit for purpose." },
      ],
      hint: "Feasibility before optimization.",
      explanation: "Constraints define the feasible set; then optimize.",
    },
    {
      id: "ms-q-2",
      kind: "mcq",
      difficulty: "Intermediate",
      concept: "model-tradeoffs",
      prompt: "For real-time agent assist, which latency metric matters most?",
      options: [
        { text: "p95/p99 latency", correct: true },
        { text: "Mean latency", whyWrong: "Hides the slow tail users experience." },
        { text: "Batch throughput", whyWrong: "Throughput is for offline jobs." },
        { text: "Time to train", whyWrong: "Irrelevant." },
      ],
      hint: "What do users feel on bad requests?",
      explanation: "Tail latency determines whether suggestions arrive in time.",
    },
    {
      id: "ms-q-3",
      kind: "mcq",
      difficulty: "Intermediate",
      concept: "model-tradeoffs",
      prompt: "Provider A is cheaper per token than B, but A's tokenizer produces 1.6× more tokens on your Hinglish calls. To compare cost you should…",
      options: [
        { text: "Compare cost per call using each provider's token counts on real transcripts", correct: true },
        { text: "Compare price per token", whyWrong: "Ignores tokenization differences." },
        { text: "Assume they're equal", whyWrong: "They're not." },
        { text: "Use word counts", whyWrong: "Words aren't billed." },
      ],
      hint: "Cost = tokens × price.",
      explanation: "Per-call cost is the comparable unit.",
    },
    {
      id: "ms-q-4",
      kind: "mcq",
      difficulty: "Intermediate",
      concept: "moe",
      prompt: "Batching more requests on a GPU server typically…",
      options: [
        { text: "Increases throughput and per-request latency", correct: true },
        { text: "Decreases both", whyWrong: "Latency rises as requests wait for the batch." },
        { text: "Increases latency only", whyWrong: "Throughput rises too." },
        { text: "Has no effect", whyWrong: "It's the main throughput lever." },
      ],
      hint: "Amortizing weights over more requests.",
      explanation: "Throughput ↑, latency ↑ — good for batch, bad for real-time.",
    },
    {
      id: "ms-q-5",
      kind: "mcq",
      difficulty: "Advanced",
      concept: "model-tradeoffs",
      prompt: "Model X: macro-F1 0.86 [0.82, 0.90], $5/1k calls. Model Y: 0.88 [0.84, 0.92], $25/1k. Quality floor 0.85, objective = cost. Choose:",
      options: [
        { text: "X — it meets the floor (point estimate; check the lower bound risk) and is 5× cheaper", correct: true },
        { text: "Y — higher F1", whyWrong: "The objective is cost, and the CIs overlap heavily." },
        { text: "Neither", whyWrong: "X meets the floor." },
        { text: "Both, randomly", whyWrong: "No." },
      ],
      hint: "Objective is cost; the difference isn't clearly significant.",
      explanation: "Overlapping CIs + cost objective → X, while monitoring whether its lower bound risks the floor.",
    },
  ],
  challenge: {
    id: "ms-ch-1",
    kind: "numeric",
    exType: "applied",
    difficulty: "Expert",
    concept: "model-tradeoffs",
    prompt: "Routing: 80% of calls go to a small model ($0.4/1k calls), 20% to a large model ($12/1k calls). What is the blended cost per 1k calls?",
    answer: 2.72,
    tolerance: 0.01,
    unit: "$",
    hint: "Weighted average.",
    explanation: "0.8 × 0.4 + 0.2 × 12 = 0.32 + 2.40 = **$2.72** per 1k — 4.4× cheaper than all-large, if routing preserves quality (measure it!).",
  },
  related: ["caching-batching", "pipeline-design", "significance"],
  terms: ["moe", "dense-model", "latency", "throughput", "ttft"],
};
