import type { Lesson } from "../../types";

export const pipelineDesign: Lesson = {
  slug: "pipeline-design",
  module: "llm",
  order: 10,
  title: "Multi-stage Pipeline Design",
  tagline: "Sequential, parallel, routed: decomposition buys debuggability — and costs latency, money and compounding errors.",
  difficulty: "Advanced",
  minutes: 40,
  stages: ["normalization", "speaker", "ner", "classification", "evidence", "verification", "decision"],
  why: `One giant prompt that does everything is simple to build and impossible to debug. A **[[pipeline]]** of focused stages — normalize, extract, classify, collect evidence, verify — lets you measure and improve each part separately.

But every stage adds latency and cost, and errors compound: five stages at 95% each are ≈77% end-to-end if errors are independent (and correlated errors on noisy calls make it worse). Good pipeline design uses **parallelism** for independent stages, **[[routing|router]]** to spend effort where it matters, and **verification** to catch errors before decisions.`,
  concepts: [
    {
      title: "Sequential, parallel and routed topologies",
      intuition: `- **Sequential** (A → B → C → D): each step uses the previous result. Simple, but latency adds up.
- **Parallel** (A → {B, C, E} → D): independent steps run at the same time; latency is set by the slowest branch.
- **Routing** (Input → Router → Simple / Complex / Ambiguous): cheap path for easy cases, expensive path or humans for hard ones.`,
      technical: `Model the pipeline as a DAG. End-to-end latency = critical path length (longest path by stage latencies); cost = Σ stage cost × probability the stage runs. Accuracy under independence ≈ Π stage accuracies along the path, adjusted by verification (which can catch a fraction of upstream errors) and routing (which changes the mix). Real errors correlate with input difficulty (noise, Hinglish), so measure end-to-end on slices rather than trusting products.`,
      example: `NER, classification and evidence extraction all read the same normalized transcript and don't depend on each other → run them in parallel, then verify. Same cost as sequential, ~35% lower latency with the lab's default stage timings (2.2 s vs 3.4 s).`,
    },
    {
      title: "Decomposition and error propagation",
      intuition: `Splitting a task makes each piece easier and measurable — but each handoff is a place for errors to enter and travel downstream. Decompose where it buys you measurability or accuracy; don't add stages because it “feels” more rigorous.`,
      technical: `Decomposition helps when sub-tasks have distinct skills or evaluation criteria, when intermediate outputs are reusable (entities used by several consumers), or when a cheap deterministic step can replace an LLM step. It hurts when stages depend on context the previous stage discarded, when the extra calls add more error than they remove, or when latency budgets are tight. Verification stages catch errors but share blind spots with generators (correlated errors).`,
      example: `A "speaker attribution" stage at 95% feeding an intent stage at 90% gives ~86% even before other stages. Improving speaker attribution to 99% raises the ceiling for everything downstream — the per-stage lesson shows how to find such bottlenecks.`,
    },
  ],
  questions: {
    what: "Designing a system as a graph of components (code, models, LLM calls, humans) with explicit inputs/outputs.",
    why: "Complex tasks mix skills; one monolithic call is hard to debug, evaluate and optimize.",
    problem: "It enables per-stage evaluation, targeted fixes, parallelism, routing and cost control.",
    how: "Define stage contracts (schemas), wire a DAG, parallelize independent stages, route by difficulty/confidence, verify before decisions, log everything.",
    onRealData: "Noisy calls fail several stages at once (correlated errors); most calls are easy and could use a cheap path.",
    whatCanGoWrong: "Latency explosion from long sequential chains, compounding errors, stages that discard needed context, routers that misroute, verifiers that rubber-stamp.",
    howToEvaluate: "Per-stage metrics on gold stage outputs, end-to-end metrics by slice, latency p50/p95, cost per decision, review rates.",
    whenToUse: "When sub-tasks are separable and measurable, or when routing can save cost on easy inputs.",
    whenNotToUse: "When a single well-grounded call meets requirements; when the latency budget can't absorb extra stages.",
    downstream: "Topology determines where errors enter, how fast decisions are made, and how much each decision costs.",
  },
  lab: {
    id: "pipeline-design",
    title: "Architecture builder",
    intro: "Load sequential, parallel and routing presets or wire your own pipeline on a canvas. 2,000 simulated transcripts flow through it to estimate end-to-end accuracy, errors caught, p50/p95 latency, cost and LLM calls per transcript.",
    modes: ["simulated"],
  },
  realWorld: {
    text: `A seven-stage pipeline (each stage an LLM call) hit 11 seconds p95 and $9 per 1k calls. Analysis showed three stages were independent (NER, objections, evidence) and one (normalization) could be deterministic code. After parallelizing and replacing the LLM normalizer, p95 fell to 4 seconds and cost to $5.40 — with identical accuracy. Adding a router that sent clean, short calls to a small model cut cost further to $3.10 with a 0.4-point macro-F1 loss, which the business accepted.`,
  },
  mistakes: [
    { mistake: "Chaining LLM calls that could run in parallel", why: "Latency adds up for no benefit.", fix: "Identify independent stages; run them concurrently." },
    { mistake: "Using an LLM where code suffices", why: "Adds cost, latency and variance.", fix: "Deterministic steps (number parsing, schema checks) in code." },
    { mistake: "Trusting products of stage accuracies", why: "Errors correlate with hard inputs.", fix: "Measure end-to-end on slices." },
    { mistake: "Unvalidated routers", why: "Misrouted hard cases get cheap, wrong answers.", fix: "Evaluate the router like any classifier; monitor per-route quality." },
  ],
  decision: {
    question: "Single call or multi-stage pipeline?",
    useWhen: ["You need per-stage measurability (speaker, entities, intent, evidence)", "Some sub-steps are deterministic or reusable", "Input difficulty varies enough to justify routing"],
    avoidWhen: ["A single grounded call meets quality and latency targets", "Extra stages can't be evaluated on their own gold labels"],
    tradeoffs: [
      { a: "More LLM calls", b: "Better decomposition", note: "Each call costs money and latency; add stages that measurably fix errors." },
      { a: "Single model", b: "Multi-stage pipeline", note: "Simplicity vs debuggability and targeted optimization." },
      { a: "Sequential", b: "Parallel", note: "Parallel cuts latency at equal cost when stages are independent." },
    ],
  },
  exercises: [
    {
      id: "pd-ex-1",
      kind: "numeric",
      exType: "applied",
      difficulty: "Intermediate",
      concept: "error-compounding",
      prompt: "Four sequential stages with accuracies 0.98, 0.95, 0.92, 0.96. Assuming independent errors and no recovery, what is the end-to-end accuracy? (3 decimals)",
      answer: 0.822,
      tolerance: 0.002,
      hint: "Multiply.",
      explanation: "0.98 × 0.95 × 0.92 × 0.96 ≈ **0.822**. Four good stages lose ~18% of transcripts.",
    },
    {
      id: "pd-ex-2",
      kind: "numeric",
      exType: "applied",
      difficulty: "Intermediate",
      concept: "pipeline-latency",
      prompt: "Stages: normalize 20 ms → speaker 150 ms → {NER 400 ms, classify 900 ms, evidence 800 ms in parallel} → verify 1,100 ms. End-to-end latency in ms?",
      answer: 2170,
      tolerance: 0,
      unit: "ms",
      hint: "Critical path: the slowest parallel branch counts.",
      explanation: "20 + 150 + max(400, 900, 800) + 1,100 = **2,170 ms** (sequential would be 3,370 ms).",
    },
    {
      id: "pd-ex-3",
      kind: "text",
      exType: "engineering",
      difficulty: "Advanced",
      concept: "routing",
      prompt: "Design a routing strategy for intent classification where 70% of calls are short and clean, 25% noisy, 5% extremely ambiguous.",
      rubric: [
        { idea: "Cheap/small model for easy calls", keywords: ["small", "cheap", "easy", "clean"] },
        { idea: "Stronger model and/or verification for noisy calls", keywords: ["large", "strong", "verification", "noisy"] },
        { idea: "Human review for ambiguous / low confidence", keywords: ["human", "review", "ambiguous", "low confidence"] },
        { idea: "Router signals (quality score, length, confidence)", keywords: ["asr confidence", "quality", "length", "confidence", "signal"] },
        { idea: "Evaluate the router and per-route quality", keywords: ["evaluate", "misroute", "per-route", "monitor", "measure"] },
      ],
      minIdeas: 3,
      hint: "Spend effort where difficulty is.",
      modelAnswer:
        "Route by cheap signals: ASR confidence/WER proxy, transcript length, language mix, and a first-pass small-model confidence. Clean/short → small model. Noisy → larger model + evidence verification. Low confidence or verifier disagreement → human review queue. Evaluate the router's misroute rate and quality per route on a stratified gold set; watch that the cheap route's error rate stays within budget.",
      explanation: "Routing is a classifier; treat it with the same evaluation discipline.",
    },
    {
      id: "pd-ex-4",
      kind: "mcq",
      exType: "conceptual",
      difficulty: "Intermediate",
      concept: "error-compounding",
      prompt: "When does adding a pipeline stage make the system WORSE end to end?",
      options: [
        { text: "When the errors it introduces (and propagates) outweigh the errors it fixes", correct: true },
        { text: "Never — more stages are always more rigorous", whyWrong: "Every stage is a new source of error, latency and cost." },
        { text: "Only if the stage uses an LLM", whyWrong: "Code stages can also introduce errors (e.g., bad normalization)." },
        { text: "Only when latency increases", whyWrong: "Accuracy can drop independently of latency." },
      ],
      hint: "Net effect.",
      explanation: "A stage earns its place only if it fixes more than it breaks — measure it with a with/without comparison.",
    },
  ],
  quiz: [
    {
      id: "pd-q-1",
      kind: "mcq",
      difficulty: "Beginner",
      concept: "pipeline-latency",
      prompt: "In a DAG pipeline, end-to-end latency is determined by…",
      options: [
        { text: "The critical (longest) path", correct: true },
        { text: "The sum of all stage latencies", whyWrong: "Only if everything is sequential." },
        { text: "The fastest stage", whyWrong: "No." },
        { text: "The number of stages", whyWrong: "Not directly." },
      ],
      hint: "Parallel branches overlap.",
      explanation: "Parallel stages overlap; the slowest chain sets latency.",
    },
    {
      id: "pd-q-2",
      kind: "mcq",
      difficulty: "Intermediate",
      concept: "error-compounding",
      prompt: "Why is Π(stage accuracies) often optimistic for real transcripts?",
      options: [
        { text: "Errors are correlated: noisy calls fail several stages at once", correct: true },
        { text: "Multiplication overestimates small numbers", whyWrong: "Math is fine; the independence assumption is wrong." },
        { text: "Stages can't fail", whyWrong: "They can." },
        { text: "Verification always fixes errors", whyWrong: "Verifiers catch only some errors." },
      ],
      hint: "Independence assumption.",
      explanation: "Hard inputs are hard for every stage.",
    },
    {
      id: "pd-q-3",
      kind: "mcq",
      difficulty: "Intermediate",
      concept: "routing",
      prompt: "The main purpose of a router is to…",
      options: [
        { text: "Send each input to the cheapest path that handles it well", correct: true },
        { text: "Make every call use the largest model", whyWrong: "The opposite." },
        { text: "Replace evaluation", whyWrong: "Routers need evaluation." },
        { text: "Parallelize stages", whyWrong: "Different concept." },
      ],
      hint: "Difficulty varies.",
      explanation: "Match effort to difficulty.",
    },
    {
      id: "pd-q-4",
      kind: "mcq",
      difficulty: "Intermediate",
      concept: "pipeline-latency",
      prompt: "Which stage is the best candidate to replace an LLM call with code?",
      options: [
        { text: "Converting '5 lakh' / 'five lac' to 500000", correct: true },
        { text: "Detecting sarcasm", whyWrong: "Needs judgement." },
        { text: "Judging entailment of a claim", whyWrong: "Needs a model." },
        { text: "Summarizing objections", whyWrong: "Generative." },
      ],
      hint: "Exactly specifiable.",
      explanation: "Deterministic, specifiable transformations belong in code.",
    },
    {
      id: "pd-q-5",
      kind: "mcq",
      difficulty: "Advanced",
      concept: "error-compounding",
      prompt: "Adding a verification stage that catches 50% of upstream errors changes a 0.80-accurate pipeline to roughly…",
      options: [
        { text: "0.90 correct-or-caught (0.80 + 0.5 × 0.20), at extra cost and latency", correct: true },
        { text: "1.00", whyWrong: "It catches only half." },
        { text: "0.40", whyWrong: "It doesn't reduce accuracy." },
        { text: "Unchanged", whyWrong: "Caught errors go to review instead of being wrong decisions." },
      ],
      hint: "Recover half of the 20% errors.",
      explanation: "Verification converts some silent errors into reviewed cases — if its catch rate is real (validate it).",
    },
  ],
  challenge: {
    id: "pd-ch-1",
    kind: "numeric",
    exType: "applied",
    difficulty: "Expert",
    concept: "routing",
    prompt: "Router sends 70% to a path with 0.93 accuracy and 30% to a path with 0.88 accuracy. The router itself misroutes 5% of calls, and misrouted calls are correct only 60% of the time. Expected end-to-end accuracy? (3 decimals)",
    answer: 0.899,
    tolerance: 0.003,
    hint: "95% correctly routed: 0.7×0.93 + 0.3×0.88; 5% misrouted at 0.60.",
    explanation: "Correctly routed accuracy = 0.7×0.93 + 0.3×0.88 = 0.651 + 0.264 = 0.915. Overall = 0.95 × 0.915 + 0.05 × 0.60 = 0.869 + 0.030 ≈ **0.899**.",
  },
  related: ["per-stage-evaluation", "model-selection", "rag-agents"],
  terms: ["pipeline", "router", "error-propagation", "latency"],
};
