import type { Lesson } from "../../types";

export const promptEngineering: Lesson = {
  slug: "prompt-engineering",
  module: "llm",
  order: 1,
  title: "Prompt Engineering",
  tagline: "From “Is this customer interested?” to a specification the model can actually follow.",
  difficulty: "Intermediate",
  minutes: 40,
  stages: ["classification", "evidence"],
  why: `A prompt is a specification. The model will fill every gap you leave with its own assumptions: what counts as “interested”, whether a maybe is a yes, whether the agent's words count, what format to answer in. On noisy transcripts, those assumptions are exactly where the errors live.

Good prompting is not magic phrasing. It is: a clear role, a precise task, explicit label definitions, constraints (including what NOT to do), an output format, evidence requirements and well-chosen examples — then measuring the result on a test set.`,
  concepts: [
    {
      title: "Anatomy of a production prompt",
      intuition: `- **[[System prompt|system-prompt]]**: who the model is and the standing rules.
- **Task instruction**: exactly what to decide.
- **Label definitions & constraints**: what each label means; what to do when unsure; what is NOT evidence.
- **Examples**: a few worked cases, especially the hard boundaries.
- **Output format**: machine-readable, with the exact allowed values.
- **Input**: the transcript — last, so the question is fresh.`,
      technical: `Instruction-tuned LLMs condition on the full context; ambiguity in the prompt becomes variance in outputs. Explicit constraints reduce the hypothesis space; negative instructions (“agent paraphrases are never evidence”) target known failure modes; output schemas enable validation. Put stable content (role, rules, examples) first — it's cacheable — and variable content (transcript) last.`,
      example: `Bad: “Is this customer interested in a loan?” → prose, forced yes/no, cites the agent.
Improved: role + “Classify the CUSTOMER's intent… If the customer does not explicitly commit or refuse, answer insufficient_evidence… Use only customer words as evidence, quoted verbatim… Return only JSON {intent, evidence, reason}”.`,
    },
    {
      title: "Zero-shot, few-shot and in-context learning",
      intuition: `**[[Zero-shot|zero-shot]]**: instructions only. **[[Few-shot|few-shot]]**: instructions plus a handful of solved examples. Examples teach boundaries better than definitions — but they also teach accidents: if all your examples are "interested", the model leans that way.`,
      technical: `[[In-context learning|in-context-learning]] conditions the model on demonstrations without weight updates. Sensitivities: label balance of demos (majority-label bias), recency (last example weighs more), surface similarity (the model copies formats and phrasings), and ordering. Choose demos that cover the hard boundaries (hedges, resolved objections, sarcasm), balance labels, and draw them from a training split — never from your test set.`,
      example: `Adding only a clean English 'interested' example can *worsen* hedge handling (“maybe next month” → interested). Adding a Hinglish hedge → insufficient_evidence example fixes it. Try both in the lab.`,
    },
  ],
  questions: {
    what: "Designing the model's input — instructions, definitions, constraints, examples and output format — so outputs are correct, consistent and parseable.",
    why: "LLMs are general; your task has specific definitions and failure modes the model doesn't know.",
    problem: "It converts an implicit business question into an explicit, testable specification.",
    how: "Iterate: write the spec, run on a dev set, read failures, add targeted constraints/examples, re-measure. Keep a held-out test set untouched.",
    onRealData: "Hinglish hedges (shayad, dekhte hai), leading agent questions, sarcasm, resolved objections and diarization errors are the cases prompts must address explicitly.",
    whatCanGoWrong: "Vague labels, no abstain option, no evidence rules, few-shot label imbalance, prose outputs, prompt bloat, and overfitting prompts to the test set.",
    howToEvaluate: "Label accuracy/macro-F1, format validity, evidence verbatim-and-customer rate — on a dev set while iterating, on a test set once.",
    whenToUse: "Always when using an LLM; invest most in definitions, abstain rules and evidence constraints.",
    whenNotToUse: "Don't try to fix upstream data errors (e.g., diarization) purely by prompting; don't keep adding rules without measuring.",
    downstream: "Prompt quality drives accuracy, parse failures, evidence quality, cost (length) and cacheability.",
  },
  lab: {
    id: "prompt-engineering",
    title: "Prompt playground",
    intro: "Edit the system instruction, task, constraints, output format and few-shot examples. Run on six hard test transcripts and see label accuracy, format validity and evidence quality. Use the simulator, or a real model via the backend.",
    modes: ["simulated", "real-model"],
  },
  realWorld: {
    text: `A first prompt (“classify interest: yes/no”) gave 71% accuracy and a pile of parse errors. Iterations — on a dev set — added: an insufficient_evidence label with a definition (+9 pts), “only customer words are evidence” (+4 pts, and evidence audits became possible), a “final stance” rule for resolved objections (+3 pts), and JSON output with an enum (parse errors 6% → 0.2%). The team froze the prompt, evaluated once on the test set, and versioned the prompt alongside the model name.`,
  },
  mistakes: [
    { mistake: "Vague label names without definitions", why: "The model applies its own notion of 'interested'.", fix: "Define each label with inclusion/exclusion criteria (mirror your annotation guideline)." },
    { mistake: "No permission to abstain", why: "Forced choices turn ambiguity into confident errors.", fix: "Add insufficient_evidence with a definition and 'do not guess'." },
    { mistake: "Few-shot examples that are all easy positives", why: "Demonstrations bias the label distribution and teach nothing about boundaries.", fix: "Use balanced, boundary-focused examples from a training split." },
    { mistake: "Iterating on the test set", why: "The final number is inflated.", fix: "Iterate on dev; touch test once (see Gold Set Design)." },
  ],
  decision: {
    question: "What should go into the prompt vs elsewhere?",
    useWhen: ["Definitions, abstain rules, evidence rules and output format → prompt", "Examples of hard boundaries → few-shot section", "Stable rules → cached system prefix"],
    avoidWhen: ["Deterministic transformations (number parsing) → code, not prompt", "Large reference documents that are rarely relevant → retrieve or omit"],
    tradeoffs: [
      { a: "More instructions", b: "Prompt bloat", note: "Each rule can fix a failure — or conflict with another. Keep rules that measurably help." },
      { a: "Zero-shot", b: "Few-shot", note: "Few-shot teaches boundaries but costs tokens and can bias; choose examples deliberately." },
    ],
  },
  exercises: [
    {
      id: "pe-ex-1",
      kind: "multi",
      exType: "applied",
      difficulty: "Beginner",
      concept: "prompt-specificity",
      prompt: "Bad prompt: “Is this customer interested in a loan?” Which problems does it have? (Select all)",
      options: [
        { text: "No definition of 'interested'", correct: true },
        { text: "No option for insufficient evidence", correct: true },
        { text: "No output format", correct: true },
        { text: "No evidence requirement", correct: true },
        { text: "It is too long", whyWrong: "It's too short — underspecified, not bloated." },
      ],
      hint: "Four of these are missing pieces of a specification.",
      explanation: "The prompt leaves definitions, abstention, format and evidence entirely to the model.",
    },
    {
      id: "pe-ex-2",
      kind: "mcq",
      exType: "conceptual",
      difficulty: "Intermediate",
      concept: "few-shot",
      prompt: "All four of your few-shot examples are clear 'interested' calls. What's the most likely effect?",
      options: [
        { text: "The model over-predicts 'interested' on ambiguous calls", correct: true },
        { text: "Better recall on 'not_interested'", whyWrong: "The examples teach nothing about refusals." },
        { text: "No effect; examples only teach format", whyWrong: "Label distribution of demos influences predictions." },
        { text: "The model refuses to answer", whyWrong: "No." },
      ],
      hint: "Demonstrations carry a label distribution.",
      explanation: "Majority-label bias: models lean toward labels over-represented in demonstrations.",
    },
    {
      id: "pe-ex-3",
      kind: "text",
      exType: "engineering",
      difficulty: "Advanced",
      concept: "prompt-specificity",
      prompt: "Write the Rules section of a prompt for intent classification on Hinglish sales calls. Aim for 4–6 rules.",
      rubric: [
        { idea: "Only customer words count as evidence", keywords: ["customer", "agent", "only"] },
        { idea: "Abstain when not explicit (insufficient_evidence, don't guess)", keywords: ["insufficient", "don't guess", "do not guess", "not explicit"] },
        { idea: "Quote evidence verbatim", keywords: ["verbatim", "exact", "quote"] },
        { idea: "Judge the final stance / resolved objections", keywords: ["final", "resolved", "later", "last"] },
        { idea: "Handle sarcasm / hedges / Hinglish", keywords: ["sarcas", "hedge", "maybe", "shayad", "hinglish"] },
      ],
      minIdeas: 4,
      hint: "Target the failure modes you saw in the lab.",
      modelAnswer:
        "- Use only words spoken by the Customer as evidence; agent questions or paraphrases are never evidence.\n- Quote evidence verbatim from the transcript.\n- If the customer neither commits nor refuses, answer insufficient_evidence — do not guess.\n- Judge the customer's final stance: an objection later resolved is not a refusal.\n- Hedges (shayad, dekhte hai, maybe later) are not commitments.\n- Praise followed by refusal is sarcasm → refusal.",
      explanation: "Each rule targets a measured failure mode; together they make outputs auditable.",
    },
  ],
  quiz: [
    {
      id: "pe-q-1",
      kind: "mcq",
      difficulty: "Beginner",
      concept: "few-shot",
      prompt: "Few-shot prompting means…",
      options: [
        { text: "Including a few worked input→output examples in the prompt", correct: true },
        { text: "Calling the model a few times and voting", whyWrong: "That's self-consistency/ensembling." },
        { text: "Fine-tuning on a few examples", whyWrong: "Few-shot prompting doesn't update weights." },
        { text: "Using a small model", whyWrong: "Unrelated." },
      ],
      hint: "It's about the prompt contents.",
      explanation: "Demonstrations in context = in-context learning.",
    },
    {
      id: "pe-q-2",
      kind: "mcq",
      difficulty: "Intermediate",
      concept: "prompt-specificity",
      prompt: "Which instruction best targets the 'agent put words in the customer's mouth' failure?",
      options: [
        { text: "“Agent questions or paraphrases are never evidence of the customer's intent.”", correct: true },
        { text: "“Be accurate.”", whyWrong: "Vague; doesn't target the failure." },
        { text: "“Think step by step.”", whyWrong: "Doesn't specify what counts as evidence." },
        { text: "“Use JSON.”", whyWrong: "Format, not evidence." },
      ],
      hint: "Negative instructions should name the failure.",
      explanation: "Specific negative instructions address specific failure modes.",
    },
    {
      id: "pe-q-3",
      kind: "mcq",
      difficulty: "Intermediate",
      concept: "prompt-specificity",
      prompt: "Why put the static rulebook before the transcript?",
      options: [
        { text: "It forms a stable, cacheable prefix, and the transcript + question stay near the end", correct: true },
        { text: "Models ignore the end of prompts", whyWrong: "The end is typically well attended." },
        { text: "It reduces output tokens", whyWrong: "Input order doesn't change output length much." },
        { text: "It's required by the API", whyWrong: "No such requirement." },
      ],
      hint: "Think caching and recency.",
      explanation: "Static-first enables prefix caching; variable content goes last.",
    },
    {
      id: "pe-q-4",
      kind: "mcq",
      difficulty: "Intermediate",
      concept: "prompt-specificity",
      prompt: "Your improved prompt still cites the agent's leading question on a call with a diarization error. The best next step is…",
      options: [
        { text: "Fix/verify speaker attribution upstream; prompts can't see mislabelled speakers", correct: true },
        { text: "Add more rules until it works", whyWrong: "The input itself says the customer said it." },
        { text: "Raise the temperature", whyWrong: "Unrelated." },
        { text: "Remove the evidence requirement", whyWrong: "That hides the problem." },
      ],
      hint: "Where does the error originate?",
      explanation: "Some errors must be fixed upstream; the evidence check helpfully exposed it.",
    },
    {
      id: "pe-q-5",
      kind: "mcq",
      difficulty: "Advanced",
      concept: "few-shot",
      prompt: "Where should few-shot examples come from?",
      options: [
        { text: "A training split, never the dev or test set", correct: true },
        { text: "The test set — they're the most representative", whyWrong: "That leaks test data and inflates results." },
        { text: "Randomly from production without labels", whyWrong: "Examples need correct outputs." },
        { text: "The model's own outputs", whyWrong: "Unverified outputs teach errors." },
      ],
      hint: "Avoid leakage.",
      explanation: "Examples from the test set are leakage.",
    },
  ],
  challenge: {
    id: "pe-ch-1",
    kind: "mcq",
    exType: "engineering",
    difficulty: "Expert",
    concept: "prompt-specificity",
    prompt: "Adding the rule “hedges are not commitments” raised dev accuracy from 84% to 86% (n = 150). What should you conclude?",
    options: [
      { text: "Promising but not conclusive: a 2-point gain on 150 examples is within noise; check per-slice effects and use a paired test", correct: true },
      { text: "Ship it: +2 points is a clear win", whyWrong: "On 150 examples the 95% CI of the difference is several points wide." },
      { text: "The rule is harmful", whyWrong: "Nothing indicates harm." },
      { text: "Evaluate it on the test set until it improves", whyWrong: "That's test-set overfitting." },
    ],
    hint: "What's the standard error of a proportion at n = 150?",
    explanation: "SE ≈ √(0.85·0.15/150) ≈ 2.9 pts per estimate. Use a paired comparison (McNemar on discordant calls) and look at the hedge slice specifically.",
  },
  related: ["structured-output", "grounding", "gold-set-design"],
  terms: ["system-prompt", "zero-shot", "few-shot", "in-context-learning", "prompt-bloat"],
};
