import type { Lesson } from "../../types";

export const ragAgents: Lesson = {
  slug: "rag-agents",
  module: "llm",
  order: 11,
  title: "RAG and Agents: Do You Need Them?",
  tagline: "Most transcript-analysis problems need neither. Know when they help — and when a deterministic pipeline wins.",
  difficulty: "Intermediate",
  minutes: 25,
  stages: ["classification", "decision"],
  why: `**[[RAG|rag]]** and **[[agents|agent]]** are powerful patterns, and they're heavily marketed. But intent classification, entity extraction and evidence selection all operate on information that's *already in the transcript*. Retrieval adds a component that can miss; agents add nondeterministic control flow that's hard to test, bound and audit.

This lesson is deliberately short. The goal is one skill: answering “do I actually need RAG or an agent for this?” — and usually answering *no*, for good reasons.`,
  concepts: [
    {
      title: "When RAG helps",
      intuition: `RAG = look things up, then answer. You need it only when the answer depends on knowledge that isn't in the input and is too big or too changeable to put in the prompt. If the knowledge is a table with exact keys, don't use similarity search — use a database query.`,
      technical: `Retrieval-augmented generation: a retriever (BM25, dense embeddings, hybrid) selects top-k passages from a corpus; they're injected into the context for generation. Two error sources: retrieval misses (recall@k) and generation errors given retrieved text. Evaluate them separately. Alternatives: include small, stable knowledge directly (cached prefix); use structured lookup (SQL/key-value) for tabular facts; use segment selection for long transcripts (retrieval within the call).`,
      example: `“Did the agent quote the correct rate for this product and segment?” → extract (product, segment, quoted rate) then look up the rate table by key. No vectors. “Answer agent questions about 400 pages of changing policy” → RAG.`,
    },
    {
      title: "When agents help",
      intuition: `An agent decides its own next step, calls tools and loops. That's useful when you genuinely can't write the flowchart in advance. If you can draw the steps, build the steps — a fixed pipeline is cheaper, faster, testable and auditable.`,
      technical: `Agents are control loops: the model chooses actions (tool calls), observes results, and repeats until done. Risks: unbounded loops and cost, wrong actions with side effects, nondeterministic trajectories that are hard to evaluate. If needed: read-only tools first, step/time/cost limits, explicit permissions, trajectory logging, and evaluation on task success rate and harmful-action rate. Often a router or a single function call covers the "dynamic" need.`,
      example: `“Classify the call, extract entities, verify evidence” — fixed sequence → pipeline. “Investigate why an application stalled across CRM, call archive and loan system, where each lookup decides the next” → agent (bounded).`,
    },
  ],
  questions: {
    what: "RAG injects retrieved external knowledge into prompts; agents let a model choose actions/tool calls in a loop.",
    why: "Some tasks need knowledge beyond the input or dynamic multi-step tool use.",
    problem: "RAG handles large/changing knowledge; agents handle open-ended procedures.",
    how: "RAG: index → retrieve top-k → generate with citations. Agents: model ↔ tools loop with limits.",
    onRealData: "Transcript intent/extraction tasks rarely need external knowledge; rate/policy checks usually need exact lookups, not semantic retrieval.",
    whatCanGoWrong: "Retrieval misses look like hallucinations; irrelevant retrieved text distracts; agents loop, overspend or take wrong actions; both are harder to evaluate.",
    howToEvaluate: "RAG: retrieval recall@k and answer faithfulness separately. Agents: task success, steps, cost, harmful-action rate on trajectory test sets.",
    whenToUse: "RAG: large, unstructured, changing knowledge. Agents: tool-dependent, non-enumerable procedures with bounded risk.",
    whenNotToUse: "When everything needed is in the transcript; when knowledge is small/stable (put it in the prompt) or structured (query it); when steps are known (pipeline).",
    downstream: "Unneeded RAG/agents add latency, cost, failure modes and evaluation burden to every decision.",
  },
  lab: {
    id: "rag-agents",
    title: "Do I need RAG or an agent?",
    intro: "Seven realistic scenarios: pick the simplest architecture that works (deterministic code, a single call/fixed pipeline, RAG, or an agent) and read why. Then walk the RAG and agent decision trees.",
    modes: ["precomputed"],
  },
  realWorld: {
    text: `A team built a RAG system over 2,000 past transcripts to “help classify intent”. Retrieval surfaced similar calls; the model then sometimes copied *their* outcomes. Accuracy dropped 3 points versus classifying the transcript alone, latency doubled, and the vector index needed maintenance. Removing RAG and adding four carefully chosen few-shot examples beat the RAG system on every metric.`,
  },
  mistakes: [
    { mistake: "Adding RAG because the task involves 'documents'", why: "The transcript already contains the evidence.", fix: "Ask: is the needed knowledge outside the input? If not, no RAG." },
    { mistake: "Vector search over structured tables", why: "Similarity isn't exact lookup; you get 'close' wrong rows.", fix: "Extract keys and query the table." },
    { mistake: "Agents for fixed workflows", why: "Nondeterminism without benefit.", fix: "Build the known sequence as a pipeline or router." },
  ],
  decision: {
    question: "Does this transcript problem need RAG or an agent?",
    useWhen: ["RAG: answers depend on large, unstructured, changing external knowledge", "Agent: next steps depend on tool results in ways you can't enumerate — with limits and audits"],
    avoidWhen: ["The transcript contains everything needed", "Knowledge is small and stable (prompt it) or structured (query it)", "The procedure is known (pipeline)"],
    tradeoffs: [
      { a: "RAG", b: "Prompt context", note: "RAG scales to big corpora but can miss; prompt context never misses but costs tokens on every call." },
      { a: "Agent", b: "Deterministic pipeline", note: "Agents handle open-ended tasks; pipelines are cheaper, testable and auditable." },
    ],
  },
  exercises: [
    {
      id: "ra-ex-1",
      kind: "mcq",
      exType: "applied",
      difficulty: "Beginner",
      concept: "rag-overuse",
      prompt: "Task: classify each call's intent from its transcript. Do you need RAG?",
      options: [
        { text: "No — the evidence is in the transcript", correct: true },
        { text: "Yes — to retrieve similar past calls", whyWrong: "Similar calls' labels can bias the answer; use curated few-shot examples instead." },
        { text: "Yes — RAG always improves accuracy", whyWrong: "It adds a failure mode and distraction." },
        { text: "Only for Hinglish calls", whyWrong: "Language doesn't create a knowledge gap." },
      ],
      hint: "Where does the needed information live?",
      explanation: "No external knowledge gap → no retrieval.",
    },
    {
      id: "ra-ex-2",
      kind: "mcq",
      exType: "applied",
      difficulty: "Intermediate",
      concept: "rag-overuse",
      prompt: "Check whether the agent quoted the current rate. Rates live in a table keyed by product and segment, updated weekly. Best approach?",
      options: [
        { text: "Extract product, segment and quoted rate; look up the table deterministically", correct: true },
        { text: "Embed the rate table and retrieve the most similar row", whyWrong: "Similarity search can return a close but wrong row." },
        { text: "Build an agent to browse the rate portal", whyWrong: "Overkill; a query suffices." },
        { text: "Put all historical rate tables in the prompt", whyWrong: "Bloat; the current table is a lookup." },
      ],
      hint: "Structured data with exact keys.",
      explanation: "Exact keys → exact lookup.",
    },
    {
      id: "ra-ex-3",
      kind: "text",
      exType: "conceptual",
      difficulty: "Intermediate",
      concept: "agent-overuse",
      prompt: "Explain why a deterministic pipeline is usually preferable to an agent for transcript intent analysis.",
      rubric: [
        { idea: "The steps are known in advance", keywords: ["known", "fixed", "flowchart", "predetermined", "sequence"] },
        { idea: "Testable / evaluable per stage", keywords: ["test", "evaluate", "per-stage", "measure"] },
        { idea: "Cheaper / faster / bounded", keywords: ["cheaper", "cost", "latency", "faster", "bounded"] },
        { idea: "Auditable / deterministic / reproducible", keywords: ["audit", "deterministic", "reproducib", "predictable"] },
      ],
      minIdeas: 3,
      hint: "What does an agent add, and do you need it?",
      modelAnswer:
        "The sequence (normalize → extract → classify → verify) is known, so an agent's dynamic control flow adds nothing but nondeterminism. A pipeline is cheaper and faster (no planning loops), each stage can be evaluated on its own gold labels, runs are reproducible, and every decision is auditable — important for disputes and compliance.",
      explanation: "Use the simplest architecture that meets requirements.",
    },
    {
      id: "ra-ex-4",
      kind: "text",
      exType: "engineering",
      difficulty: "Advanced",
      concept: "rag-overuse",
      prompt: "A stakeholder asks for “RAG over all past transcripts” to improve intent classification. Write your recommendation.",
      rubric: [
        { idea: "The evidence is already in the current transcript", keywords: ["already in", "transcript contains", "no external knowledge", "in the call", "current transcript"] },
        { idea: "Retrieved past calls can anchor/bias the answer", keywords: ["bias", "anchor", "copy", "neighbour", "neighbor", "past outcomes"] },
        { idea: "Better alternatives: curated few-shot examples, clearer definitions", keywords: ["few-shot", "examples", "definition", "curated", "prompt"] },
        { idea: "Evaluate any change against the baseline on a gold set", keywords: ["evaluate", "gold", "baseline", "compare", "paired"] },
      ],
      minIdeas: 3,
      hint: "Where is the knowledge, and what would retrieval add?",
      modelAnswer:
        "Don't add RAG for this task: everything needed to classify intent is in the current transcript, and retrieving similar past calls (with their outcomes) tends to anchor the model on neighbours' labels. Instead, curate boundary-focused few-shot examples from the training split and tighten label definitions. If the stakeholder still wants to try RAG, compare it against the baseline on the gold set with a paired test before adopting it.",
      explanation: "Respond to architecture requests with the knowledge-gap question and an evaluation plan.",
    },
  ],
  quiz: [
    {
      id: "ra-q-1",
      kind: "mcq",
      difficulty: "Beginner",
      concept: "rag-overuse",
      prompt: "RAG is most appropriate when…",
      options: [
        { text: "Needed knowledge is external, large and changing", correct: true },
        { text: "The input contains all needed information", whyWrong: "Then no retrieval is needed." },
        { text: "The data is a small, stable rulebook", whyWrong: "Put it in the prompt." },
        { text: "You want lower latency", whyWrong: "RAG adds latency." },
      ],
      hint: "Knowledge gap + scale.",
      explanation: "RAG fills knowledge gaps too big for the prompt.",
    },
    {
      id: "ra-q-2",
      kind: "mcq",
      difficulty: "Intermediate",
      concept: "rag-overuse",
      prompt: "In a RAG system, a wrong answer could be caused by…",
      options: [
        { text: "Retrieval missing the right passage, or generation misusing it — evaluate both", correct: true },
        { text: "Only the generator", whyWrong: "Retrieval misses are a major source." },
        { text: "Only the retriever", whyWrong: "Generators can misread correct passages." },
        { text: "Tokenization only", whyWrong: "No." },
      ],
      hint: "Two stages.",
      explanation: "Measure retrieval recall@k and answer faithfulness separately.",
    },
    {
      id: "ra-q-3",
      kind: "mcq",
      difficulty: "Intermediate",
      concept: "agent-overuse",
      prompt: "The defining property of an agent is…",
      options: [
        { text: "The model chooses its next actions/tool calls in a loop", correct: true },
        { text: "It uses a large model", whyWrong: "Size is irrelevant." },
        { text: "It has a system prompt", whyWrong: "All chat models do." },
        { text: "It uses RAG", whyWrong: "Separate concept." },
      ],
      hint: "Who decides the control flow?",
      explanation: "Model-driven control flow.",
    },
    {
      id: "ra-q-4",
      kind: "multi",
      difficulty: "Intermediate",
      concept: "agent-overuse",
      prompt: "If you must deploy an agent, which safeguards are essential? (Select all)",
      options: [
        { text: "Step, time and cost limits", correct: true },
        { text: "Least-privilege (start read-only) tools", correct: true },
        { text: "Logged trajectories and evaluation on task success", correct: true },
        { text: "Unlimited retries for robustness", whyWrong: "Unbounded loops are a primary agent risk." },
      ],
      hint: "Bound, restrict, observe.",
      explanation: "Limits, permissions and observability.",
    },
    {
      id: "ra-q-5",
      kind: "mcq",
      difficulty: "Advanced",
      concept: "rag-overuse",
      prompt: "Retrieving similar past calls (with their labels) into the prompt to classify a new call risks…",
      options: [
        { text: "The model copying neighbours' outcomes instead of reading this call", correct: true },
        { text: "Lower token usage", whyWrong: "It increases tokens." },
        { text: "Guaranteed accuracy gains", whyWrong: "It can hurt." },
        { text: "Nothing", whyWrong: "It's a known failure mode." },
      ],
      hint: "Anchoring on retrieved examples.",
      explanation: "Retrieved examples act as uncontrolled few-shot demos; curated examples are safer.",
    },
  ],
  challenge: {
    id: "ra-ch-1",
    kind: "label",
    exType: "engineering",
    difficulty: "Advanced",
    concept: "rag-overuse",
    prompt: "Choose the simplest adequate architecture for each task.",
    labels: ["Deterministic code", "Single LLM call / pipeline", "RAG", "Agent"],
    passThreshold: 0.8,
    items: [
      { text: "Extract loan amount, tenure and intent from each call", answer: "Single LLM call / pipeline" },
      { text: "Parse '50 L' and 'five lac' into integers", answer: "Deterministic code" },
      { text: "Answer agents' questions about 400 pages of monthly-changing policy PDFs", answer: "RAG" },
      { text: "Investigate a stalled application across 3 systems where each lookup decides the next", answer: "Agent" },
      { text: "Check the quoted rate against a keyed rate table", answer: "Deterministic code" },
    ],
    hint: "Knowledge location and control flow.",
    explanation: "Most items don't need RAG or agents. Use them only for external unstructured knowledge (RAG) or non-enumerable tool-driven procedures (agent).",
  },
  related: ["pipeline-design", "context-engineering", "embeddings"],
  terms: ["rag", "agent", "semantic-search", "pipeline"],
};
